### ISSUE TITLE
Unable to round trip data

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#1002]
**What version of EMX2 are you using (see footer)**
8.52.0

**Describe the bug**
Data import into empty schema fails 

**To Reproduce**
Go to server en download all data al zip  ( for example; https://emx2.molgeniscloud.org/Catalogue/updownload/)
Go to other server and upload all data into empt schema ( for example; localhost)

**Expected behavior**
Data gets uploaded, schema is created and filled with data

**Comment by BrendaHijmans** [comment]
have you tried with updated version of software?

**Comment by mswertz** [comment]
Might this have to do that 'catalogue' actually depends on other schemas? Which you also need to download?

We could address this with feature: 'download / upload multiple schemas'
