### ISSUE TITLE
Filled out data in ontology and ontology_array data types is not visible when editing in forms

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#1008]
**What version of EMX2 are you using (see footer)**
8.54.0

**Describe the bug**

**To Reproduce**
1. Go to  https://emx2.dev.molgenis.org/Conception-test/tables/#/Cohorts
2. See that e.g. countries, and type are filled out for cohort called 'test' if you scroll to the right in the table shown
3. Try to edit this cohort in forms: these fields are not visibly filled out in the form, as if no data is present.

**Comment by connoratrug** [comment]
Can not reproduce , please add all relevant fields and precise step to reproduce

**Comment by mswertz** [comment]
I can reproduce this on this server on my machine. E.g. in Cohorts first record has 'Denmark' selected in countries. When I open the form Denmark is not shown as selected. When I reproduce in styleguidist, i.e., create an example with value = [{name:"Denmark"}] I also see it is not properly shown.
