### ISSUE TITLE
Int and Decimal Form input fields don't accept negative numbers

### ISSUE THREAD

**Issue by MaxPostema** [molgenis/molgenis-emx2#1010]
**What version of EMX2 are you using (see footer)**
v8.51.1

**Describe the bug**
Int and Decimal Form input fields don't accept negative numbers

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org/apps/styleguide/#!/InputInt'
2. Try to enter a negative number to a int field
3. notice that the 'minus' key is blocked

**Expected behavior**
I can type a number like "-3"

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome (any)
- Version: 98 (any)

**Note**
Adding the minus key to the accepted input list wil not solve the problem. That will make "3-3" a valid input but an invalid value. Something smarter is needed to keep the "input is always valid design philosophy"
https://github.com/molgenis/molgenis-emx2/blob/2c50c733c8b131ee15492237a23d44bf50311290/apps/styleguide/src/forms/InputInt.vue#L28

**Comment by mswertz** [comment]
closed in #957
