### ISSUE TITLE
Field Cohorts.releaseType cannot be filled out

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#1031]
**What version of EMX2 are you using (see footer)**
8.51.0

**Describe the bug**
When trying to fill out Cohorts in forms, it is not possible to select anything under releaseType, which has columnType ontology. Also, remarkably, the appearance of this field in forms is different from that of e.g. design, which also has clumnType ontology:
![image](https://user-images.githubusercontent.com/42644481/157448535-5753c502-804f-467a-912d-c3b0758eabb3.png)
![image](https://user-images.githubusercontent.com/42644481/157449006-7140f08b-1c5c-4178-8f0a-32fbdc688ce5.png)

**To Reproduce**
1. Go to 'https://catalogue-acc.molgeniscloud.org/testCohort_update/tables/#/Cohorts' (log in as admin)
2. Try to edit testCohort
3. Try to fill out releaseType

**Comment by connoratrug** [comment]
related to https://github.com/molgenis/molgenis-emx2/issues/1008
