### ISSUE TITLE
When you click on 'Show more', you jump to the heading of the page, show more does work

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#1033]
**What version of EMX2 are you using (see footer)**
8.54.1

**Describe the bug**
When you click on show more, the view jumps to the start of the webpage. It would be nicer if you stay at the part of the page where you click 'show more'

**To Reproduce**
1. Go to ['https://emx2.test.molgenis.org'](https://emx2.dev.molgenis.org/Conception-test/catalogue/#/), log in as admin
2. Scroll down
3. Click on show more in a column of choice
4. View jumps to start of page.

**Comment by connoratrug** [comment]
version mix up , it is fixed
