### ISSUE TITLE
In Catalogue NetworkView I would like a link for Models

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#1075]
**What version of EMX2 are you using (see footer)**
5.58.2

**Describe the bug**
-There are no links connecting Networks to Models or DataDicionaries, e.g.: https://brenda3.molgeniscloud.org/EMA-demo/catalogue/#/networks/EH
-Or connecting DataDictionaries to Tables, e.g.: https://brenda3.molgeniscloud.org/EMA-demo/catalogue/#/target-datadictionaries/EH_CDM/1.0

**To Reproduce**
1. Load testdata: 
[testData.zip](https://github.com/molgenis/molgenis-emx2/files/8302156/testData.zip)
2. Go to Catalogue
3. Click on Networks, and select a network
4. See there is nothing under Contents, there should be a link to a model there.

**Comment by mswertz** [comment]
On the first link, I see a 'Models' link on the bottom of page?
The second indeed also broken on my screen. However, I can see https://brenda3.molgeniscloud.org/EMA-demo/catalogue/#/target-data-dictionaries/EH_CDM/1.0

**Comment by BrendaHijmans** [comment]
the link is missing in Models, because only RWEresources have a refback 'dataDictionaries' referring to SourceDataDictionaries.

data model is change is needed: Cohorts and Models need a refback 'dataDictionaries' referring to  SourceDataDictionaries and TargetdataDictionaries, respectively.
