### ISSUE TITLE
Databank view shows error and unable to add new databank

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#1090]
**What version of EMX2 are you using (see footer)**
8.47.0

**Describe the bug**
Catalogue view of Databanks shows sql error and I'm unable to add new databank

**To Reproduce**
1. Go to 'https://data-catalogue-staging.molgeniscloud.org/Immune-Image/catalogue/#/Databanks'
2. You see an sql error
3. Click on '+' on the table next to PID to add databank
4. Fill in PID and Name and try to save
5. No error message but databank is not saved

**Expected behavior**
Be able to view page without error and be able to add databank

**Screenshots**
![molgenis-8 47 0_error-databank](https://user-images.githubusercontent.com/4077085/159737906-a306341b-f5f0-4e4e-9410-1117bd3a2d6a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04LTS
 - Browser Chromium
 - Version 99.0

**Comment by BrendaHijmans** [comment]
need to update to higher version of software
