### ISSUE TITLE
Extensive reliance on static methods

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#1100]
**What version of EMX2 are you using (see footer)**
8.x

**Describe the bug**
Extensive reliance on static methods makes the code tightly coupled ( and therefore hard to test and maintain)

**Comment by connoratrug** [comment]
Could you please then suggest a way to test the code without running a complete instance of the system. The current 'smoketests' test to slow, for development use,  coverage is limited, and unstable in CI context.

**Comment by mswertz** [comment]
normally you should put all your logic in a bean. The Sparkjava web API should only provide a very thin layer around such beans. See for example how graphql and csv do it. There all real logic is actually in classes that you can test. Then only integration tests are remaining which should take form of smoke tests to test if the API is actually connected

**Comment by connoratrug** [comment]
The comment does not answer the question and closing the issue solve the reported issue.
