### ISSUE TITLE
Components lib demo app references image file that is not part or source code 

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#1216]
**What version of EMX2 are you using (see footer)**
8.69.8

**Describe the bug**
Components lib demo app references image file that is not part or sources code , resulting in the image not being shown and an error in the console
```Failed to load resource: the server responded with a status of 404 (Not Found)```
http://localhost:3000/assets/img/molgenis_logo.png

**To Reproduce**
Open the 'molgenis-components' app and view the menu ( and console)

**Additional context**
Most likely copy paste error from styleguide dist build

**Comment by mswertz** [comment]
not an error but a missing resource that also needs to be copied, see styleguide/public/assets/img
