### ISSUE TITLE
Eleborate feedback on uploaded data is not showing anymore

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#1258]
**What version of EMX2 are you using (see footer)**
8.71.0

**Describe the bug**
Upload of data via interface used to give feedback on which tables are imported and how many rows etc. This is not the case anymore. 

**To Reproduce**
1. Go to https://emx2.dev.molgenis.org/
2. Download test cat 
3. Upload downloaded data
4. You only get feedback dat csv was imported.
5. Same happens with excel upload

**Comment by joerivandervelde** [comment]
In addition:
- when importing CSVs, importer should make clear that any files NOT matching table names are interpreted as 'molgenis.csv' i.e. the metadata schema
- any errors thrown in that context should be labeled RED and not GREEN as they are now.
