### ISSUE TITLE
keywords met komma's in het Catalogue model

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#126]
Go to emx2 demo lifecycle schema 
Create a zip from the files:
[Keywords.csv](https://github.com/molgenis/molgenis-emx2/files/6325303/Keywords.csv)
[Variables.csv](https://github.com/molgenis/molgenis-emx2/files/6325306/Variables.csv)

import the zip:

**Expected:**

The data is successfully imported 

**Observed** 
Error during import , data is not imported 

![Screenshot 2021-04-16 at 15 24 05](https://user-images.githubusercontent.com/47183404/115030975-f4f04680-9ec7-11eb-9012-5f9a89be079b.png)

Sommige LifeCycle topics (in nieuwe EMX2 Catalogue model zijn dat keywords) zijn zinnen en soms staat er dan ook een komma in.
keywords met komma's erin worden wel goed ingeladen in de tabel Keywords, maar worden dan niet goed herkend bij het inladen in de tabel Variables

**Comment by mswertz** [comment]
Hi. 

In case you have comma an a field, then it should be quoted when using CSV

In case you have a 'ARRAY' field (such as REF_ARRAY) with multiple values AND commas in you csv, then you need to escape with \,

For example: can you please test the following works?

`
col1,col2
col1value,"\"value in col 2 with, comma\",\"and, more, commas\""
`

**Comment by BrendaHijmans** [comment]
Both examples files in the issue description contain quotes around the filed that raises the issue ("Respiratory, allergy and skin characteristics"). Keywords.csv is successfully uploaded, Variables.csv raises the issue: the field within quotes is cut at the comma.

**Comment by mswertz** [comment]
Did you try to put quotes around the values? 

In addition, I was asking if you have ideas to make this easier. There are different solutions. Currently we use quotation to indicate that a comma is part of the value and not an array seperator. But instead we could use a special character instead (e.g. pipe symbol `|`).

**Comment by BrendaHijmans** [comment]
There are quotes around the values (see files attached to issue). 

Quotations seem fine to me. The use of a special characters may be cumbersome.

**Comment by mswertz** [comment]
I made an error with quote escaping (fixed above). Because it is a array, each value (even if it is only one) must be also quoted like so:

```
"""Respiratory, allergy and skin characteristics"""
````

In case of two values it makes more sense 

"""Respiratory, allergy and skin characteristics1"",""Respiratory, allergy and skin characteristics2"""
