### ISSUE TITLE
Table view does not show correct Mappings/ETLs to Table

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#1288]
**What version of EMX2 are you using (see footer)**
8.62.2

**Describe the bug**
On the SourceTable page (AP): https://conception-acc.molgeniscloud.org/Conception/catalogue/#/source-tables/AP/1.0/AP
The Mappings/ETLs are shown but not distinguishable, they are called:
* To: AP - Version: 1.0 - Table: AP
* To: AP - Version: 1.0 - Table: AP
But should be:
* To: AP - Version: 1.0 - Table: VISIT_OCCURRENCE
* To: AP - Version: 1.0 - Table: MEDICAL_OBSERVATIONS

**To Reproduce**
1. Go to 'https://conception-acc.molgeniscloud.org/Conception/catalogue/#/source-tables/AP/1.0/AP'
2. See error

**Expected behavior**
* To: AP - Version: 1.0 - Table: VISIT_OCCURRENCE
* To: AP - Version: 1.0 - Table: MEDICAL_OBSERVATIONS

**Screenshots**
![molgenis-8 62 2_table-mappings-etl](https://user-images.githubusercontent.com/4077085/169067330-157d6cec-704e-46bd-80ed-566ac1a61567.png)

![molgenis-8 62 2_table-mapping_1](https://user-images.githubusercontent.com/4077085/169067346-4963327a-e293-4025-9184-a2d36dc38544.png)
![molgenis-8 62 2_table-mapping_2](https://user-images.githubusercontent.com/4077085/169067382-53ad269f-3f42-4417-a3e1-c295810ff2da.png)

**Desktop (please complete the following information):**
 - OS: [ubuntu]
 - Browser [chromium]
 - Version [101.4951.64]

**Comment by RosaMGini** [comment]
I think it should be the other way around? AP is the origin table, and VISIT_OCCURRENCE and MEDICAL_OBSERVATIONS are the target table

**Comment by RosaMGini** [comment]
@erikzwart any news on this bug? There has been great progress on the ETL data so as soon as this bug is fixed it will be possible to profit from the new data that is now in

**Comment by RosaMGini** [comment]
@EleanorHyde-UMCG let me know when you have feeback on this! cheers, rosa

**Comment by connoratrug** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#9100 Verwerken feedback VAC4EU, bugs en features](https://trello.com/c/x0lVToBd/483-9100-verwerken-feedback-vac4eu-bugs-en-features)
