### ISSUE TITLE
URLs without "https://" in cohorts view don't work

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#1299]
**What version of EMX2 are you using (see footer)**
8.88.1

**Describe the bug**
If a user adds and url in their cohort description without https:// in front of it the url doesn't work.

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'
2. Click on 'tables' > 'cohorts'
3. Add an url for a cohort without https:// and the url in the cohorts view is broken
For example: for cohort 'CSC' the url is filled in as _nkcx.se_. If you click on website in the cohorts view (https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue/HEAP/cohorts) you are redirected to _https://data-catalogue.molgeniscloud.org/public_html/apps/catalogue/nkcx.se_ 
If you fill in _https://nkcx.se_ the url does work.

**Comment by mswertz** [comment]
that is not really a bug is it? The real bug we might want to post is that the URL should use an URL input that will check if an URL is valid, which means indeed it should be prefixed by http:// https:// mailto: ftp:// etc.

**Comment by marijevdgeest** [comment]
Maybe, but then we should be really clear to users as this field is filled in manually and I think most people don't put http in front of it while typing a url

**Comment by mswertz** [comment]
Yes, should be validation error then agreed?

**Comment by mswertz** [comment]
You can find a fix for this in #1607
