### ISSUE TITLE
Menu link to docs does not work

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#137]
**Describe the bug**
When trying to view the docs i get an error 

**To Reproduce**
1. Go to https://emx2-catalogue.test.molgenis.org/
2. Click on 'Docs;

**Expected behavior**
Expected to see the docs ( did not expect new tab)

**Additional context**
Version: 5.17.0 .

**Comment by mswertz** [comment]
link has been removed until proper docs exists
