### ISSUE TITLE
Error signing into umcgresearchdatacatalogue.nl/ using chromium

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#1375]
**What version of EMX2 are you using (see footer)**
v8.71.0

**Describe the bug**
Try to sign in and I get an error:
{
  "errors" : [
    {
      "message" : "State cannot be determined"
    }
  ]
}

This occurs when I use chromium (102.0.5005.115), Firefox behaves correctly

**To Reproduce**
1. Go to 'https://www.umcgresearchdatacatalogue.nl/apps/central/#/' using Chromium as a browser
2. Click on 'Sign in'

**Expected behavior**
I expect to see login menu (Firefox):
![molgenis-8 71 0_Sign-in_menu](https://user-images.githubusercontent.com/4077085/174590270-9ca78e8f-096b-447e-a487-993e72c360d0.png)

**Screenshots**
Chromium
![molgenis-8 71 0_Sign-in](https://user-images.githubusercontent.com/4077085/174590331-fba1c5bf-e73e-4b45-9284-80b42d1dec47.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser Chromium, Firefox
 - Version 102.0.2005.115 , 101.0.1

**Comment by mswertz** [comment]
cannot reproduce anymore
