### ISSUE TITLE
Emx2 is missing a model version for the metadata schema

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#140]
**Describe the bug**
Cannot upload downloaded model

**To Reproduce**
Download the schema 
some time later  ( for example 19 days )
Upload the schema

**Expected behavior**
Schema is uploadend without errors

or 

Message is show that model version is incompatible

**Comment by mswertz** [comment]
Of course we can add version but then we also need to check. The mistake here was that a breaking change that was not marked as such. And even then it would not be known to the user. So my proposal would be to save version of the software that created the schema to the database, and then in case of change add migration scripts if possible and update to that version (that would have been possible in this case) or break with a clear error (in that case I would call this a major version change).
