### ISSUE TITLE
Missing tables after import

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis-emx2#144]
**Describe the bug**
Missing tables after import, even though they are there

**To Reproduce**
Unsure. Happened a couple of times. A rough idea of what we did:
* Delete existing filled cde database.
* Create new cde database
* Grant Viewer permission to anonymous user
* Upload 
[emx2-cde-fdp-rml-compat-v2.xlsx](https://github.com/molgenis/molgenis-emx2/files/6364992/emx2-cde-fdp-rml-compat-v2.xlsx) into the cde schema
* Go to the tables list
* *sometimes* nothing is present
* The tables suddenly appear if you repeat a combination of 
  * refresh the tables list
  * go to the schema page
  * log out and log back in again

**Expected behavior**
The tables are there right away

**Screenshots**

**Version**
5.25.0

**Comment by mswertz** [comment]
We believe this is fixed but please add if you rediscovered the issue
