### ISSUE TITLE
When I fill in a String field longer than 255 I get not easy to understand error message

### ISSUE THREAD

**Issue by mswertz** [molgenis/molgenis-emx2#1447]
Expected: user interface warns before save

Current: 
![image](https://user-images.githubusercontent.com/120060/178697309-44721363-45c4-436a-94fc-6c37c41b1df9.png)

**Comment by connoratrug** [comment]
i thing the design description field is set to String ( the default ) but should of type Text ? , https://github.com/molgenis/molgenis-emx2/blob/cf2f4254bccf90229349afb3e2c1084d1a25b822/data/datacatalogue/molgenis.csv#L41

**Comment by connoratrug** [comment]
Closes by https://github.com/molgenis/molgenis-emx2/pull/1493
