### ISSUE TITLE
Catalogue ref link validation fails, when data is correct

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#1449]
**What version of EMX2 are you using (see footer)**
8.108.3

**Describe the bug**
Field validation fails for TableMappings.fromTable when correct selection is made

**To Reproduce**
1. Login as admin / editor
2. Load a catalog model with demo data 
3. Go to the tables app
4. Add / Edit a TableMappings row 
5. enter required fromDataDictionary and fromTable field

**Expected behavior**
the formTable selection is constrained by the fromDataDictionary and when selecting a table from the selected data dictionary, the field validation succeeds.

**Comment by mswertz** [comment]
can't reproduce at [8.188.0](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.188.0)
