### ISSUE TITLE
When entering data manually selecting 'False' remains empty after saving

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#1456]
**What version of EMX2 are you using (see footer)**
8.108.3

**Describe the bug**
Email Adriaan Eldering (14/07):

> Dag Support,
> 
> Ik heb vandaag een overleg gehad met een onderzoeker om de catalogus in te vullen. Zij gaf aan dat wanneer zij het veld dataAccessFee invulde en het formulier opsloeg, dat dataAccessFee daarna weer leeg was. Ik heb dit zelf even getest en dit gebeurt bij mij ook in een test-cohort. Het gebeurt echter alleen wanneer ik False invul in dit veld. Ik heb dit getest met mijn eigen account en niet met het admin account, zodat ik dezelfde rechten had als de onderzoeker. 
> 
> Voor het opslaan:
![image002](https://user-images.githubusercontent.com/8653334/178995535-81988045-62f6-4e3d-a9bb-f408cee7b729.png)

![image003](https://user-images.githubusercontent.com/8653334/178995548-137025f9-3385-4934-a7b0-b45cfce15f48.png)

**Comment by erikzwart** [comment]
Same as #647

**Comment by mswertz** [comment]
Does this still exist in molgenis-components based UX?

**Comment by mswertz** [comment]
Cannot reproduce in [8.189.3](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.189.3)

<img width="355" alt="image" src="https://github.com/molgenis/molgenis-emx2/assets/120060/9223238e-bf96-40c8-9c8b-db626e4b247b">
