### ISSUE TITLE
Change in table prop results in change in column order

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#1495]
**What version of EMX2 are you using (see footer)**
8.110

**Describe the bug**
Using a gql command to update a table meta data prop ( for example field type) results in a change of column order ( the changed field becomes the last column.

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'
2. run a change command ```mutation{change(columns: {table: \"Pets\", name: \"name\", columnType: \"TEXT\"}){message}} ```
3. column name is now the last column

**Expected behavior**
Column order does not change

**Comment by mswertz** [comment]
You can add 'position' to your call if you care about the order, i.e.

`mutation{change(columns: {table: \"Pets\", name: \"name\", columnType: \"TEXT\", position: 0})

I suppose that your 'bug' here is that position is being touched, correct?
And I also see that the first position is not being set so it seems, if I query the _schema of Pet store

**Comment by connoratrug** [comment]
I did not about the position prop , that perfect

**Comment by mswertz** [comment]
I think you still found a bug because if one doesn't provide position then previous position should not be changed
