### ISSUE TITLE
Missing semantics for ontology tables

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis-emx2#1548]
Semantics can be added to regular tables to denote the 'class' of its 'instances' (i.e. rows), as well as its attributes (columns) to define the concepts that are given a value for a particular instance.

However, semantics cannot be applied to Ontology tables. This is can help to separate the attribute from the class of its lookup values.

For example:

The attribute Medication (defined by [NCIT:C459](http://purl.obolibrary.org/obo/NCIT_C459)) links to instances of 'Drugs' in an Ontology table containing e.g. paracetamol (defined by [ATC:N02BE01](http://purl.bioontology.org/ontology/ATC/N02BE01)). If the table 'Drugs' would have semantics, its class could be defined as ATC codes ([EDAM:data_3103](http://edamontology.org/data_3103)).

This would result in a more complete picture: The concept of Medication is expressed as ATC codes such as paracetamol. Or: medication includes paracetamol, which belongs to the class ATC codes.

**Comment by mswertz** [comment]
How should this work @joerivandervelde ?

In new schema editor semantics on table level is exposed. Would this solve it? See #1520

**Comment by joerivandervelde** [comment]
Implemented in https://github.com/molgenis/molgenis-emx2/pull/1763
