### ISSUE TITLE
Uploading templates to data-catalogue-staging with information not in refs/ontologies is possible, but breaks forms

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#1550]
**What version of EMX2 are you using (see footer)**
8.110.0

**Describe the bug**
When a user uploads templates with information that's invalid (for example not in CatalogueOntologies), the file can be uploaded, but it breaks the form editor for that specific row.

**To Reproduce**
1. Go to 'https://data-catalogue-staging-test.molgenis.org'
2. Go to CONSTANCES schema
3. Click Up/Download
4. Upload first _SourceDictionary_constances_bug.xlsx_ and then _SourceMappings_constances_bug.xlsx_  (Files in comment!)
-> These files upload variablemappings for variables in LifeCycle_CDM, but tries to upload these to LongITools_CDM (this also happens when you try to upload information that's not available in CatalogueOntologies)
6. Go to table VariableMappings
7. Click on edit button for a row, you see the form is broken. 

**Expected behavior**
Error that the file cannot be uploaded

**Comment by marijevdgeest** [comment]
[SourceDictionary_constances_bug.xlsx](https://github.com/molgenis/molgenis-emx2/files/9452371/SourceDictionary_constances_bug.xlsx)
[SourceMappings_constances_bug.xlsx](https://github.com/molgenis/molgenis-emx2/files/9452372/SourceMappings_constances_bug.xlsx)

**Comment by connoratrug** [comment]
The 'https://data-catalogue-staging-test.molgenis.org/' mentioned in the issue is not running, @marijevdgeest is it possible to (re)create minimal reproducible example ( using the catalogue demo data set , or even the minimal pet store example ) ?

**Comment by erikzwart** [comment]
Tried to reproduce issue through web form (gui) and template but emx2 throws errors when it should. Still can not find how users are able to select variables from networks that are not defined in SourceTable.mappings

**Comment by erikzwart** [comment]
The cohort NAWC on data-catalogue-staging seems to have this issue, they where able to upload a template with empty values that are (should) be mandatory:
https://data-catalogue-staging.molgeniscloud.org/NWAC/tables/#/
![VariableMappings_empty](https://user-images.githubusercontent.com/4077085/188907230-a30c70c3-7066-43bf-b488-a0bf22a105b1.png)
![update_VariableMappings](https://user-images.githubusercontent.com/4077085/188907272-fc9020d7-4421-4e2f-9121-8e11e69c029a.png)

They used the following template:
[SourceMapping_StorKohort.xlsx](https://github.com/molgenis/molgenis-emx2/files/9507152/SourceMapping_StorKohort.xlsx)

Export of st
[NAWC_staging_2022-09-07_1633.zip](https://github.com/molgenis/molgenis-emx2/files/9507154/NAWC_staging_2022-09-07_1633.zip)
aging area:

**Comment by mswertz** [comment]
I just tried to upload on my machine. 

First downloaded
- DataCatalogue
- SharedStaging
- CatalogueOntologies

Then uploaded in right order
- Uploaded schema for shared staging, datacatalogue
- Uploaded data into ontologies, shared staging, datacatalogue

Finally, tried top upload NACW, however then I got an error. 

This leads to working hypothesis that might totally wrong:
- upload constraint checking might be fine, it is just that constraints are not checked if refered data is then changed. In casu: reference to EPHOR_CDM which doesn't exist later
- so the way of cleaning is to download and then try to upload. You will then find all errors.
- Meanwhile, there should be a bug that we can change related data, breaking it all after the fact.

**Comment by erikzwart** [comment]
![image](https://user-images.githubusercontent.com/4077085/189292627-7d321598-ccd6-461b-84b3-71d3068609b0.png)
NWAC uploaded these 2022-09-06 see screenshot (mg_insertedOn, mg_updatedOn), notice the update time 1:10 after inserting. Did something happen there while updating the records or is it a delayed update from db?
