### ISSUE TITLE
When you filter or sort a table, navigation doesn't work anymore

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#1552]
**What version of EMX2 are you using (see footer)**
8.110.0

**Describe the bug**
After filtering or sorting a table, going to the next 'page' and changing the number of rows shown (10, 20, 100 etc.) is not possible anymore.

**To Reproduce**
1. Go to an emx2 server with v8.110.0 (data-catalogue-staging for example)
2. Click on a table
3. Filter or sort the table
4. Try to click the arrows or change the number of rows shown

**Comment by connoratrug** [comment]
fixed in 8.121.x
