### ISSUE TITLE
Creating schema from DATA_CATALOGUE_COHORT_STAGING template fails

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#1575]
**What version of EMX2 are you using (see footer)**
8.114.8

**Describe the bug**
Creating schema from DATA_CATALOGUE_COHORT_STAGING template fails

**To Reproduce**
1. Go to https://emx2.dev.molgenis.or
2. Click on plus icon to create a new schema
3. Select DATA_CATALOGUE_COHORT_STAGING as template and set load example data to TRUE
4. Click on create database
5. results in ```Error: Transaction failed: Add column 'Resources.institution' failed: 'refTable' required for columns of type REF, REF_ARRAY, REFBACK```

**Expected behavior**
DB is created with given settings

**Comment by mswertz** [comment]
can't reproduce in [8.189.3](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.189.3)
