### ISSUE TITLE
Memory in row input form

### ISSUE THREAD

**Issue by chinook25** [molgenis/molgenis-emx2#1683]
**What version of EMX2 are you using (see footer)**
8.121.3-SNAPSHOT

**Describe the bug**
Adding/editing rows causes the memory the browser is using to reach unacceptable levels. It frees again after a while (e.g. 30. seconds), but that is not fast enough.

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org'
2. Go / add a schema containing tables with lots of columns with REF like types (tested it on the ITHACA schema, subjects table)
3. Click on the button to add a row, or edit an existing one.
4. Close the modal en open it again a few times.
5. After enough times the browser starts to become laggy.
6. Check the task manager and see that the browser is taking up a few Gb too many of the memory.

**Expected behavior**
Closing the modal frees up the memory it used, immediately after closing. 
Maybe: closing the modal cancels outstanding requests.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 105.0.1

**Comment by mswertz** [comment]
@chinook25 is this problem alleviated with the new multi-page forms?

**Comment by chinook25** [comment]
@mswertz As for as I can test, when using multi-page the form is split up enough for this not to happen. Of course, if you don't use them this can still occur.

**Comment by mswertz** [comment]
closed because workaround of multi-page form.
