### ISSUE TITLE
Exports of 'Abstract'  tables are empty.

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#181]
**Describe the bug**
When you export an abstract table (e.g. OntologyTerms, Resources, AllVariables), the file is empty.

**To Reproduce**
1. Go to https://emx2-catalogue.test.molgenis.org/LifeCycle4/updownload/
2.  Download the whole dataset or specific tables in Excel. The tables OntologyTerms, Resources or AllVariables appear empty, while they are not empty when viewing the data under 'Tables'

**Expected behavior**
I expect to get an export with the information that I see when I go to the specific tables themselves in the Table view.

 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 5.31.0

**Comment by mswertz** [comment]
Ah, this is a good question where I am not sure it works as intended. OntologyTerms, Resources and AllVariables are superclass tables that in fact don't contain data. However, in the data explorer it has been setup that you can also see the data from their subclass tables (e.g. Variables). What I noticed is that it doesn't show a column indicating what subclass table the data is actually in, would that be solving it it?
