### ISSUE TITLE
Routed filters can cause error

### ISSUE THREAD

**Issue by chinook25** [molgenis/molgenis-emx2#1833]
**What version of EMX2 are you using (see footer)**
8.127.3

**Describe the bug**
Adding numerical filters that have from-to values throw error on refresh if on or both of the values are empty.

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/pet store/tables/#/Order'
2. Add a filter for price with something like 'from 5 to *empty*' 
3. refresh the page 
4. See error: TypeError: undefined has no properties

**Expected behavior**
I expect that on refresh no error is thrown as a filter with just from or to should be a viable filter.

**Comment by mswertz** [comment]
has been fixed in
