### ISSUE TITLE
Auth tokens should be passable via multiple (user-defined?) header keys

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis-emx2#1857]
Right now, auth tokens are passed with request header key `x-molgenis-token`. However, when complying to specific standards or specifications, this could be a different key. For instance the latest update to the Beacon VP spec (https://github.com/rini21/vp-api-specs-beaconised) will pass auth tokens under key `auth-key`. We can probably add more key names by hard coding (it will not happen so often), but another option could be a flexible runtime mechanism. What would be best? Added priority label because a solution will be needed fast for VP onboarding of EMX2 instances.

**Comment by mswertz** [comment]
if this is a standard beacon option, then we can change emx2 to also support 'auth-key'. Assuming this will be a general beacon spec. However, ideally the beacon index should take care of this. 

Does this architecture use a central server that we must trust? I would prefer an architecture that doesn't have a server in the middle, so we would be dealing with end users instead directly using oauth (i.e. we sign in in lifescience AAI and then all servers connected to same lifescience AAI realm would know that we can be trusted).

If this uses a central server then I think we need to extend our security mechanism to also say that we only trust requests from a specific central server (so our tokens cannot be reused from other sites).
