### ISSUE TITLE
Users are able to upload faulty data to staging areas

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#1876]
**What version of EMX2 are you using (see footer)**
8.121.2

**Describe the bug**
Users are able to upload faulty data to staging areas, e.g. in VariableMappings table. Data contains faulty refs to case sensitive table names. After uploading faulty data, the toTable and toVariable have disappeared and when you try to edit a VariableMapping all information is empty. 
![image](https://user-images.githubusercontent.com/42644481/206424935-f4e012e2-0515-4adb-bc9a-1c9e275d2ca7.png)

**To Reproduce**
1. Go to 'data-catalogue-staging-test' and log in
2. Click on PIAMA staging area
3. Upload faulty data file with toTable 'CardioMetabolic' (should be 'Cardiometabolic') 
[VariableMappings.zip](https://github.com/molgenis/molgenis-emx2/files/10184581/VariableMappings.zip)
4. Upload should throw an error, but data is uploaded.
5. Go to VariableMappings table, see there are empty entries in column toTable and toVariable, which are obligatory ![image](https://user-images.githubusercontent.com/42644481/206424935-f4e012e2-0515-4adb-bc9a-1c9e275d2ca7.png)
6. Try to edit a row and see that form is empty ![image](https://user-images.githubusercontent.com/42644481/206425448-a3480baa-41f2-42f3-951b-9f16b20548bb.png)
7. NOTE: data in VariableMappings.zip cannot be uploaded to catalogue (throws an error), bug is only present when uploading to staging areas.

**Expected behavior**
Upload of faulty data should not be possible, should give an error like this:
![image](https://user-images.githubusercontent.com/42644481/206427700-48a94c1d-4dd3-455e-8723-a6bc41e4b5b1.png)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marijevdgeest** [comment]
Pelagie had this issue as well, basically everything broke:
- Wrong toVariable mapping
- Wrong toTable mappings (in both VariableMappings and TablesMappings)
- Wrong version number mappings
- Mappings to dictionaries that do not yet exist in the catalogue

**Comment by mswertz** [comment]
Again, the foreign key that should be there for toTable and toVariable is NOT set in the SQL. Damn.

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/120060/209014466-4673f039-a04d-4b7b-8c2c-859245d497eb.png">

**Comment by mswertz** [comment]
Hypothesis: every time that we delete the Network schema, all foreign keys between VariableMappings and Network schema are also removed. Actually, you should not be able to delete Network schema. Therefore you can upload erroneous values.

What is unclear to me is why after that columns are delete completely.

**Comment by mswertz** [comment]
Confirmed. This happens when you drop the schema you refer to. In the future we will disable the 'cascade' options on schema delete. Then you will get an error that says 'you cannot drop schema because objects depend on it'
