### ISSUE TITLE
GraphQL api returns too much data when applying a filter on a ref property

### ISSUE THREAD

**Issue by jelmerveen** [molgenis/molgenis-emx2#1878]
Given the following demo model:

```
Shops table
[Name]               [Fruit]
Mary's market        Apple, Pear, Banana
Joe's Delicasies     Pineapple, Kaki, Coconut
Farmer John's        Blueberry, Strawberry


Fruit table
[Name]
Apple
Pear
Banana,
Pineapple,
Kaki,
Coconut,
Strawberry,
Blueberry
```

**Is your feature request related to a problem? Please describe.**
When using the above model, when I want to get all shops that sell me anything that has 'apple' in it and only those products.

So when I query something like this:
```
Shops(filter: { shops: { fruit: { like: 'apple' } } } ) {
   name,
   fruit
}
```
I would expect to get:

```
Mary's market        Apple
Joe's Delicasies     Pineapple
```

But now I get:

```
Mary's market        Apple, Pear, Banana
Joe's Delicasies     Pineapple, Kaki, Coconut
```

**Describe the solution you'd like**
I would love to have a more sql like result. Or a way to filter the results better

**Comment by mswertz** [comment]
works as intended.

What you might like is subfiltering. Please rewrite as such. And your query is not correct.

E.g.

Shops(filter: { shops: { fruit: { like: 'apple' } } } ) {
   name
   fruit(filter: {name: {like: 'apple'}}){name}
}

**Comment by jelmerveen** [comment]
Ah you mean in my first query I actually have to have fruit selected as a property. Correct.

Being able to subfilter the results would be nice, but my solution question was open ended: ' Or a way to filter the results better'

Marking this in a whole as 'invalid' and 'wont fix' is a bit harsh isn't it?

**Comment by jelmerveen** [comment]
After doing some research, this would be the correct approach as you mentioned.

https://stackoverflow.com/questions/67925260/is-there-a-way-to-filter-elements-in-join-table-in-graphql
