### ISSUE TITLE
Nested filters only works for one level deep

### ISSUE THREAD

**Issue by jelmerveen** [molgenis/molgenis-emx2#1901]
**Is your feature request related to a problem? Please describe.**
For making complex queries from the old molgenis implementation easier, I would love to be able to nested filters deeper than one level. 2 or 3 would already help a lot.

**Describe the solution you'd like**
I would love to be able to perform such a query:

```
{
Biobanks(filter: { collections: {parentCollection: { id: { equals:"bbmri-eric:ID:AT_MUG:collection:ColorectalCancerCollection"}}}}) {
    id,
    name,
    collections(filter: { parentCollection: {name: {not_like: ""}} }) {
        id,
        name
        parentCollection(filter: { name: { like: "something_interesting"}}) {
	          id,
                  name
        }
    }
  }
}
```

**Describe alternatives you've considered**
Alternative would be doing a json filter on the client side. which could also work but takes more time.

**Comment by mswertz** [comment]
this is now solved, correct @jelmerveen ?
