### ISSUE TITLE
Download metadata with draft data

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#1970]
**Is your feature request related to a problem? Please describe.**
When downloading data, also draft data is downloaded. In .csv or excel draft and non-draft data are not different.

**Describe the solution you'd like**
We need options to:
1. download data without drafts
2. download data with drafts AND with metadata explaining this is draft data

**Comment by erikzwart** [comment]
3. able to download zip (complete schema) and able to select/check option 1 or 2. (zip is used in migration script)
Nice to have:
4. download metadata track changes
