### ISSUE TITLE
Can not add / insert column of type file in catalogue 3 model

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#1972]
**What version of EMX2 are you using (see footer)**
8.136.20

**Describe the bug**
Can not add / insert  in catalogue 3 model

**To Reproduce**
1. As admin, use template to add catalogue 3 model
2. As admin, use tables app to add new cohort row
3. Fill-out a column with column type File ( has browse btn in ui)
4. Save the new row

**Expected behavior**
Added file is part of new cohort row and can be downloaded

**Comment by mswertz** [comment]
cannot reproduce in [8.189.2](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.189.2)
