### ISSUE TITLE
Unable to add data / Metadata null pointer / Edit modal error

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#2077]
**What version of EMX2 are you using (see footer)**
8.148.3 ( and higher)

**Describe the bug**
When i signin and try to edit ( add/update) a table i get a blank edit modal  

**To Reproduce**
1. Go to  for example 'https://catalogue-acc.molgeniscloud.org/pet%20store/tables/#/Pet'
2. Sign in with edit rights ( for example admin)
4. Try to adit the Pet table
5. See error

note: likely related to https://github.com/molgenis/molgenis-emx2/commit/68d5dfe9d7a3420dced1341d0842d74edef82695
Rowedit line 11 

**Expected behavior**
Expect to see the edit modal , and able to edit the data 

**Screenshots**

<img width="1277" alt="Screenshot 2023-02-16 at 09 30 20" src="https://user-images.githubusercontent.com/47183404/219311131-aa5d15b7-b706-42fe-8ab0-6ba19e2f1497.png">

**Comment by mswertz** [comment]
I could not reproduce at 149.0

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/120060/219313904-31c0382e-31bd-4b52-a0e4-42075d948834.png">

**Comment by BrendaHijmans** [comment]
if data is reuploaded, the error does not occur. But when server is updated error occurs
