### ISSUE TITLE
Search in ssr-catalogue cohorts does not work. Caching issue?

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#2123]
**What version of EMX2 are you using (see footer)**
8.151.1

**Describe the bug**

**To Reproduce**
1. Go to 'https://www.umcgresearchdatacatalogue.nl/UMCG/ssr-catalogue'
2. Click on Cohorts on the homepage.
3. See no cohorts
4. Refresh page > all cohorts found
5. Enter a search term in search box, e.g. ABC
6. Nothing is found: ![image](https://user-images.githubusercontent.com/42644481/222080232-8cf99ae2-379d-45fc-ab6c-1d6d913d776a.png)
7. Remove filters -> nothing is found: 
![image](https://user-images.githubusercontent.com/42644481/222080642-8d01acc5-402a-4590-a96c-1872252725c0.png)
8. Upon refreshing the page, all cohorts are found again when filters are removed.

Browser: Chrome Version 110.0.5481.178

Time 'stamp': 9:59 am, 3/8/2023

**Comment by connoratrug** [comment]
can not reproduce

**Comment by connoratrug** [comment]
this has been fixed by Operations
