### ISSUE TITLE
Harmonisation information inconsistent (View details vs Harmonisation tab)

### ISSUE THREAD

**Issue by EleanorHyde-UMCG** [molgenis/molgenis-emx2#2140]
**What version of EMX2 are you using (see footer)**
Software version: 8.121.1 Database version: 5.

**Describe the bug**
The harmonised/partially harmonised information for variable edu_m_0 in different cohorts is not consistent across the two different ways of viewing this information (1) https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue/EUChildNetwork/variables/edu_m_0?model=LifeCycle_CDM&version=1.0.0 and 2) https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue/EUChildNetwork/variables?tab=harmonization

**To Reproduce**
1. Go to https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue/EUChildNetwork/variables
2. Type "edu_m_0" in the Variables search field on the right hand side
3. Click on the Harmonisation tab
4. See which cohorts have 'partial harmonisation' for this variable.
5. Click on the Details tab
6. Open up the Mother's education level information and click on View details
7. See which cohorts have partial and which have full harmonisation for this variable - and compare with step 4.

**Expected behavior**
The rows of data for edu_m_0 should be identical in both screens.

**Screenshots**
If applicable, add screenshots to help explain your problem. (see screenshots from Line Marie Toft Dyhr at UCPH)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 110.0.5481.178

![Pic 2 (Molgenis_edu_m_0_view details)](https://user-images.githubusercontent.com/80456579/223409220-33a55c3c-ad17-4999-b1ac-f11a6c993ecf.PNG)

![Pic 1 (Molgenis_edu_m_0_harmonization)](https://user-images.githubusercontent.com/80456579/223409205-ad4e8ef0-c622-4f82-b4b8-2e54b1b1eb54.PNG)

**Additional context**

**Comment by marijevdgeest** [comment]
These views show something different: harmonization details show mappings per repeat, while harmonization tab shows a summary of the mappings for all repeats.

So: 
1. at least one partial or one complete = partial
2. at least one partial or one complete and no NA = complete
3. only NA = NA

However, there is a bug for point 2: this one expects one partial _and_ one complete (and no NA), so all repeats completed results in NA
