### ISSUE TITLE
Can not upload molgenis-settings.csv if it contains an empty setting value

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#2199]
**What version of EMX2 are you using (see footer)**
8.151.1

**Describe the bug**
Can not upload molgenis-settings.csv if it contains an empty setting value

**To Reproduce**
1. Create schema
2. Add some settings 
3. Add a setting with an empty value ( or clear an existing value)
4. Download the scheme + data 
5. upload to new schema
6. Upload fails with message "description cannot be null"

**Expected behavior**
Successful upload

**Comment by mswertz** [comment]
verified still exists in [8.189.2](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.189.2)
