### ISSUE TITLE
Cohorts view for networks doesn't show more than 20 cohorts

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#2203]
**What version of EMX2 are you using (see footer)**
8.151.1

**Describe the bug**
Not more than 20 cohorts are show in the overview, even though more cohorts are part of the network (and search is broken)

**To Reproduce**
1. Go to ['https://emx2.test.molgenis.org'](https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue/EUChildNetwork/cohorts)
2. See number of cohorts, compare that to the number of cohorts in https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/cohorts when filtered on 'EU Child Network'
3. You'll see that cohorts are missing ['https://emx2.test.molgenis.org'](https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue/EUChildNetwork/cohorts)

**Expected behavior**
All cohorts part of the network are shown, either on scroll or with paging

**Comment by erikzwart** [comment]
See https://data-catalogue-acc.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue/EHEN/cohorts
I expect to see 32 cohorts but count 20.
![image](https://github.com/molgenis/molgenis-emx2/assets/4077085/09ea7407-718d-429a-8ede-1b7ed97d7c8a)

Version: 8.190.4
