### ISSUE TITLE
Searching on cohort names in the data catalogue needs further improvement

### ISSUE THREAD

**Issue by EleanorHyde-UMCG** [molgenis/molgenis-emx2#2205]
**What version of EMX2 are you using (see footer)**
Software version: [8.151.1](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.151.1). Database version: 8.

**Describe the bug**
A) when I search on the homepage (https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue) for a cohort, all I get to see is the networks which that cohort is linked to, not the cohort itself.
B) If I go to the cohorts page (https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/cohorts) and search for a cohort, I get the list filtered to that cohort, but I can't click on the cohort to go and see it.
In general: it's not currently possible to search for a cohort and see its details without first going through the relevant network/project.

**To Reproduce**
1. Go to https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue
2. Type 'ALSPAC' in the search bar
3. See that the number of network blocks displayed is reduced to those containing ALSPAC, but that no cohort information is displayed.
4. Go to https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/cohorts
5. Type 'ALSPAC' in the search bar
6. See that the list of cohorts is reduced to one, ALSPAC.
7. Click on the ALSPAC row to view the cohort and see that this leads nowhere.

**Expected behavior**
I would expect to see individual cohort data (https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue/EHEN/cohorts/ALSPAC) when I search for and/or click on a specific cohort on the homepage or in a table of cohorts.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version Versie 111.0.5563.112 (Officiële build) (64-bits)

**Comment by mswertz** [comment]
Indeed, in the new catalogue design we envision a global search that will list the seperate resources that match. I.e. you would expect both an ALSPAC cohort and also list of the network they are part of. I would recommend we return a list of resources with counts e.g. 
* Cohorts (1)
* Networks (3)
* Studies (25)
And then user can drill down on the thing they care about

**Comment by EleanorHyde-UMCG** [comment]
No longer a problem in the new user interface
