### ISSUE TITLE
Change to file column made to row via form editor are not stored

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#2209]
**What version of EMX2 are you using (see footer)**
8.169.3

**Describe the bug**
Changes made to row are not persisted

**To Reproduce**
1. login with edit rights
2. create or use petstore db
3. go to tables app en view the Pets table 
4. select a row and click the edit icon
5. Add some data to the photo-url field 
6. go to next chapter to and click save 
7. Modal closes but row is not updated

**Expected behavior**
Row is updated with the new data

**Comment by mswertz** [comment]
Even worse, in [8.189.2](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.189.2) I was not even able to add any file. Might explain some other issue I noticed.

**Comment by chinook25** [comment]
Issue seems to have been resolved (tested on v8.213.25)
