### ISSUE TITLE
Chapters are enabled while chapterIsEnabled = false

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#2219]
**What version of EMX2 are you using (see footer)**
8.172.0

**Describe the bug**

**To Reproduce**
1. Go to umcgresearchdatacatalogue.nl/apps/central/#/
2. open a form in the Cohorts table
3. See that chapters are enabled
4. Go to settings and see that chaptersAreEnabled = false

**Expected behavior**
if chaptersAreEnabled = false, chapters should be disabled

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by connoratrug** [comment]
```chaptersAreEnabled``` is a schema setting not a server/database setting , from the issue report its not clear to what schema is used to test this issue. , i tested using the EQTL_LUNG schema and the setting was respected ( form was shown without chapters )

**Comment by mswertz** [comment]
I suppose it is fixed then
