### ISSUE TITLE
Catalogue 3: network's catalogue is not working

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#2223]
**What version of EMX2 are you using (see footer)**
8.172.0

**Describe the bug**
Network's catalogue is not working for data model 3.3.

**To Reproduce**
1. Go to https://data-catalogue-acc.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue
2. No networks are shown
3. Go to https://data-catalogue-acc.molgeniscloud.org/catalogue/tables/#/Networks
4. See that data is loaded

**Expected behavior**
I expect Networks to show up in the network's catalogue

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
You should use the right version of the catalogue app, i.e. catalogue3

Go to https://data-catalogue-acc.molgeniscloud.org/catalogue/catalogue3/#/networks-catalogue
No networks are shown
Go to https://data-catalogue-acc.molgeniscloud.org/catalogue3/tables/#/Networks
See that data is loaded
