### ISSUE TITLE
Catalogue 3: Variable explorer is not working

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#2224]
**What version of EMX2 are you using (see footer)**
8.172.0

**Describe the bug**
The variable explorer is not working for data model 3.x

**To Reproduce**
1. Go to https://data-catalogue-acc.molgeniscloud.org/catalogue/catalogue/#/variable-explorer, data model is 3.3
2. see that no variables are found
3. Go to https://data-catalogue-acc.molgeniscloud.org/catalogue/tables/#/Variables
4. See that variables are loaded

**Expected behavior**
Variable explorer should be updated to work with 3.x. TagretVariables and SourceVariables were moved to Variables. Can be distinguished by the Resource they are attached to.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
Die you try:

Steps to reproduce the behavior:

Go to https://data-catalogue-acc.molgeniscloud.org/catalogue/catalogue3/#/variable-explorer, data model is 3.3
see that no variables are found
Go to https://data-catalogue-acc.molgeniscloud.org/catalogue3/tables/#/Variables
See that variables are loaded
