### ISSUE TITLE
Catalogue 3 issues

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#2230]
**What version of EMX2 are you using (see footer)**
8.172.0

**Describe the bug**
Multiple issues with the catalogue 3 views, see https://docs.google.com/document/d/1aIBL0RrolsiJHAkFcolGHJ1HX45MiyKCNBwggt3LmLo/edit 

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by connoratrug** [comment]
moved to separate issue
