### ISSUE TITLE
Variable explorer shows names instead of labels

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#2236]
**What version of EMX2 are you using (see footer)**
8.174.2

**Describe the bug**
The variable explorer for data model version 3.x shows 'name' instead of 'label', see image:

![image](https://user-images.githubusercontent.com/42644481/231418524-0ba2fc30-55d0-46ae-88c8-0b627fc26585.png)

**To Reproduce**
Go to https://data-catalogue.molgeniscloud.org/catalogue/catalogue3/#/variable-explorer

**Expected behavior**

**Comment by mswertz** [comment]
propose should have both id and label, we have enough space for that
