### ISSUE TITLE
Variable explorer should only show cohorts that are within the network that uses a variable

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#2245]
**Is your feature request related to a problem? Please describe.**
When browsing mappings in the variable explorer, it is hard to see which cohorts mapped to a variable, since all cohorts are shown for each network. See example for EXPANSE:

![image](https://user-images.githubusercontent.com/42644481/232488481-753ca34f-1943-424c-a078-895def026066.png)

**Describe the solution you'd like**
When looking at the details of a variable, I would only like to see those cohorts that are in a network. See example for EXPANSE with only 6 cohorts (made-up example)
![image](https://user-images.githubusercontent.com/42644481/232488829-db2a178e-5a1d-4e06-b00b-8e2ce9e5a627.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by mswertz** [comment]
will solve this as part of redesign
