### ISSUE TITLE
Selection of network variables does not always work

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#2246]
**What version of EMX2 are you using (see footer)**
8.174.5

**Describe the bug**
Sometimes selection of variables within a network does not work correctly. When refreshing the browser the selection is correct.

**To Reproduce**
1. Go to https://data-catalogue.molgeniscloud.org/
2. At EUChildNetwork, click on variables, you are now viewing eu child variables: Lifecycle and Longitools
3. Click on Molgenis logo in left hand upper corner
4. At EPHOR network, click on variables
5. See error: also LifeCycle variables are also shown

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chinook25** [comment]
Can't reproduce (v8.209.1)
