### ISSUE TITLE
When data is manually uploaded to a schema, the description of that schema disappears.

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#2250]
**What version of EMX2 are you using (see footer)**
8.174.4

**Describe the bug**
When creating a schema, you can give a description of the schema. After uploading data to the schema this description is gone.

**To Reproduce**
1. Go to https://emx2.dev.molgenis.org/apps/central/#/
2. log in as admin
3. change description for pet store schema
4. enter the pet store schema and download pet store datamodel 'export schema as csv'
5. upload this csv
6. go to schema overview and see that description is gone 
7. similar outcome when data is uploaded without a schema

**Comment by mswertz** [comment]
cannot reproduce in [8.189.2](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.189.2)
