### ISSUE TITLE
Cannot download and reupload pet store data

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#2251]
**What version of EMX2 are you using (see footer)**
8.176.0

**Describe the bug**
If I download pet store database, I cannot reupload it into the same schema.

**To Reproduce**
1. Go to https://emx2.dev.molgenis.org/
2. Click on pet store
3. Download all data as csv
4. upload this csv in same schema
5. See error

Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
cannot reproduce in [8.189.2](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.189.2).
