### ISSUE TITLE
Logging in within a schema gives an error

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#2261]
**What version of EMX2 are you using (see footer)**
[8.177.0](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.177.0)
**Describe the bug**
Logging in within a schema gives an error

**To Reproduce**
1. Go to 'https://vac4eu.molgeniscloud.org/vac4eu/catalogue/#/'
2. Login
3. See error:
` internal server error Schema 'catalogue' unknown. Might you need to sign in or ask permission?`

**Expected behavior**
Login and see content. When you login to https://vac4eu.molgeniscloud.org/apps/central/#/ (homepage) and then go to the schema there are no issues

**Comment by connoratrug** [comment]
can not reproduce , when i sign in the page reloads and i am signed in ad can see the catalogue ( tested using chrome browser)

**Comment by marijevdgeest** [comment]
Fix: change name schema to capital
