### ISSUE TITLE
Multicolumn ref input is broken; when clicked the screen scrolls dramatically

### ISSUE THREAD

**Issue by chinook25** [molgenis/molgenis-emx2#2284]
**What version of EMX2 are you using (see footer)**
8.178.9

**Describe the bug**
multi column ref inputs scroll the screen and don't selected the clicked ref when the user click on the label instead of the checkbox.

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'](https://emx2.dev.molgenis.org/apps/molgenis-components/#/component/InputRef
2. In the multi column example click on one of the labels.
3. The screen scrolls up, the example shows the ref to be selected, but the checkbox is not checked.

**Expected behavior**
The clicked ref gets selected and the screen doesn't scroll

**Additional context**
Clicking the checkbox does work as intended.

**Comment by MaxPostema** [comment]
Cant reproduce on mac/firefox, chrome or safari. @chinook25 Is it already fixed or maybe a windows issue?

**Comment by chinook25** [comment]
@MaxPostema bug is no longer happening. Seems to have been accidentally fixed somewhere along the line :)
