### ISSUE TITLE
(Repeated) variables (values) tables are broken

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#2295]
**What version of EMX2 are you using (see footer)**
[8.177.0](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.177.0).

**Describe the bug**
Variables, Repeated Variables and Variable Values tables broken (only in ATHLETE staging area). Changing the name of the _since version_ and _until version_ columns in the 'All Variables' table fixes it.

**To Reproduce**
1. Go to https://data-catalogue.molgeniscloud.org/ATHLETE/tables/#/
2. Click on 'Variables' table

**Screenshots**
<img width="1582" alt="Screenshot 2023-05-11 at 15 21 34" src="https://github.com/molgenis/molgenis-emx2/assets/8653334/080ef733-d42d-458d-bab9-a90c67bce359">

**Test data**
[ATHLETE_bug.zip](https://github.com/molgenis/molgenis-emx2/files/11452663/ATHLETE_bug.zip)

**Comment by erikzwart** [comment]
Not sure of this is connected to this issue but looking at the tables in the 'Up/Download' screen shows some tables twice, like Contacts, Datasets and others. See screenshot:
![image](https://github.com/molgenis/molgenis-emx2/assets/4077085/278c8b6d-880b-43c3-ac8f-0707bc97d492)

**Comment by erikzwart** [comment]
> Not sure of this is connected to this issue but looking at the tables in the 'Up/Download' screen shows some tables twice, like Contacts, Datasets and others. See screenshot: ![image](https://user-images.githubusercontent.com/4077085/237707653-278c8b6d-880b-43c3-ac8f-0707bc97d492.png)

The above turn out not to be related of a 'bug', what happens is that for instance Contacts is shown because this is a tableName and again but this time because tableName Resources has a refTable Contacts.
The distinction between those is not shown in the UI and so you end up with two Contacts.
