### ISSUE TITLE
Don't show empty chapters in row editor.

### ISSUE THREAD

**Issue by MaxPostema** [molgenis/molgenis-emx2#2332]
**What version of EMX2 are you using (see footer)**
8.181.1

**Describe the bug**
Creating a new row in a dataset with headings will create a set of chapters.
If fields inside of the chapters are hidden ( via expression ) empty chapters will be shown in de editor.

<img width="1150" alt="Schermafbeelding 2023-05-23 om 16 07 59" src="https://github.com/molgenis/molgenis-emx2/assets/46395349/7b059e01-5576-4495-8f6e-df0b31bd6cae">

Note, do we want to hide the whole chapter if the heading is hidden?

**Comment by mswertz** [comment]
what causes this empty chapters? I mean, is this a symptom of a data model error? Or are the fields hidden?
That determines if we here should show some warning or as you say hide it.

**Comment by MaxPostema** [comment]
Yes, if all the fields are hidden via visibility expression you will get a empty chapter. I expect that the complete chapter needs te be hidden (from the side menu) if all the containing fields are hidden.

**Comment by chinook25** [comment]
fixed in #2715
