### ISSUE TITLE
When menu has multiple menu-tabs for different tables, navigation gets stuck to first table

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis-emx2#2341]
**What version of EMX2 are you using (see footer)**
8.184.1

**Describe the bug**
When menu is changed, with multiple references to different tables. Navigation gets stuck. So in my example, I added "Subject", "Gene Anomaly". If you click on menu "Subject", you see table "Subject", if you click in menu "Gene Anomaly" you stay in table "Subject". This is probably due to the "#" in link.

**To Reproduce**
1. Go to 'https://ithaca-emx2test.molgeniscloud.org/'
2. Click on 'ILIAD'
3. Go to menu-bar and click on "Gene Anomaly"
4. See view on "Subjects" table stays instead of table "GenomeVariant"

**Expected behavior**
When I click on menu-bar, go to the specified table.

**Screenshots**
![Scherm­afbeelding 2023-05-24 om 16 08 37](https://github.com/molgenis/molgenis-emx2/assets/40240913/5b9ee783-c94c-4b07-b309-65c80699a387) Settings
![Scherm­afbeelding 2023-05-24 om 16 19 20](https://github.com/molgenis/molgenis-emx2/assets/40240913/d1ae6390-3024-4c18-815c-795c5a5b903f) Menu-bar

**Comment by MaxPostema** [comment]
Developer Musings

This issue is based around the '#' in te url. In vue routers the solution would be to use te vue router component in the menu to do the click. ( instead of a <a> tag so that vue can rebuild wat needs to rebuild )

**Comment by mswertz** [comment]
@MaxPostema seems to be one to pick up as part of our bugfix story?
