### ISSUE TITLE
Schema names are case sensitive in the URL

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#2350]
**What version of EMX2 are you using (see footer)**
[8.183.2](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.183.2)
**Describe the bug**
If you add capital letters to an URL schema is not found.

**To Reproduce**
1. Go to https://vac4eu.molgeniscloud.org/conception/
2. login
3. Change url to https://vac4eu.molgeniscloud.org/Conception/
4. Seems like you're logged out again

**Comment by mswertz** [comment]
works as intentended AFAIK

**Comment by marijevdgeest** [comment]
> works as intentended AFAIK

Then we really have to make sure we don't change the schema name when updating versions etc (as happened with VAC4EU)
