### ISSUE TITLE
Can not add row to Pet table from pet store demo project

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#2360]
**What version of EMX2 are you using (see footer)**
8.188.1

**Describe the bug**
Can not add a row

**To Reproduce**
1. Sign in as editor
2. Select pet store
3. Select Pet table
4. Click on the plus icon 
5. Fill in: name, type and weight 
6. click save

**Expected behavior**
A new row is added 
![Screenshot 2023-06-01 at 10 36 48](https://github.com/molgenis/molgenis-emx2/assets/47183404/0eccd068-a7ff-455d-b25a-49077c2f007c)

**Screenshots**

**Comment by MaxPostema** [comment]
Fixed by #2353
