### ISSUE TITLE
Variables edit/input/delete broken

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#2373]
**What version of EMX2 are you using (see footer)**
[8.177.0](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.177.0)

**Describe the bug**
For https://data-catalogue.molgeniscloud.org/:
- Variable edit forms broken
- Can't add new variables, getting this error: `value should match your selection in column 'resource'`
And: `The variables input contains a field name 'name' that is not defined for input object type 'ExtendedResourcesPkeyInput'`
- Can't delete variables (also repeated variables and variable values) with the same error:
`The variables input contains a field name 'name' that is not defined for input object type 'ExtendedResourcesPkeyInput'`

**Comment by MaxPostema** [comment]
I think i might have fixed this in [v8.189.1](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.189.1)

**Comment by marijevdgeest** [comment]
> 

Yes, it works on [v8.189.1](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.189.1) (tested on data-xatalogue-acc @EleanorHyde-UMCG )

**Comment by marijevdgeest** [comment]
Getting the same error again, in [v8.199.1](https://github.com/molgenis/molgenis-emx2/releases/tag/vv8.199.1)
