### ISSUE TITLE
Lists of cohorts seem to be in random order. It would be very useful to have all cohort lists consistently in alphabetical order of the acronyms.

### ISSUE THREAD

**Issue by EleanorHyde-UMCG** [molgenis/molgenis-emx2#2417]
**What version of EMX2 are you using (see footer)**
Software version: [8.190.4](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.190.4). Database version: 8.

**Describe the bug**
Lists of cohorts seem to be given in random order. They should be displayed in alphabetical order of acronym whenever listed. For example on the cohorts-belonging-to-a-project page, but also in other places such as when filtering on cohorts in the Variable Explorer (whether project-specific variable explorer or 'main' variable explorer).
**To Reproduce**
1. Go to https://data-catalogue-acc.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue/ATHLETE
2. Click on View cohorts
3. See that the cohort cards are listed in (seemingly) random order.
![image](https://github.com/molgenis/molgenis-emx2/assets/80456579/d84dd9f2-a1ba-4447-915a-c99403d539ed)

Alternatively, go to the Variable Explorer:
1. Go to https://data-catalogue-acc.molgeniscloud.org/catalogue/catalogue/#/variable-explorer
2. scroll down to find the list of cohorts to filter on
3. See that the list is in (seemingly) random order

![image](https://github.com/molgenis/molgenis-emx2/assets/80456579/2c037e71-bb77-4b13-93fb-e45ba3609094)

**Expected behavior**
I would expect to be able to scroll through a list of cohorts / cohort cards in alphabetical order in order to be able to find what I'm looking for.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Versie 114.0.5735.134 (Officiële build) (64-bits)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by EleanorHyde-UMCG** [comment]
see comment above

**Comment by mswertz** [comment]
I think this applies to the ref input of the cohorts where we would like to add a sort clause

**Comment by EleanorHyde-UMCG** [comment]
In acc:
- list of cohorts in the cohort overview page for Athlete: CORRECT
- list of cohorts on the left hand side in the overview of Athlete variables (https://data-catalogue-acc.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue/ATHLETE/variables): CORRECT
- list of cohorts when you click on 'view as table' under the list in the overview of Athlete variables: STILL IN RANDOM ORDER

**Comment by EleanorHyde-UMCG** [comment]
Tested 05.09.23 in acc, still athe same situation as in July:

- list of cohorts in the cohort overview page for Athlete: CORRECT
- list of cohorts on the left hand side in the overview of Athlete variables (https://data-catalogue-acc.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue/ATHLETE/variables)  CORRECT
- list of cohorts when you click on 'view as table' under the list in the overview of Athlete variables: STILL IN RANDOM ORDER

**Comment by EleanorHyde-UMCG** [comment]
Closing this issue as it seems to have been fixed, both in the 'old' catalogue as in SSR
