### ISSUE TITLE
Filters is broken

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#243]
**What version of EMX2 are you using (see footer)**
5.44.0

**Describe the bug**
The filters options does not show the selected filters.

**To Reproduce**
1. Go to 'https://emx2-conception.test.molgenis.org/ARS/tables/#/SourceVariables' (need to be logged in)
2. Click on 'filters'
3. Choose a few.
3. Filters are not applied.

**Expected behavior**
The table is refreshed an shows only the chosen columns.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win 10
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BrendaHijmans** [comment]
this may be the same issue as 'Clik on checkbox ....' posted by Connor. 
However: selections under columns do work. Filters seems redundant for tables

**Comment by mswertz** [comment]
Cannot reproduce on emx2.dev.molgenis.org. Can you verify again if it still exists?
