### ISSUE TITLE
Variable explorer shows 'mapped GenR, MoBa' but should also include cohorts that map to Repeated variables

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#2439]
**What version of EMX2 are you using (see footer)**
8.190.4

**Describe the bug**
In the Variable explorer search for this example for 'AdhdR_0', open the card and you see mapped by: 'GenR, Moba'. So those two cohorts map to the variable 'AdhdR_0'. However there are many more Cohorts that map to the 'Repeated variable' 'AdhdR_1 through AdhdR_17'
In the variable explorer detail of the variable 'AdhdR_0' **the green check icon is missing** for cohort GenR (adhdR_0). 
Related and would be nice to have see #2245 

**To Reproduce**
1. Go to 'https://data-catalogue-acc.molgeniscloud.org/catalogue/catalogue/#/variable-explorer'
2. Search for: 'adhdr_0'
4. Open AdhdR_0
5. See mapped by

**Expected behavior**
In the detail overview of AdhdR_0 I would like to see instead of 'mapped by GenR, Moba':
Variable mapped by GenR, Moba
Repeated variable maped by GenR, CHOP, INMA, ELFE (etc.. sorted a-z)

**Screenshots**
Variable explorer
![image](https://github.com/molgenis/molgenis-emx2/assets/4077085/0cb07bb6-46ef-4c19-bc67-94f914f6ae8f)
Variable explorer details (GenR missing green check 'adhdR_0'
![image](https://github.com/molgenis/molgenis-emx2/assets/4077085/ff19de66-8c74-41f8-b6de-16833a3ab9cc)

**Additional context**
To see which variables are mapped to which cohorts you can use Variables view: https://data-catalogue-acc.molgeniscloud.org/catalogue/tables/#/Variables
Search for adhdr_0, check the 'name' and see which cohorts are mapped (column mappings)
![image](https://github.com/molgenis/molgenis-emx2/assets/4077085/6cc64e00-0ae4-44ce-8d50-511111c0bb7f)

The same for the repeated variables view: https://data-catalogue-acc.molgeniscloud.org/catalogue/tables/#/RepeatedVariables
Search for adhdr_ check the 'name' (adhdR_1 to adhdR_17) and see which cohorts are mapped (column mappings)
![image](https://github.com/molgenis/molgenis-emx2/assets/4077085/cb002b06-055c-48eb-841e-c1d034be298b)

**Comment by marijevdgeest** [comment]
Similar issue as #1894
