### ISSUE TITLE
Minor adjustments/bugs cohort cards 

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#2458]
**Is your feature request related to a problem? Please describe.**
After testing v[8.195.2](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.195.2) we found a few things that still need to be adjusted on the [cohort cards page](https://data-catalogue-acc.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue/ATHLETE/cohorts):

goto:

https://data-catalogue-acc.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue/EHEN/cohortsall institutions are N/A ( check wioth DB), 

- Institutions always show N/A
- Sometimes fields show N/A, sometimes not (if ontology), preferably leave empty, as N/A can be confusing (can also mean Not Applicable)

**Comment by connoratrug** [comment]
slipt into https://github.com/molgenis/molgenis-emx2/issues/2469 and

**Comment by connoratrug** [comment]
closed , split into https://github.com/molgenis/molgenis-emx2/issues/2469 and https://github.com/molgenis/molgenis-emx2/issues/2473
