### ISSUE TITLE
Aggregate view gives an error on ref/ontology columns with names containing capitals.

### ISSUE THREAD

**Issue by dtroelofsprins** [molgenis/molgenis-emx2#2488]
**What version of EMX2 are you using (see footer)**
v8.200.0

**Describe the bug**
The aggregate view gives an error on ref/ontology columns with names containing capitals.

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org'
2. Create a new database using the Pet Store Template
3. Open the Pet table, and select the aggregate view
4. You will get a nice aggregated view with Column "category" and row "tags". 
5. Open the schema editor and change the name of the "category" column into "Category" and save it.
6. Go to the Pet table again, select the aggregate view and you will get an error

**Expected behavior**
The aggregate view should work with all column name not only the lower-case ones.

**Screenshots**
![image](https://github.com/molgenis/molgenis-emx2/assets/57137088/44c74faa-5185-4013-a30c-56344a1857da)

**Desktop (please complete the following information):**
 - iOS

**Comment by chinook25** [comment]
Aggregate tables now works with correctly with capitals and spaces as per https://github.com/molgenis/molgenis-emx2/pull/2594
