### ISSUE TITLE
anonymous viewer is able to add Dataset Mappings

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#2504]
**What version of EMX2 are you using (see footer)**
8.183.2 (also present in 8.200.1)

**Describe the bug**
A anonymous viewer is able to click the plus icon in the Dataset view and so adding a Dataset Mapping.

**To Reproduce**
1. Go to 'https://conception-acc.molgeniscloud.org/conception/catalogue/#/datasets'
2. Click on 'In-patient PEDW'
3. Click on the plus: This dataset is mapped to the following standards: +
4. See 'insert into table: ..'

**Expected behavior**
Anonymous user should **not** be able to see and click the plus icon.

**Screenshots**
![image](https://github.com/molgenis/molgenis-emx2/assets/4077085/7faa4beb-a106-4893-9f35-22681ac4f16f)

![image](https://github.com/molgenis/molgenis-emx2/assets/4077085/b7867198-8572-42e5-a952-030f0eff1590)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser Brave
 - Version 1.52.129

**Comment by chinook25** [comment]
Current version does not have the + visible (v8.209.1)
