### ISSUE TITLE
anonymous viewer is able to edit Dataset mapping

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#2507]
**What version of EMX2 are you using (see footer)**
8.183.2 (also in 8.200.1)

**Describe the bug**
A anonymous user is able to click on the pencil icon to edit the description of a dataset mapping

**To Reproduce**
1. Go to 'https://conception-acc.molgeniscloud.org/conception/catalogue/#/dataset-mappings/ARS_SDO/SDO/ConcePTION_CDM/VISIT_OCCURRENCE'
2. Click on Description 'pencil icon'
3. See 'update into ..'

**Expected behavior**
A anonymous user should **not** be able to see and click the pencil icon

**Screenshots**
![image](https://github.com/molgenis/molgenis-emx2/assets/4077085/0113252a-eb4f-44bf-861e-2857c798b69c)

**Comment by chinook25** [comment]
Is no longer possible at the current version (v8.209.1)
