### ISSUE TITLE
(Tables) Unable to edit row that has a compound key thats contains a ref type column

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#2554]
**What version of EMX2 are you using (see footer)**
8.199.1 and 8.207.1

**Describe the bug**
As an Admin I am unable to edit (by pressing the pencil icon) the dataset after I created the Dataset. If i try I see a window  update into table: Datasets (Datasets) without any fields.

**To Reproduce**

1. Go to 'https://data-catalogue.molgeniscloud.org/FORCE-NEN/tables/#/Datasets' log is as Admin
2. Click on 'pencil icon' of any of the Datasets
3. See error

**Expected behavior**
Able to edit the fields

**Screenshots**
![image](https://github.com/molgenis/molgenis-emx2/assets/4077085/623cbb6f-8e70-4c27-9104-2eeb383354ef)

**Comment by connoratrug** [comment]
the edit modal takes the row key as input for the edit modal component ( it fetches the data bases on the key passed ) if the key includes a ref type , the entire ref object is put into the key ( instead of only the ref object key). 

```
export function getPrimaryKey(
  row: IRow,
  tableMetadata: ITableMetaData
): Record<string, any> | null {
  //we only have pkey when the record has been saved
  if (!row["mg_insertedOn"] || !tableMetadata?.columns) {
    return null;
  } else {
    return tableMetadata.columns.reduce(
      (accum: Record<string, any>, column: IColumn) => {
        const cellValue = row[column.id];
        if (column.key === 1 && cellValue) {
          accum[column.id] = cellValue; // !! there: if cellValue is a ref object the entire object gets added to the key
        }
        return accum;
      },
      {}
    );
  }
}
```
