### ISSUE TITLE
Unable to include jpgs or other non-text files in my app.

### ISSUE THREAD

**Issue by jelmerveen** [molgenis/molgenis-emx2#2555]
**Is your feature request related to a problem? Please describe.**
I cannot access files other than text based files.

**Describe the solution you'd like**
I want ```private static String redirectAssets(Request request, Response response)``` to be rewritten so it also can serve images. At least jpg.

**Describe alternatives you've considered**
now I am accessing the images from elsewhere.

**Comment by mswertz** [comment]
close in [#image files](https://github.com/molgenis/molgenis-emx2/commit/4164dadea05c18856cfe2d4cd68d7d231ee91541)
