### ISSUE TITLE
Cannot scroll down when searching inside a ref/ref_array table when filling out forms

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#2571]
**What version of EMX2 are you using (see footer)**
8.209.1

**Describe the bug**
In forms, when opening a table inside a form (a refback) and searching within ref/ref_array from there, you cannot find anything in a long list, because you cannot scroll down anymore. 

**To Reproduce**
1. Go to https://emx2.dev.molgenis.org/
2. sign in as admin
3. Click on catalogue-demo 
4. go to up/download
5. import testdata: [testdata.xlsx](https://github.com/molgenis/molgenis-emx2/files/12192098/testdata.xlsx)
6. Click on Catalogue in the ribbon
7. Click on Data sources
8. Edit an existing data source by clicking on the pencil, a form will open
9. Move to section 'linkage' and click on + at 'linked resources'
10. Try to fill out 'main resource' by clicking on the fill out box
11. Try to scroll down searching for datasource10.
12. You cannot scroll down.

**Expected behavior**
I want to be able to scroll through the options

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
@BrendaHijmans can you test again? I cannot reproduce on 8.213.8

<img width="1638" alt="image" src="https://github.com/molgenis/molgenis-emx2/assets/120060/5eb5f3e7-03e5-4fa2-a25f-f0ae417f72b7">

**Comment by BrendaHijmans** [comment]
Issue is still present in 8.213.9. Cannot scroll through list of Data sources or Databanks in this window. No scroll bar is present (see yellow highlight). 

![image](https://github.com/molgenis/molgenis-emx2/assets/42644481/8d8b8ff2-71f9-47a8-b949-3036ebece087)
