### ISSUE TITLE
Inconsistent filter behaviour of the diagnosis filter in the Directory App

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis-emx2#2631]
**What version of EMX2 are you using (see footer)**
v8.213.0

**Describe the bug**
The diagnosis filter is not dismissed when you click outside of the filter, this is inconsistent with other filters and makes is unclear for the user how to dismiss this filter. All other filters are dismissed when you click outside of the filter.

**To Reproduce**
1. Go to 'https://bbmri-emx2-test.molgeniscloud.org/BBMRI-ERIC%20Directory/directory/#/catalogue'
2. Click on 'Diagnosis available'
3. Select any diagnosis
4. Click outside of the filter

**Expected behavior**
The filter is dismissed once you click outside the filter.

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.5
 - Browser: Safari 16.6

**Additional context**
The Diagnosis available filter is a custom component to display the hierarchy.

**Comment by mswertz** [comment]
I believe closed with #2640
