### ISSUE TITLE
Cannot download the RDF/JsonLD representation of the catalogue

### ISSUE THREAD

**Issue by mswertz** [molgenis/molgenis-emx2#2668]
**What version of EMX2 are you using (see footer)**
8.209.1

**Describe the bug**
When I go to https://data-catalogue-acc.molgeniscloud.org/catalogue/api/rdf I get exception
"message": "RDF export failed due to an exception: Cannot invoke \"org.molgenis.emx2.Column.getColumnType()\" because \"column\" is null"

When I go to https://data-catalogue-acc.molgeniscloud.org/catalogue/api/ttl
I get "message": "jsonld export failed: Generation of jsonLd failed: more than one column marked with 'id' or primary key in table Resources"

** Expected **
RDF representation

**Comment by esthervanenckevort** [comment]
Resolved in https://github.com/molgenis/molgenis-emx2/pull/2903
