### ISSUE TITLE
RDF output fails on empty column

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis-emx2#2689]
**What version of EMX2 are you using (see footer)**
8.213.27

**Describe the bug**
When requesting RDF for the data catalogue I get an null pointer exception

**To Reproduce**
1. Go to 'https://data-catalogue-acc.molgeniscloud.org/catalogue/api/rdf/Cohorts'

**Expected behavior**
An RDF representation of the Cohorts table

**Screenshots**
`{
  "errors" : [
    {
      "message" : "RDF export failed due to an exception: Cannot invoke \"org.molgenis.emx2.Column.getColumnType()\" because \"column\" is null"
    }
  ]
}`

**Comment by joerivandervelde** [comment]
The column could not be found because of camel casing interference, partial fix @ https://github.com/molgenis/molgenis-emx2/pull/2698

**Comment by esthervanenckevort** [comment]
Resolved in https://github.com/molgenis/molgenis-emx2/pull/2903
