### ISSUE TITLE
Changing an uploaded file field gives wrong name

### ISSUE THREAD

**Issue by chinook25** [molgenis/molgenis-emx2#2691]
**What version of EMX2 are you using (see footer)**
v8.210.0

**Describe the bug**
After editing a row, changing a file field, then name of the uploaded file is not correctly changed in the row.

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org'
2. Got to the pet store
3. Go to the User table
4. Log in as admin
5. Make a new row with an uploaded image
6. Save the row
7. See that the file name has become picture.(extension of the uploaded file) 

**Expected behavior**
File name is changed correctly

**Comment by chinook25** [comment]
This might be the cause of #1623

**Comment by mswertz** [comment]
We think this is a caching issue: is the column name properly updated in your user interface? E.g. if you rename column from 'picture' to 'picture2' then column name in user interface should be 'picture2' and all the file downloads should be 'picture2.extension' with the extension matching the extension of file you uploaded e.g. 'picture2.png'. 

N.B. some users have feature request to be able to name this file themeselves but that is not a bug.

**Comment by mswertz** [comment]
Reading your description this works as intended. When you upload a file, then the file should have same name as the column name.

**Comment by chinook25** [comment]
@mswertz I expected that the original name of the uploaded file should be kept, so I misunderstood what was intended. Closing the issue.
