### ISSUE TITLE
Most expressions give errors and do not work

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis-emx2#2697]
**What version of EMX2 are you using (see footer)**
v8.210.0-SNAPSHOT and also in v8.213.0

**Describe the bug**
When expression field is filled, most expression give error, where they worked before. Only auto-id seems to work.

**To Reproduce**
visible expression:
1. Go to https://emx2.dev.molgenis.org/Cranio/schema/#/, choose "variant"
2. edit "genetype" and go to visible expression
3. fill in example: gene?.id==='BRCA1'
4. In preview, if you choose "BRCA1" in field "genetype", you get error
<img width="369" alt="Scherm­afbeelding 2023-08-29 om 13 51 15" src="https://github.com/molgenis/molgenis-emx2/assets/40240913/3ffc6b68-872f-4ee0-bf9d-4283b7b21266">

validation expression:
1. Go to https://emx2.dev.molgenis.org/Cranio/schema/#/, choose "variant"
2. edit "name" and go to validation expression
3. fill in example: /^[cg]\\.\\d+/.test(name)
4. in preview nothing happens, no validation
5. Apply and save settings
6. Go to variant and create new variant
7. type in field name "c.4375C>T", gives error, and it could pass validation test

<img width="1124" alt="Scherm­afbeelding 2023-08-29 om 13 57 20" src="https://github.com/molgenis/molgenis-emx2/assets/40240913/e140d020-2d5b-4580-9f31-e55d8d550a2f">

computed expression:
1. Go to https://emx2.dev.molgenis.org/Cranio/schema/#/, choose "variant"
2. edit "id" and go to validation expression
3. make sure it is columnType string
4. In computed fill in one field, in my example "name"
5. In preview you see error, when even when name field is filled
<img width="1124" alt="Scherm­afbeelding 2023-08-29 om 14 06 17" src="https://github.com/molgenis/molgenis-emx2/assets/40240913/df1c4a47-5965-4f69-99de-6955d12b6126">

**Expected behavior**
I expected that expression would work without giving errors

**Comment by clemens-tolboom** [comment]
**Cancelling** on genetype or name then retry **Preview** does not reappear. And my gene selections are not cancelled either.

![image](https://github.com/molgenis/molgenis-emx2/assets/371014/8df92164-31b4-46e2-b5a8-92fa5c91021b)

**Comment by chinook25** [comment]
fixed in #2701
