### ISSUE TITLE
The system allows creation of different tables that only differ in case and this breaks the system in various places

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis-emx2#2723]
**What version of EMX2 are you using (see footer)**
v8.213.30-SNAPSHOT

**Describe the bug**
The system allows the creation of different tables that have the same name except for the case. e.g. Pet vs pet. This breaks in several places where the system will mix the metadata for the different tables.

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org'
2. Select the Pet store schema.
3. Click on Schema
4. Create a new table 'pet' and save
5. Go to Tables
6. Click on the table 'pet'
7. You will get an error Validation error (FieldUndefined@[Pet/name]) : Field 'name' in type 'Pet' is undefined

**Expected behavior**
Metadata of the table is retrieved in a manner that does not mix between the two tables.

**Additional context**
Converting names between different naming conventions is really hard to get right. It is probably better to always use an unmangled identifier in APIs and use (mangled) names only for display. Ideally the name is then stored also in the database metadata schema (for instance as a table comment) but otherwise could be derived from the identifier by a transformation that inserts spaces between when switching from lower to upper case (e.g. firstName -> First Name, CollectionEvents -> Collection Events).

**Comment by mswertz** [comment]
We solve this in the validation rules that applied during creation of tables and columns (i.e. check lowercase uniqueness).
BTW for a emx2 9.x we could consider to also use these lowerCase(column.identifier) as table/column names to make sql building easier in terms of not having to use quotes, but more difficult in that you must understand how naming conventions work.
