### ISSUE TITLE
Cohorts.design schematic not visible in frontend

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#2727]
**What version of EMX2 are you using (see footer)**
8.211.0

**Describe the bug**
In the umcgresearchdatacatalogue the design schematic (Cohorts.design schematic, columnType file) is not visible on the cohort page. 

**To Reproduce**
1. Go to https://umcgresearchdatacatalogue.nl/UMCG/ssr-catalogue/cohorts/LIFELINES_NEXT
2. See that no design schematic is shown. 
3. If you download all data in zip, there is a file referenced in the column design schematic in Cohorts table for the entry LIFELINES_NEXT: https://umcgresearchdatacatalogue.nl/UMCG/api/zip.
4. The data is not visible in tables view: https://umcgresearchdatacatalogue.nl/UMCG/tables/#/Cohorts

**Comment by connoratrug** [comment]
The is not value for the column designSchematic listed in the table

**Comment by connoratrug** [comment]
Seams to be a issue with the Graphql API , when using the zip api the document is show / downloaded

**Comment by connoratrug** [comment]
already fixed in v8.214.1 , to check https://catalogue-acc.molgeniscloud.org/UMCG/ssr-catalogue/cohorts/LIFELINES_NEXT
