### ISSUE TITLE
Inside forms refbacks do not select on refback column (related to issue #2710)

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#2734]
**What version of EMX2 are you using (see footer)**
8.214.3

**Describe the bug**
Refbacks inside forms show all available data in the refTable, even if a refback column is given. For instance, in the Databanks form, at the section contents, there is a column 'datasets'. This is a refback to the Datasets table. Inside forms it now shows all the available datasets. It should only show the available datasets of the Databank that is opened in the form.

**To Reproduce**
1. Go to https://emx2.dev.molgenis.org/catalogue-demo/tables/#/Datasets
2. See all datasets per resource ![image](https://github.com/molgenis/molgenis-emx2/assets/42644481/b3e30e89-a405-419b-a5ef-f3fca48d7565)
3. Go to https://emx2.dev.molgenis.org/catalogue-demo/catalogue/#/databanks
4. Edit a databank and go to 'contents' section.
5. See that all datasets are shown at the 'datasets' column. 
![image](https://github.com/molgenis/molgenis-emx2/assets/42644481/c94cfda0-f0e9-4173-a1e9-431253695d7e)

**Expected behavior**
I only want to see the datasets that are 'attached' to the particular resource that I opened the form for.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
@chinook25 the issue shows itself in InputRefBack and seems to be rooted in an unresolved promise in Client.convertRowToPrimaryKey 

When in InputRefBack rendering `{{refTablePrimaryKeyObject}}` then you see 
<img width="124" alt="image" src="https://github.com/molgenis/molgenis-emx2/assets/120060/38586e86-2c85-48d0-946e-d7983248f440">

**Comment by BrendaHijmans** [comment]
fixed by https://github.com/molgenis/molgenis-emx2/pull/2899
