### ISSUE TITLE
Different order of data items in different browsers

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#2736]
**What version of EMX2 are you using (see footer)**
8.213.29

**Describe the bug**
In firefox this page https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/networks/EOSC4Cancer is visualized as: ![image](https://github.com/molgenis/molgenis-emx2/assets/42644481/2565db2a-24a7-4a92-9216-1bb5600f0531)

In chrome the same page is:
![image](https://github.com/molgenis/molgenis-emx2/assets/42644481/025d42da-c759-45cb-9ddb-cf4f422fb207)

Note the order of the data elements. See Cohorts and Data sources first in firefox, last in Chrome

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chinook25** [comment]
@BrendaHijmans What would be the expected order here? Or is just consistency enough?

**Comment by dtroelofsprins** [comment]
Wrong PR attached, it should be 2736 from GCC repo.

**Comment by dtroelofsprins** [comment]
PR #6293 removed.
