### ISSUE TITLE
To add a cohort to a network, you have to BOTH add the network to the cohort AND add the cohort to the network

### ISSUE THREAD

**Issue by EleanorHyde-UMCG** [molgenis/molgenis-emx2#2737]
**What version of EMX2 are you using (see footer)**
[v8.213.29](https://github.com/molgenis/molgenis-emx2/releases/tag/vv8.213.29)

**Describe the bug**
When you want to link a cohort to a network, it's not enough when a local datamanager adds the network to the cohorts tabel. We have to add the cohorts in the networks tabel as well. This doesn't work because we don't always know when a cohort adds there cohort to a network and they will email us with the question why their cohort doesn't show up in the list of cohorts of a certain network.

**To Reproduce**
1. FOR EXAMPLE: If we want DNBC to show up in the list of EUCAN-Connect cohorts (https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue/EUCAN-connect/cohorts)
2. The DNBC data manager will add EUCAN-Connect to the list of networks in the cohorts table in their staging area: https://data-catalogue.molgeniscloud.org/DNBC/tables/#/Cohorts
3. But this is not enough, we have to add the cohort DNBC in the networks table as well: https://data-catalogue.molgeniscloud.org/catalogue/tables/#/Networks

**Expected behavior**
If a cohort selects a certain network in their staging area, the cohort should show up in the overview of cohorts of the network.

**Comment by BrendaHijmans** [comment]
This is an issue in the data model and not in the UI

**Comment by EleanorHyde-UMCG** [comment]
@marijevdgeest has this been fixed yet?

**Comment by marijevdgeest** [comment]
I'm not sure, if it's a datamodel issue maybe in the new model? (@BrendaHijmans?)

**Comment by BrendaHijmans** [comment]
This is fixed in the new model. You now add the cohorts to the network only. Add the data in the staging area of the network and then sync with catalogue.Op 3 dec 2024 om 11:31 heeft marijevdgeest ***@***.***> het volgende geschreven:﻿
@EleanorHyde-UMCG I'm not sure, if it's a datamodel issue maybe in the new model? ***@***.***?)
