### ISSUE TITLE
Deleting custom menu links removes other links except the custom link

### ISSUE THREAD

**Issue by davidruvolo51** [molgenis/molgenis-emx2#2739]
**What version of EMX2 are you using (see footer)**
8.215.0

**Describe the bug**

When I created a menu link (Settings >> Menu) and moved the new link to the end of the list, I'm unable to delete the custom link. If I click the delete button associated with the custom link, it deletes the first link in the list. 

**To Reproduce**
1. Go to 'https://emx2.te.molgenis.org'
2. Create a schema, e.g., test
3. Open the newly created schema
4. Navigate to Settings >> Menu 
5. Click the plus button to add a new menu link and enter dummy text (do not save changes)
6. Move the newly created link to the end of the list
7. Delete the new link and observe the link that is deleted
8. Repeat until all links are removed

**Expected behavior**
It is expected that I can 1) create a new menu link, 2) rearrange the menu links, and 3) delete links.

**Screenshots**

State of the links after a custom link is created and moved to the end of the list

![Screenshot 2023-09-13 at 15 45 15](https://github.com/molgenis/molgenis-emx2/assets/13485722/6cd669ab-0c74-498b-a4da-e0623d69dfb9)

State of the links after clicking delete. (the first item was removed)
![Screenshot 2023-09-13 at 15 45 24](https://github.com/molgenis/molgenis-emx2/assets/13485722/fb2a40db-a0f4-446a-b5e6-62f69898b7e6)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
This is useful for projects that wish to have a custom menu and a specific order.

**Comment by mswertz** [comment]
ah that is a bit unfortunate
