### ISSUE TITLE
Datasets in catalogue do not show variables

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#2757]
**What version of EMX2 are you using (see footer)**
8.218.0

**Describe the bug**
Datasets in catalogue do not show variables inside that dataset anymore.

**To Reproduce**
1. Go to https://vac4eu.molgeniscloud.org/conception/catalogue/#/datasets/SPA/SPA
2. No variables are shown under the 'Variables' section
3. This used to be the case in earlier version, such as 8.213.29, see https://vac4eu-acc.molgeniscloud.org/conception/catalogue/#/datasets/SPA/SPA

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
I cannot reproduce in latest version (v8.221.2). Can you please check @RosaMGini ?

**Comment by BrendaHijmans** [comment]
This has been resolved.
