### ISSUE TITLE
Unable to Update Data Model: Changing 'ontology_array' to 'ontology' Datatype

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis-emx2#2844]
**What version of EMX2 are you using (see footer)**
Software version: [v8.222.0](https://github.com/molgenis/molgenis-emx2/releases/tag/vv8.222.0). Database version: 10.

**Describe the bug**
There is an issue with updating the data model. Specifically, it is currently not possible to change the datatype from "ontology_array" to "ontology." I tried updating via schema-editor and in up/download. Both methods gives error.

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/newPet/schema/#/'
2. Go to table "Pet"
3. Change column "tags" from ontology_array to ontology
4. Save change 
5. See error
(Also possible in upload, same error)

**Workaround**
Make new database, upload new created datamodel.

**Expected behavior**
The system should allow the modification of a field's datatype from "ontology_array" to "ontology" within the data model, as it is a legitimate use case when adapting the data structure to changing requirements.

**Screenshots**
<img width="936" alt="Scherm­afbeelding 2023-10-10 om 16 27 23" src="https://github.com/molgenis/molgenis-emx2/assets/40240913/2d0ad103-52c6-406f-a4c4-7a417e50f1e6">
<img width="607" alt="Scherm­afbeelding 2023-10-10 om 16 27 37" src="https://github.com/molgenis/molgenis-emx2/assets/40240913/cce2e931-85eb-4b42-9d80-e5137a7af198">

**Comment by mswertz** [comment]
Okay, found the source of the bug. However, there is another bug behind this one, which is: what if there are values in the column? Should the change than fail?

**Comment by Fernananas** [comment]
> Okay, found the source of the bug. However, there is another bug behind this one, which is: what if there are values in the column? Should the change than fail?

Normally, there is an error if data is already available in other format. So yes, no changes if data. But please a clear error message, why change is failing.

**Comment by Fernananas** [comment]
i think this one should be closed
