### ISSUE TITLE
Python client does not recognize all schemas (i.e. staging areas) on server 

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#2875]
**What version of EMX2 are you using (see footer)**
v8.224.1

**Describe the bug**
I am trying to retrieve data from schemas on this server: https://brenda3.molgeniscloud.org/apps/central/#/, which contains many schemas: 
![image](https://github.com/molgenis/molgenis-emx2/assets/42644481/ec265aa3-6d56-4fc7-96e0-55598d017c38)
But not all schemas are recognized by the emx2 python client:
![image](https://github.com/molgenis/molgenis-emx2/assets/42644481/0d1a7fc6-adbc-423a-a624-d69d38a6bb81)

**To Reproduce**
1. Follow README of emx2-python-client: https://github.com/molgenis/molgenis-emx2/blob/master/tools/pyclient/README.md
2. Log in on server with staging areas
3. run print(client.status)
4. Staging areas are not recognized as schemas

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by YpeZ** [comment]
Good spot. There's an error there, but not the one you think. The output of the small list of schema's is correct, but it incorrectly shows that you're signed in. 

Compare in your console 
`with Client('https://brenda3.molgeniscloud.org) as client:`
`    client.signin(username, password)`
`    # Status while signed in`
`    print(client.status)`
`# Status after signing out`
`print(client.status)`

I'm creating a fix for the sign-in status

**Comment by YpeZ** [comment]
Fixed by #2876
