### ISSUE TITLE
Large ontologies cannot always be loaded when adding or editing row in table

### ISSUE THREAD

**Issue by YpeZ** [molgenis/molgenis-emx2#2898]
**What version of EMX2 are you using (see footer)**
v8.220.2

**Describe the bug**
Within the insert/update dialog, clicking the edit field for a column that references a large ontology such as _Diseases_ sometimes results in seemingly waiting forever for the list to load. It appears (see screenshot) that a 404 error is raised and that the list could not even be fetched. Sometimes the lists do load, but after a long wait (10+ seconds).
Additionally, closing the edit dialog often results in being signed out from the server.

**To Reproduce**
1. Go to an EMX2 server with Cohorts staging areas
2. Click on a Cohorts staging area
3. Sign in as a user with sufficient permissions to edit data on the schema
4. Click on the table _Subcohorts_
5. Click on the _add entry_ button
6. Click on the field _main medical condition_
7. See error

**Expected behavior**
The ontology list should appear instantaneously after clicking the dropdown menu.

**Screenshots**
<img width="1434" alt="image" src="https://github.com/molgenis/molgenis-emx2/assets/14897333/9a131f34-a0d0-4ada-b88e-3f7316309da5">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 118.0.2

**Additional context**

**Comment by mswertz** [comment]
so I think meanwhile we should only include terms we actually use? to make this list dramatically shorter? we of course have a story in trac to make this way more lazy so users don't first load the whole damn ontology ;-)

**Comment by YpeZ** [comment]
At this moment the query requests from each term also the metadata of their parent and/or children terms. It would seem that requesting only the _name_ and _label_ of the parent/child would suffice for this purpose, but instead it also loads metadata such as _definition_ and _mg_insertedBy_, etc.

Changing the query
```
query Diseases( $filter:DiseasesFilter, $orderby:Diseasesorderby ) {
        Diseases(
          filter:$filter,
          limit:100000, 
          offset:0,
          orderby:$orderby
          )
          {
          	order 
            name 
            label 
            parent { order name label parent { name } codesystem code ontologyTermURI definition mg_draft mg_insertedBy mg_insertedOn mg_updatedBy mg_updatedOn } 
            codesystem code ontologyTermURI definition 
            children { order name label parent { name } codesystem code ontologyTermURI definition mg_draft mg_insertedBy mg_insertedOn mg_updatedBy mg_updatedOn} 
            mg_draft 
            mg_insertedBy 
            mg_insertedOn 
            mg_updatedBy 
            mg_updatedOn
          }
          Diseases_agg( filter:$filter ) {
            count
          }
        }
```
to 
```
query Diseases( $filter:DiseasesFilter, $orderby:Diseasesorderby ) {
        Diseases(
          filter:$filter,
          limit:100000, 
          offset:0,
          orderby:$orderby
          )
          {
          	order 
            name 
            label 
            parent { order name label } 
            children { order name label parent { name } } 
          }
          Diseases_agg( filter:$filter ) {
            count
          }
        }
```

reduces the size of the query response JSON from 27.82MB to 8.94MB without losing any of the necessary information.
