### ISSUE TITLE
Updating a data model via schema editor is broken

### ISSUE THREAD

**Issue by dtroelofsprins** [molgenis/molgenis-emx2#2942]
**What version of EMX2 are you using (see footer)**
v9.4.0

**Describe the bug**
I can't save any data model changes using the schema editor

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org'
2. Click on pet store
3. Go to the schema editor
4. Add an extra column to the Pet table (or make any other change) 
5. Apply and save the schema
6. It keeps spinning for ever 

**Expected behavior**
When I update the data model using the schema editor, I'm able to save it.

**Comment by chinook25** [comment]
fixed in #2978
