### ISSUE TITLE
Front-end brokken while indexing 

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#296]
**What version of EMX2 are you using (see footer)**
6.5.4

**Describe the bug**
When a new data-set / data model is uploaded ( or 'large' data change) the application becomes broken ( session errors) while the data is being indexed ( 5 , 10 , 15 min maybe more )

**To Reproduce**
1. Go to server -> import 
2. Import non trivial data set ( 30 + tables , 3000 records)
3. after import is done , click around in the app 
4. pages are loaded with error messages or not al all and java error is shown

**Expected behavior**
App works , or user is notified that the app is down and asked to check back in n minutes

**Comment by mswertz** [comment]
this is proposed to be fixed by #302

**Comment by mswertz** [comment]
was closed by #302
