### ISSUE TITLE
Subclasses exported as individuals

### ISSUE THREAD

**Issue by AJKellmann** [molgenis/molgenis-emx2#2984]
**Is your feature request related to a problem? Please describe.**
When exporting the Molgenis catalogue as RDF, classes and subclasses from ontologies are often exported as classes and individuals instead of subclasses.
One example is the Area of information Ontology, which is exported as one class with all subclasses as individuals.

To Reproduce
Steps to reproduce the behaviour:

Go to 'https://emx2.dev.molgenis.org/catalogue-demo/api/rdf'
Search for '[http://localhost:8080/CatalogueOntologies/api/rdf/Areas%20of%20information%20cohorts/Alcohol]
In the original Ontology, it was a Class - in the current export, it is an individual.
So instead of rdf:type, we need to use the rdfs:subClassOf relation.

**Describe the solution you'd like**
Ontologies are mainly based on classes and subclasses and may also contain predicates.
Those structures should be preserved.

**Describe alternatives you've considered**
We might export Ontology tables as classes and subclasses. 
Ontologies rarely contain individuals because they define the schema of a structure.

**Comment by esthervanenckevort** [comment]
The exception here is Countries. The rows in this table represent the individual countries and those do not make sense as a class.
