### ISSUE TITLE
Cannot return to overview of schemas

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#299]
**What version of EMX2 are you using (see footer)**
Software version: 6.5.6. Database version: 6.4.2.

**Describe the bug**
On emx2.dev.molgenis.org you cannot return to the schema overview when clicking Molgenis or in any other way.

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/apps/central/#/'
2. Click on any schema, you can now view the tables in this schema
3. Click on Molgenis, you can still view the tables in the schema and are not returned to  'https://emx2.dev.molgenis.org/apps/central/#/'

**Expected behavior**
Return to overview of all available schemas

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
Ah, we have conflicting feature request. We just implemented 'when I click on logo I go to first menu item'. For a central catalogue that makes sense. But for a staging area it doesn't.

**Comment by BrendaHijmans** [comment]
There is no way to return to the overview of databases at the moment, except for deleting part of the url. It is necessary to go back to the overview to be able to view other schemas (ontologies, cdms) in the data-catalogue-staging.
