### ISSUE TITLE
Green check mark next to biobank names in the Directory App not being rendered

### ISSUE THREAD

**Issue by konstantina-gkp** [molgenis/molgenis-emx2#2996]
**What version of EMX2 are you using (see footer)**
    v10.1.0

**Describe the bug**
   In the front page of the Directory App, the biobanks have a green check mark assigned next to their names. The check mark is a small 
   icon that displays a popover upon hover. The popover contains information related to the Quality certificates assigned to each 
   biobank. After recent changes in the Directory App, the check mark is not being rendered anymore.

**To Reproduce**

   1. Create the Directory schema with the demo data
   2. Go to the Directory’s front page
   3. Check the biobank report cards

**Expected behavior**
   A green check mark should be displayed next to the biobank names in the biobank reports. The green check mark should show the 
   Quality certificate label.

**Comment by dtroelofsprins** [comment]
v10.3.2 Green checkmarks are shown, but text is not readable
