### ISSUE TITLE
Ontology tables should be represented with well known properties that allow them to be treated as well defined ontologies

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis-emx2#2997]
**Is your feature request related to a problem? Please describe.**
Ontology tables now create a lot of properties that are semantically the same but do not share their definition. 

**Describe the solution you'd like**
Ontology tables should be represented with the following properties instead of the properties based on the column names:

- name: rdfs:label 
- label: rdfs:label 
- parent: rdfs:subClassOf 
- code : skos:notation
- ontologyTermURI: owl:sameAs (skos:exactMatch is an alternative, but owl:sameAs allows it to be joined in some visualisations (e.g. GraphDB/VOWL)
- definition: rdfs:definedBy

The following columns can be ignored:
- order
- codesystem
- children: rdfs:superClassOf could be used if wanted

**Describe alternatives you've considered**
- This could be done either in code or with the semantics tagging in EMX2. But since ontology tables are created in code it is basically the same.
- Instead we could also derive this from a common parent table, but this would put all the ontologies in the same table, which would make querying more expensive.

**Comment by esthervanenckevort** [comment]
Joeri mentioned that for the users it would be good to have the NCIT terms next to the ones mentioned above. Even though it leads to some duplication of data in the exports I don't have any issue with adding those.

**Comment by joerivandervelde** [comment]
Very nice, some minor remarks:
- Please check if there are useful NCIT synonyms in the current definition, for some people in our domain NCIT is the reference point and not RDFS (see https://github.com/molgenis/molgenis-emx2/blob/afa2efe51978a2784829d8309e0262b80a8dd9ab/backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlColumnExecutor.java#L283)
- Please don't ignore codesystem: in addition to the full URI of a term, it is often very useful to have separate code and codesystem to create different representations of a term. For intance in Beacon you have to do CURIE notation everywhere (codesystem:code) but some filters come in with codesystem_code etc. Also codesystem property is useful to filter ontology lists that come from multiple sources e.g. all diseases from ICD10, but not ORPHA or SNOMED.
