### ISSUE TITLE
Duplicate tables in schemas with references to another schema

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#3022]
**What version of EMX2 are you using (see footer)**
10.4.0

**Describe the bug**
Tables within a schema are duplicated. Seems to only be the case when the datamodel contains references to another schema (refSchema) and to tables that are not ontology tables.
![image](https://github.com/molgenis/molgenis-emx2/assets/42644481/349a38e6-6fee-4284-97e4-7e76478d2de3)

**To Reproduce**
1. Go to https://emx2.dev.molgenis.org/test_staging/tables/#/
2. See that some, but not all, tables are duplicated
3. This is also the case in the up/download section: https://emx2.dev.molgenis.org/test_staging/updownload/
4. Only happens when there are references to non ontology tables in another schema.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by connoratrug** [comment]
minimal gql query to reproduce 

`{
  _schema {
    id
    tables {
      id
      schemaId
    }
  }
}
`
