### ISSUE TITLE
Having ontologies with a label makes you unable to edit data

### ISSUE THREAD

**Issue by MaxPostema** [molgenis/molgenis-emx2#3031]
**What version of EMX2 are you using (see footer)**
Software version: [v10.4.4-SNAPSHOT](https://github.com/molgenis/molgenis-emx2/releases/tag/vv10.4.4-SNAPSHOT). Database version: 13.

**Describe the bug**
Adding labels to a ontologies will break saving of item containing that ontologie

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/pet%20store/tables/#/Tag'
2. add label 'colors' to ontologie with name 'colors'
3. Edit a existing pet with that ontologie applied
4. notice you cant save anymore
5. If you cannot reproduce, try to edit that same record a second time without any changes

**Screenshots**
<img width="1227" alt="Schermafbeelding 2023-11-23 om 11 42 06" src="https://github.com/molgenis/molgenis-emx2/assets/46395349/b186b183-35f7-4643-a16c-6d30b27d2f3e">

**Comment by mswertz** [comment]
I cannot reproduce, however, I found another bug which is that it doesn't show the label properly

I went to emx2.dev and then edited first the 'colors' to have label 'kleuren' and then edited 'pooky'. 
<img width="854" alt="image" src="https://github.com/molgenis/molgenis-emx2/assets/120060/822f2a5d-09f3-4fae-84fe-6928994c9bb3">

However is my result, not an error but also not visiuble
<img width="1400" alt="image" src="https://github.com/molgenis/molgenis-emx2/assets/120060/1030dee1-a299-44f3-b139-36efc125264b">

**Comment by mswertz** [comment]
Okay, I got it back but when changing totally other field, namely the urls field???

<img width="869" alt="image" src="https://github.com/molgenis/molgenis-emx2/assets/120060/aad7ca69-5587-4e8a-97f1-6d84d6310f4b">

**Comment by MaxPostema** [comment]
Yes, the issue only seems to happen on edit with the ontologies 'pre applied'
