### ISSUE TITLE
creating a table without a label makes a unselectable table

### ISSUE THREAD

**Issue by MaxPostema** [molgenis/molgenis-emx2#3036]
**What version of EMX2 are you using (see footer)**
Software version: [v10.4.4-SNAPSHOT](https://github.com/molgenis/molgenis-emx2/releases/tag/vv10.4.4-SNAPSHOT). Database version: 13.

**Describe the bug**
Creating a table without a label makes a unselectable table in the table listing

<img width="950" alt="Schermafbeelding 2023-11-23 om 13 48 42" src="https://github.com/molgenis/molgenis-emx2/assets/46395349/a41b697f-4815-4ee9-b206-b44ed5918c2e">

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'
2. create a new table, give it a name but keep the label empty
3. Go to 'http://localhost:8080/pet%20store/tables/#/'
4. Notice that you cant open the table because there is no name to click on

**Expected behavior**
Fallback to using the name if there is no label

**Comment by mswertz** [comment]
I suspect there is an empty label. I will add a fix that also gives name when label is ""
