### ISSUE TITLE
feat(central): when creating a new schema from a template I should see progress analogous to when uploading a schema via zipfile

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#3059]
**What version of EMX2 are you using (see footer)**
10.5.2

**Describe the bug**
While creating a new schema with catalogue test data, the 'Create database' window does not disappear. The schema with data is made though.

![image](https://github.com/molgenis/molgenis-emx2/assets/42644481/ebffe152-26bd-4daf-bbed-8b6b871bfa89)

**To Reproduce**
1. Go to https://emx2.dev.molgenis.org/apps/central/#/
2. Sign in
3. Click on + to create a new schema
4. Give schema a name, at template choose: DATA_CATAOGUE, load example data = True
5. Window of creating the schema gets stuck

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
I conclude this is a server issue, see 
<img width="458" alt="image" src="https://github.com/molgenis/molgenis-emx2/assets/120060/be1655e1-5ce2-4b1e-8a65-30d67c2a69b7">

Can you check with 'ops'?

**Comment by BrendaHijmans** [comment]
The issue also occurs when making a CohortStaging schema without data (template = DATA_CATALOGUE_COHORT_STAGING). Sometimes the request gets through. Sometimes it does not, because it takes t long to make the schema. It does not occur when making a Network staging schema  (template = DATA_CATALOGUE_NETWORK_STAGING), which is not incorporated in the profiles yet. Maybe the profiles are slow?

**Comment by dtroelofsprins** [comment]
I'm experiencing the same issue after adjusting the BBMRI-ERIC Disease Types table's datamodel:
- changed a one-to-many to many-to-many (within the table itself)
- add more data (not rows, but added data to a column).

Create database window with spinner keeps showing, although the database is created.

**Comment by esthervanenckevort** [comment]
We should change the code to run the import in a job and give regular updates, just like when using the upload functionality.
