### ISSUE TITLE
Changelog failing to display information at listing of databases

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#3070]
**What version of EMX2 are you using (see footer)**
10.5.2

**Describe the bug**
When isChangelogEnabled == True, at the listing of databases (e.g. here: https://data-catalogue.molgeniscloud.org/apps/central/#/) , the column 'last update' should display the date and table of the latest change. This is not the case anymore, see image below.
![image](https://github.com/molgenis/molgenis-emx2/assets/42644481/5e54ca6c-55b6-4c25-961f-52b345c7ee14)

**To Reproduce**
1. Go to https://data-catalogue.molgeniscloud.org/apps/central/#/ and sign in
2. See 'failed to fetch updated' in column 'last update'
3. Go to a database, e.g. ABCD, click on settings
4. Click on changelog and see that changes are logged

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
indeed, query has been 'changed' when the tableName to tableId change happened. Shouldn't have been done here (yet)
