### ISSUE TITLE
About page of ssr-catalogue should display network specific information

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#3072]
**What version of EMX2 are you using (see footer)**
10.5.2

**Describe the bug**
The about page of the ssr-catalogue displays the about for the UMCG research data catalogue. 

**What do you expect?**
The about page should only be shown on the UMCG research data catalogue and be switched off on the data-catalogue. Something like: if theme == UMCG show about

**Comment by connoratrug** [comment]
suggest story to load about page ( or about sections ) from db

**Comment by BrendaHijmans** [comment]
data-catalogue.molgeniscloud.org now had an error on the about page of the ssr catalogue:
https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/about
