### ISSUE TITLE
Directory App: Show details for collection in biobank card does not work

### ISSUE THREAD

**Issue by dtroelofsprins** [molgenis/molgenis-emx2#3083]
**What version of EMX2 are you using (see footer)**
v10.5.1

**Describe the bug**
When opening a biobank card the show/hide details button of the collections doesn't work (does nothing). For example https://bbmri-emx2-test.molgeniscloud.org/Directory/directory/#/biobank/bbmri-eric:ID:PL_JD16N

**To Reproduce**
1. Go to 'https://bbmri-emx2-test.molgeniscloud.org/Directory/directory/#/biobank/bbmri-eric:ID:PL_JD16N'
2. Click on Show Details of one of the collections => It does nothing

**Expected behavior**
Detailled collection information is shown, see for example: https://directory.bbmri-eric.eu/#/biobank/bbmri-eric:ID:PL_JD16N

**Comment by chinook25** [comment]
Note: this bug only effect Safari

**Comment by dtroelofsprins** [comment]
Most of the times I indeed check multiple browsers, but in this case I totally didn't think of it. Will keep it in mind to always check!
