### ISSUE TITLE
Computed expressions with date field will not render correctly in the data explorer

### ISSUE THREAD

**Issue by MaxPostema** [molgenis/molgenis-emx2#3120]
**What version of EMX2 are you using (see footer)**
Software version: [v10.8.2](https://github.com/molgenis/molgenis-emx2/releases/tag/vv10.8.2). Database version: 14.

**Describe the bug**
Computed expressions with date field will display `|[object Object]|[object Object]|` and not the expected `|2023-12-06|2023-12-06|` in the table explorer

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/pet%20store/schema/#/'
2. Add a date field of type date to a table
3. Add a string field with a computed expression`"|"+date+"|"+date.toString()+"|"`
4. Notice that the computed field works in the forms 
5. Notice that in the table explorer the result brakes to `|[object Object]|[object Object]|`

**Expected behavior**
The table explorer can display computed values of type date

**Screenshots**
<img width="492" alt="Schermafbeelding 2023-12-11 om 14 58 42" src="https://github.com/molgenis/molgenis-emx2/assets/46395349/54bdc1c4-ec08-46fc-8696-2d85695e082b">

**Comment by MaxPostema** [comment]
Traced the issue to the backend
If i send a computed string to the backend:
![Schermafbeelding 2023-12-13 om 11 38 01](https://github.com/molgenis/molgenis-emx2/assets/46395349/09617134-f4ce-4e46-9b93-4f12b0c629fc)

It will return it back to the frontend changed:
<img width="492" alt="Schermafbeelding 2023-12-13 om 11 38 13" src="https://github.com/molgenis/molgenis-emx2/assets/46395349/42cda9f3-3e45-4497-ae38-7a111cf03d77">

**Comment by chinook25** [comment]
Did some testing on it and it seems this is not related to date/datetime but to alle refered field in computeds (e.g. you can test it with the name field).

**Comment by chinook25** [comment]
fixed in #3258
