### ISSUE TITLE
SSR catalogue variables view does not filter on network cohorts

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#3186]
**What version of EMX2 are you using (see footer)**
v10.18.1

**Describe the feature request**
When the variable page is viewed in the context of a 'catalogue' ( instead of viewing all variables in the entire catalogue i.e /all)  only the variables and cohorts linked to that 'catalogue' should be shown.

**To Reproduce**
1. Go to 'https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/ATHLETE'
2. Click on 'variables'
3. Click on 'harmonizations'
4. See matrix with all cohorts instead of only the ATHLETE cohorts.

**Expected behavior**
Network specific views only show cohorts part of the selected network.

**Comment by connoratrug** [comment]
The 'catalogue'/network nesting seems somewhat confusing, as an alternative we could have te variables shown as part of a network details page.
