### ISSUE TITLE
Mappings not shown in SSR catalogue

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#3187]
**What version of EMX2 are you using (see footer)**
v10.18.1

**Describe the bug**
Mappings to harmonized variables are not shown in the variables view

**To Reproduce**
1. Go to 'https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/ATHLETE'
2. Click on 'variables'
3. Search for variable '[adhd_wave_1](https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/ATHLETE/variables/adhd_wave_1-ATHLETE_CDM-outcome_ath-ATHLETE_CDM?keys={%22name%22:%22adhd_wave_1%22,%22resource%22:{%22id%22:%22ATHLETE_CDM%22},%22dataset%22:{%22name%22:%22outcome_ath%22,%22resource%22:{%22id%22:%22ATHLETE_CDM%22}}})' 
4. This variable is mapped by INMA, EDEN and NINFEA but no mappings are shown.

**Expected behavior**
Matrix and variable details shows cohorts that have mapped to the selected variable(s)

**Comment by connoratrug** [comment]
todo:

- [ ]  Fetch data for Variable page from AllVariable table ( instead of Variable table )
- [ ] determine what to show on harmonisation page
