### ISSUE TITLE
Show number of variables in SSR catalogue variables view

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#3191]
**Is your feature request related to a problem? Please describe.**
When you navigate to a variables view in the catalogue, I want to see the number of variables available in that view (for example filtert on the network).
For example, navigate to: https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/ATHLETE/variables
This is the view for the ATHLETE network, here I want to see the number of variables available for ATHLETE (1377)

**Describe the solution you'd like**
We would like one of the following solutions:
- Number of variables shown in paging (< 1-20 of 1377 variables >)
- Number in explanation text: 'A complete overview of 1377 available variables'
- Number shown underneath the 'variables' header

**Comment by connoratrug** [comment]
basic function implemented as part of https://github.com/molgenis/molgenis-emx2/issues/3186 , but could realy do with some nice styling to fix better in the page design

**Comment by connoratrug** [comment]
closed by #3478
