### ISSUE TITLE
Possibility to search in SSR catalogue topics tree 

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#3192]
**Is your feature request related to a problem? Please describe.**
The topics tree is very extensive, this makes it nearly impossible to find a topic by just clicking through
(https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/all/variables)

**Describe the solution you'd like**
An option to search through the topic tree by text

**Comment by EleanorHyde-UMCG** [comment]
This has been merged, where can I test it? (prev for 3449 won't work)

**Comment by EleanorHyde-UMCG** [comment]
Looks good. However I wonder whether the filter when chosen in the pop-up is then applied correctly to the variables shown. 
If I search on 'adhd' in the topics and choose the highest level ("Symptoms and signs") I see two variables. If I click on either of the variables or go and look at them in Tables, I can see no link to adhd anywhere. Where does it see 'adhd' in these variables? (Maybe we don't display enough information elsewhere about individual variables, could also be that)
