### ISSUE TITLE
Quality label popup for a collection is clipped

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis-emx2#3220]
**What version of EMX2 are you using (see footer)**
v10.16.0-SNAPSHOT

**Describe the bug**
If a collection has quality labels assigned the collection card shows these with a blue questions mark to show more details in a popup on hover. However the popup is clipped by the bounding box of the collection card.

**To Reproduce**
1. Go to 'hhttps://bbmri-emx2-test.molgeniscloud.org/Directory/directory/#/catalogue?Qualitylabels=eric'
2. Make sure that the filter 'Quality labels' BBMRI-ERIC is selected.
3. Hover over the blue question mark next to a quality label
4. Observe that the popup is clipped by the bounding box of the card.

**Expected behavior**
The popover is not clipped.

**Screenshots**
<img width="1348" alt="Screenshot 2024-01-16 at 08 42 05" src="https://github.com/molgenis/molgenis-emx2/assets/1942445/48f43a3e-e51e-496f-b212-e65f8dcc1a57">

**Comment by chinook25** [comment]
Only happens when I make the window so small everything becomes unusable anyways, so can't reproduce. Might be a Safari issue?

**Comment by esthervanenckevort** [comment]
I can't reproduce it anymore on Safari and I noticed that the style of the popup has changed, so I would consider this resolved.

**Comment by konstantina-gkp** [comment]
The issue is also present on windows. Therefore, I will remove the "Safari" tag.
