### ISSUE TITLE
I can't save quality information for biobanks in the Directory in one go

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis-emx2#3221]
**What version of EMX2 are you using (see footer)**
v10.16.0-SNAPSHOT

**Describe the bug**
When I create a new quality information for a biobank the save button is disabled. I can save it as draft and then reopen the form and save it.

**To Reproduce**
1. Go to 'https://bbmri-emx2-test.molgeniscloud.org/Directory/directory/#/catalogue'
2. Log in as admin
3. Click on tables
4. Click on QualityInfoBiobanks
5. Click on + and fill in the form
6. I can't save the form

The same holds true for the collection level.

**Expected behavior**
- I can save the form.
- We don't need a computed label here

**Screenshots**
<img width="1509" alt="Screenshot 2024-01-16 at 13 20 31" src="https://github.com/molgenis/molgenis-emx2/assets/1942445/bb4a9184-74d6-4923-b63b-25cc4da9b223">

**Additional context**
Probably related to the computed attribute? I can save as draft and reopen and save and the computed value label is marked as required.

**Comment by dtroelofsprins** [comment]
I've checked, whether the Directory App keeps working when removing the "label" (computed field) from the QualityInfoBiobanks and QualityInfoCollections tables and it seems that in the current version these fields are not used anymore. I will therefore remove them from the model.

However the fact is, that there is something broken regarding the computed fields. This is probably related to this story: https://trac.molgeniscloud.org/ticket/10481, as a ref.label is used in the computed field and not ref.name.

**Comment by chinook25** [comment]
Data fix: in the schema editor, remove the computed expression. Set required to false. Readd the computed expression.
 
Bug should still be fixed though :)

**Comment by chinook25** [comment]
Saving is now possible again.
