### ISSUE TITLE
This can also be used as a test case: PELAGIE is not in list Networks.cohorts, so mapping from PELAGIE to adhd_eval should not be visible when searching in LifeCycle variables. It should be visible in the overall 'super' catalogue.

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#3229]
This can also be used as a test case: PELAGIE is not in list Networks.cohorts, so mapping from PELAGIE to adhd_eval should not be visible when searching in LifeCycle variables. It should be visible in the overall 'super' catalogue. 

In the test data, PELAGIE is in the network ATHLETE. The variables for LifeCycle that it maps to, should also be visible there.

_Originally posted by @BrendaHijmans in https://github.com/molgenis/molgenis-emx2/issues/3218#issuecomment-1895681827_

**Comment by connoratrug** [comment]
Need to check 'It should be visible in the overall 'super' catalogue' once view all variables fix has been released

**Comment by EleanorHyde-UMCG** [comment]
@BrendaHijmans would you agree that this hasn't been solved yet?
