### ISSUE TITLE
Directory App: ontology values with ontologyTermUri not always shown as hyperlinks in collection/subcollections cards

### ISSUE THREAD

**Issue by dtroelofsprins** [molgenis/molgenis-emx2#3255]
**What version of EMX2 are you using (see footer)**
v10.25.0

**Describe the bug**
Ontology values with a ontologyTermUri are not always shown as hyperlinks in the collection/sub-collection details pages.

**To Reproduce**
1. Go to 'https://bbmri-emx2-test.molgeniscloud.org/Directory/directory/#/collection/bbmri-eric:ID:CZ_MMCI:collection:Blood_samples'
2.See that medical records and Survey data is orange = hyperlink at collection level.
3. Scroll down to a subcollection => the first one also has data categories survey data and medical records, but these are not shown as hyperlinks.

**Expected behavior**
Ontology values that have ontologyTermUri's should be hyperlinks in the biobank/collection and sub-collection cards.

**Screenshots**
Collection level: Survey data and Medical records have an URI and are shown as hyperlinks
![image](https://github.com/molgenis/molgenis-emx2/assets/57137088/fbe7e088-4627-41cc-a557-ba801d9d1830)

Subcollection, also has Survey data and Medical records, but these are not shown as hyperlinks:
![image](https://github.com/molgenis/molgenis-emx2/assets/57137088/86ca4673-9fab-45d2-a18d-e8423de819dc)

**Comment by chinook25** [comment]
They are not hyperlinks because there is no url in the data. See https://bbmri-emx2-test.molgeniscloud.org/Directory/tables/#/DataCategories

**Comment by dtroelofsprins** [comment]
You are right about that, but the issue here is that, the ones that do have a url, for example Survey data and Medical Records are shown right in the collection, but not in the sub-collection.
