### ISSUE TITLE
Schema description does not show

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#326]
**What version of EMX2 are you using (see footer)**
6.7.1

**Describe the bug**
If you make a new schema and enter a description, the description does not show once the schema is made.

**To Reproduce**
1. Go to an emx2 server
2. Click on + to make a new schema/database
3. Fill out name and description
4. No description is visible

**Expected behavior**
I expect the description to be visible

**Comment by mswertz** [comment]
duplicate with #554
