### ISSUE TITLE
Different menu options for catalogue are not evenly distributed in horizontal plane

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#3283]
**What version of EMX2 are you using (see footer)**
10.28.0

**Describe the bug**
The outline of different menu options or 'resources' on the landing page is not evenly divided in the horizontal plane. Note, that sometimes there are 4 'resources', sometimes 3, sometime 2, all should have an even distribution in the horizontal plane. 
see for instance:
- https://emx2.dev.molgenis.org/catalogue-demo/ssr-catalogue/OOM
- https://emx2.dev.molgenis.org/catalogue-demo/ssr-catalogue/EUChildNetwork

![image](https://github.com/molgenis/molgenis-emx2/assets/42644481/cc837fa3-e580-4aa2-aa59-9c5b223bce17)

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
We fixed this temporarily by making descriptions about same size. However, that is not a permanent fix

**Comment by connoratrug** [comment]
_Expected behavior_  is missing
