### ISSUE TITLE
Development docs missing styleguide setup

### ISSUE THREAD

**Issue by jelmerveen** [molgenis/molgenis-emx2#331]
**What version of EMX2 are you using (see footer)**
documentation

**Describe the bug**
When following the development manual for setup after using yarn in the apps folder
I should also cd into styleguide and do yarn build there, else you get the following error

```
This dependency was not found:

* @mswertz/emx2-styleguide in ../node_modules/cache-loader/dist/cjs.js??ref--0-0!../node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&, ../node_modules/cache-loader/dist/cjs.js??ref--0-0!../node_modules/vue-loader/lib??vue-loader-options!./src/components/ListTables.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save @mswertz/emx2-styleguide
```

**Expected behavior**
Should be in de docs

**Comment by mswertz** [comment]
did you do a 'yarn install' in /apps ?

**Comment by jelmerveen** [comment]
As a matter of fact I did do yarn install in the /apps folder. But this has nothing to do with this error.

If you cleanly checkout emx2 repository, there will be no 'dist' folder inside the styleguide app.
to reproduce this, is by deleting the dist folder from the styleguide in your dev environment and try to start.
You will get the same error as above.

The reason is, is that you use 'workspaces' and have included the styleguide as a package in one or more apps, because of workspaces it will see the same package inside your mono-repo and will link it internally. It then tries to resolve the path and looks for the 'dist' folder inside the styleguide. With a clean install this is not present, because of .gitignore it is not added to the repo. So it will error.

So you actually have to build the styleguide as well by typing 'yarn build' inside the styleguide app. And this step is not documented.

yarn install only fetches external dependancies and does not build anything.

**Comment by mswertz** [comment]
documentation has been added in #341 see https://emx2.dev.molgenis.org/apps/docs/#/dev_apps
