### ISSUE TITLE
Failing unit test on local master branch build

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#332]
**What version of EMX2 are you using (see footer)**
Inferred version: 6.7.5-SNAPSHOT

**Describe the bug**
org.molgenis.emx2.sql.TestGrantRolesToUsers > testRole FAILED
    java.lang.AssertionError: expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.molgenis.emx2.sql.TestGrantRolesToUsers.testRole(TestGrantRolesToUsers.java:145)

**To Reproduce**
```gradle build ```

**Expected behavior**
All test succeed

**Desktop (please complete the following information):**
 - OS: mac os
 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,2
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	2,4 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB

**Comment by mswertz** [comment]
we have been blocking pull requests with bug fixes. So I will first want to merge those requests as I think this will be fixed by them.

Btw: is the template for the bug not too extensive?

**Comment by mswertz** [comment]
should be closed in #302
