### ISSUE TITLE
Feature Request - Improved Handling of Date Fields in XLSX Uploads

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis-emx2#3355]
**Description:**
When uploading XLSX files containing date fields, errors are encountered if the corresponding Excel cell is set as a date. This issue does not occur when using text uploads.

**Issue Details:**

Problem: Errors arise during the XLSX upload process when the Excel cell is configured as a date field.
Expected Behavior: Smooth handling of date fields during XLSX uploads, similar to text uploads.
Impact: Users face difficulties in importing XLSX files with date fields, leading to inconvenience and potential data integrity issues.

**Screenshots**
<img width="595" alt="Scherm­afbeelding 2024-02-05 om 11 35 37" src="https://github.com/molgenis/molgenis-emx2/assets/40240913/5147e328-5cda-4804-8582-530234402720">
***XLSX cell settings***
<img width="1149" alt="Scherm­afbeelding 2024-02-05 om 13 54 56" src="https://github.com/molgenis/molgenis-emx2/assets/40240913/fd108093-dca8-4727-924c-b8019c28397f">
***Error given***
<img width="595" alt="Scherm­afbeelding 2024-02-05 om 11 37 24" src="https://github.com/molgenis/molgenis-emx2/assets/40240913/9eb81374-c333-4c10-abcc-1ed3749f7f69">
***workaround, set cell to text, (before entering date)***

**Additional context**
Added xlsx examples, second example uploads. Other one does not
[pet store_Order_DateTest.xlsx](https://github.com/molgenis/molgenis-emx2/files/14166006/pet.store_Order_DateTest.xlsx)
[pet store_Order_DateTest2.xlsx](https://github.com/molgenis/molgenis-emx2/files/14166008/pet.store_Order_DateTest2.xlsx)

**Comment by mswertz** [comment]
Ok, I researched. Excel may encode dates as decimal values. So we should check if the value we got is a decimal and then apply a very weird conversion (available in Excel parsing frameworks) to get decimal converted to a localdatetime.

**Comment by mswertz** [comment]
> Ok, I researched. Excel may encode dates as decimal values. So we should check if the value we got is a decimal and then apply a very weird conversion (available in Excel parsing frameworks) to get decimal converted to a localdatetime.

It is actually very hard to guess, POI can do it I suppose. However, I am looking to fastexcel to try and reduce memory footprint.
