### ISSUE TITLE
Missing Cohorts.publications ref_array in cohort view, e.g.: https://preview-emx2-pr-3321.dev.molgenis.org/catalogue-demo/ssr-catalogue/ATHLETE/cohorts/BIB, see where demo data has Cohorts.publications filled out: https://preview-emx2-pr-3321.dev.molgenis.org/catalogue-demo/tables/#/Cohorts?_col=id,designPaper,publications

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#3362]
Missing Cohorts.publications ref_array in cohort view, e.g.: https://preview-emx2-pr-3321.dev.molgenis.org/catalogue-demo/ssr-catalogue/ATHLETE/cohorts/BIB, see where demo data has Cohorts.publications filled out: https://preview-emx2-pr-3321.dev.molgenis.org/catalogue-demo/tables/#/Cohorts?_col=id,designPaper,publications

_Originally posted by @BrendaHijmans in https://github.com/molgenis/molgenis-emx2/issues/3321#issuecomment-1931505017_

**Comment by esthervanenckevort** [comment]
Please clean up the title & description of this issue so it is clear for anyone what has to be done.

**Comment by connoratrug** [comment]
oudated
