### ISSUE TITLE
After upgrading the server scheduled jobs stop running

### ISSUE THREAD

**Issue by dtroelofsprins** [molgenis/molgenis-emx2#3372]
**What version of EMX2 are you using (see footer)**
v10.35.2 (but also in previous versions)

**Describe the bug**
After upgrading a server using the AWX "Emx2 backend update playbook" template, scheduled scripts stop running. Only after opening and saving the script again it starts running again. 

**To Reproduce**
1. Go to 'https://bbmri-emx2-test.molgeniscloud.org'
2. Schedule for example the "Hello world" job to run every minute (0 0/1 * * * ?)
3. Check if the job runs (for several times) 
4. Upgrade the server using the AWX "Emx2 backend update playbook" template
5. Wait five minutes => the job doesn't run anymore
6. Open the script and save it (no adjustments needed) => the job starts running again 

**Expected behavior**
After upgrading the server, scheduled jobs keep running.

**Comment by mswertz** [comment]
So it seems the cron task manager is not restarting when server is restarted

**Comment by dtroelofsprins** [comment]
Today discussed during OPS weekly meeting, Ruben is going check on the server side how and what regarding the cron job after a restart.
