### ISSUE TITLE
Directory app: URLs with query parameters do not display the correct filtered results

### ISSUE THREAD

**Issue by konstantina-gkp** [molgenis/molgenis-emx2#3396]
**What version of EMX2 are you using (see footer)**
v10.40.1-SNAPSHOT

**Describe the bug**
When the directory’s URL has any query parameters e.g., “Category” filter set to “Covid”, the URL becomes "https://directory-emx2-acc.molgenis.net/ERIC/directory/#/catalogue?Categories=covid19". If we try to search for this specific URL, the URL redirects us to the general initial page of the directory app instead of redirecting us to the retrieved collections matching the current set filter. This behavior is repeated for any existing filter.   

**To Reproduce**
1. Go to "https://directory-emx2-acc.molgenis.net/ERIC/directory/#/catalogue?Categories=covid19"
2. Check the result

**Expected behavior**
A URL with a set filter displays the collections matching that filter instead of directing the user to the initial directory page. In the case of the category filter set to "Covid", the directory app should return/display 77 results. 

**Screenshots**
Actual results

![url_directory](https://github.com/molgenis/molgenis-emx2/assets/143411718/24ecedb4-66bd-4c41-9ff2-fab27643874e)

**Comment by mswertz** [comment]
I can't reproduce on chrome + mac

**Comment by konstantina-gkp** [comment]
The issue does not appear anymore.
