### ISSUE TITLE
'About statuses' in SSR catalogue seems to be a link, but is irresponsive 

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#3423]
**What version of EMX2 are you using (see footer)**
[v10.37.1](https://github.com/molgenis/molgenis-emx2/releases/tag/vv10.37.1).

**Describe the bug**
'About statuses' seems to be a link, but is irresponsive 

**To Reproduce**
1. Go to 'https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/all/variables?page=1&view=harmonization'
OR
2. Go to any variable details page, for example 'https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/all/variables/adhd_wave_1-ATHLETE_CDM-outcome_ath-ATHLETE_CDM?keys={%22name%22:%22adhd_wave_1%22,%22resource%22:{%22id%22:%22ATHLETE_CDM%22},%22dataset%22:{%22name%22:%22outcome_ath%22,%22resource%22:{%22id%22:%22ATHLETE_CDM%22}}}'
2. Click on 'about statuses' on the topright corner of the matrix and notice nothing is happening

**Expected behavior**
After clicking 'about statuses' a pop up or dialog appears explaining what 'completely harmonized', 'partially harmonized' or 'NA" means.

**Comment by connoratrug** [comment]
how would we explain what  'completely harmonized', 'partially harmonized' or 'NA" means ?

**Comment by marijevdgeest** [comment]
Story: https://trac.molgeniscloud.org/ticket/10882

**Comment by davidruvolo51** [comment]
There are two fixes in this issue: 1) the statuses and definitions and 2) the status calculation. PR #3498 will address this issues. A new PR will be created to address the calculations.
