### ISSUE TITLE
Feat: Show dataset details in side modal on cohort page

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#3424]
**What version of EMX2 are you using (see footer)**
[v10.37.1](https://github.com/molgenis/molgenis-emx2/releases/tag/vv10.37.1).

**Describe the bug**
Clicking on a dataset in SSR catalogue Cohorts view shows a buggy detail page (see screenshot)

**To Reproduce**
1. Go to any cohort page that has datasets, for example 'https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/all/cohorts/GenR'
2. Scroll down to 'datasets' and click on a dataset
4. See a dialog appear without any contents

**Expected behavior**
Clicking on a dataset shows a dialog with dataset details:
- Label
- Source
- Description
- Unit of observation
- Keywords

**Screenshots**
![Screenshot 2024-02-22 at 12 43 06](https://github.com/molgenis/molgenis-emx2/assets/8653334/10fab13c-e7ae-417f-9983-ead04892f20f)

**Comment by connoratrug** [comment]
i check the code, the link to networks is not yet implemented , we need to decide what to show , both in modal and behind btn
