### ISSUE TITLE
Catalogue redirect is shortly interrupted by 'You have to log in to view the data' 

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#346]
**What version of EMX2 are you using (see footer)**
6.7.4

**Describe the bug**
When you click on 'Catalogue' you shortly see 'You have to login to view the data' before the Catalogue appears.

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org' or 'https://data-catalogue.molgeniscloud.org/'
2. Click on 'Catalogue'
3. See error

**Expected behavior**
I expect to go to the Catalogue immediately.

**Comment by connoratrug** [comment]
possibly related to https://github.com/molgenis/molgenis-emx2/issues/345
