### ISSUE TITLE
UMCG Research Data Catalogue: 'Search in cohorts' only works on the first page

### ISSUE THREAD

**Issue by kimmeijercbch** [molgenis/molgenis-emx2#3460]
**What version of EMX2 are you using (see footer)**
v10.36.0

**Describe the bug**
The search function 'Search in cohorts' only works on the first page of the cohort overview. If you go to page 2, and then search for a keyword, you get zero hits. 

**To Reproduce**
1. Go to 'https://umcgresearchdatacatalogue.nl/UMCG/ssr-catalogue/all/cohorts'
2. Type in: "lifelines"
3. Now you get 4 hits
4. Remove the tekst "lifelines"
5. Click on button for next page (at the bottom of the page). You are now on page https://umcgresearchdatacatalogue.nl/UMCG/ssr-catalogue/all/cohorts?page=2
6. Type in: "lifelines"
7. Now you get 0 hits

**Expected behavior**
You expect to get the same 4 hits if you start the search on page 1.

**Comment by kimmeijercbch** [comment]
There are more issues with the searchfunction. See also #3461.

Further issues:
- If you select Filters - Data categories - Imaging data you get two pages with hits. If you got to the second page, you get the same list as on the first page. 
- If you enter 'life' in the Search in cohorts, you get 5 pages with hits. If you then go to the second page, the selection is gone, and you are on the second page of 7 pages.

**Comment by connoratrug** [comment]
can not reproduce in version v10.46.1, needs retest

**Comment by connoratrug** [comment]
can not longer be reproduced, most likely fixed as side effect of other fix , closing
