### ISSUE TITLE
When searching for a variable which has repeated measurements, clearer information should be provided on the 'list of variables' tab

### ISSUE THREAD

**Issue by timcadman** [molgenis/molgenis-emx2#3484]
Decision: show (+ 12) 

**Is your feature request related to a problem? Please describe.**
When searching for a variable which has repeated measurements, in the 'list of variables' tab, only the first variable is returned. This can leave it confusing for a researcher unfamiliar with the catalogue whether data exists at additional ages, or whether this is the only variable that exists. 

**Describe the solution you'd like**
For me it would be more intuitive if only the stem of the variable was displayed (e.g. "adhd_wave_", rather than "adhd_wave_1"), and potentially an additional element to the right stating 'repeated measurements'.

**Describe alternatives you've considered**
Make no changes and leave it for the researcher to discover this when clicking on the variable.

**Additional context**
![Captura de pantalla 2024-03-11 a las 11 35 33 (2)](https://github.com/molgenis/molgenis-emx2/assets/41470917/f13bd834-f61f-4043-9136-4e3f7a83cbab)

**Comment by timcadman** [comment]
Yes something simple just saying "x more repeats available" would be good

**Comment by timcadman** [comment]
Something like this:

![Captura de pantalla 2024-03-13 a las 13 57 16](https://github.com/molgenis/molgenis-emx2/assets/41470917/cb1d76d5-3b32-40de-9071-2010ed1da673)

**Comment by EleanorHyde-UMCG** [comment]
Request from Morris: add a plus on the LHS of repeated variables, which you can then expand to show the repeated variables underneath. This is how it looks in Lifelines:

![image](https://github.com/molgenis/molgenis-emx2/assets/80456579/d9e0d01f-7a39-49a0-951f-dffd29c5067f)

**Comment by marijevdgeest** [comment]
I think this solution has a different purpose in the Lifelines cat, here the repeats show actual additional information, while for the data catalogue it's just a list of names where only the numbers are different from the root variable, so this solution seems  to take up a lot of space that's not necessary. I think showing something simpler is already enough information ("+ x repeats") and much more clean.

**Comment by EleanorHyde-UMCG** [comment]
> I think this solution has a different purpose in the Lifelines cat, here the repeats show actual additional information, while for the data catalogue it's just a list of names where only the numbers are different from the root variable, so this solution seems to take up a lot of space that's not necessary. I think showing something simpler is already enough information ("+ x repeats") and much more clean.

@marijevdgeest could you make a mock-up please of how you see this?

**Comment by marijevdgeest** [comment]
> > I think this solution has a different purpose in the Lifelines cat, here the repeats show actual additional information, while for the data catalogue it's just a list of names where only the numbers are different from the root variable, so this solution seems to take up a lot of space that's not necessary. I think showing something simpler is already enough information ("+ x repeats") and much more clean.
> 
> @marijevdgeest could you make a mock-up please of how you see this?

I'm actually not sure what would be the best option, everything feels quite clunky. I was thinking maybe just a number after the variable name and no number when there are no repeats. Like:
VariablenameA_ (12)
VariablenameB
VariablenameC_ (21)

But not sure if that would be clear enough. @timcadman what do you think?

**Comment by timcadman** [comment]
Perhaps either
(+ 12) or (+ 12 repeats) would be clearer?

**Comment by chinook25** [comment]
Once it's clear what we want, can the original issue be updated with that information?
