### ISSUE TITLE
Diagnosis search hangs when searching for leukemia

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis-emx2#3502]
**What version of EMX2 are you using (see footer)**
Software version: [v10.41.6](https://github.com/molgenis/molgenis-emx2/releases/tag/vv10.41.6). Database version: 17.

**Describe the bug**
When typing leukemia in the diagnosis available facet I get a hanging spinner when I type leukemia.

**To Reproduce**
1. Go to 'https://directory-emx2-acc.molgenis.net/ERIC/directory/#/catalogue'
2. Click on 'Diagnosis available'
3. Type 'leukemia' in the search box
4. When typing the fifth character the search hangs with a spinner

**Expected behavior**
The list of codes is limited to those matching the typed text.

**Screenshots**
<img width="1360" alt="Screenshot 2024-03-13 at 12 05 10" src="https://github.com/molgenis/molgenis-emx2/assets/1942445/52bfba71-b0da-42b2-b4e6-e31031a5690e">

**Comment by chinook25** [comment]
The issue here is that if there are no search results, it keeps showing the spinner.
