### ISSUE TITLE
As catalogue data manager I would like to see the emx2 version number in the nuxt-ssr UI

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#3513]
**Is your feature request related to a problem? Please describe.**
If I want to check the emx2 version number while I am in the ss-catalogue< i have to navigate to the tables view in the 'old' app. 

**Describe the solution you'd like**
I would like to see the emx2 version number in the nuxt-ssr UI at the bottom of the page, below the citations. 
![image](https://github.com/molgenis/molgenis-emx2/assets/42644481/efbd198e-b296-419a-a7d2-cfe386e64de8)

**Describe alternatives you've considered**

**Additional context**

**Comment by connoratrug** [comment]
is visible on the about page 
https://data-catalogue-acc.molgeniscloud.org/catalogue/ssr-catalogue/all/about#version
