### ISSUE TITLE
EMX2 Pyclient get fails in case the table name starts with a lowercase

### ISSUE THREAD

**Issue by dtroelofsprins** [molgenis/molgenis-emx2#3543]
**What version of the EMX2 are you using**
molgenis-emx2-pyclient 10.48.0

**Describe the bug**
 data = client.get(schema='testTableId', table='table1') fails when the name of the table starts with a lowercase letter, because the id of the table is stored Pascalcase 

error:
molgenis_emx2_pyclient.exceptions.PyclientException: Message: Failed to retrieve data from testTableId::'table1'.
Status code: 400.

If instead of entering table1, Table1 as name, the error is:
    raise NoSuchTableException(f"Table {table!r} not found in schema {current_schema!r}.")
molgenis_emx2_pyclient.exceptions.NoSuchTableException: Message: Table 'Table1' not found in schema 'testTableId'.

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org'
2. Create a new schema
3. Upload the attached file
4. Create a script:
`from molgenis_emx2_pyclient import Client

import os

token = os.environ.get('MOLGENIS_TOKEN')

client = Client('https://emx2.dev.molgenis.org', token=token)

data = client.get(schema='testClient', table='table1')`

5. Run the script and see the error, also try to run with table='Table1'

**Expected behavior**
Data should be retrieved also when tableID and tableName are not the same.
[testTableId.csv](https://github.com/molgenis/molgenis-emx2/files/14721825/testTableId.csv)

**Comment by YpeZ** [comment]
Fixed in #3522 

I tested the script on the [dev server](https://emx2.dev.molgenis.org/testTableID/tasks/#/scripts) with lowercase `table1` and verified it works with the latest Pyclient version.
