### ISSUE TITLE
Menu items set to 'editor' cannot be seen by users with editor or manager role

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#355]
**What version of EMX2 are you using (see footer)**
6.10.0. 

**Describe the bug**
Menu items set to 'editor' cannot be seen by users with editor or manager role

**To Reproduce**
1. Go to 'https://data-catalogue-staging.molgeniscloud.org/'
2. Log in as admin
3. Make a test user account with editor right for a schema of choice
4. Log in as this test user
5. You cannot see the up/download menu item
6. repeat with test user set to manager

**Expected behavior**
I expect to see menu items that should be visible for an editor role

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sidohaakma** [comment]
Fixed by https://github.com/molgenis/molgenis-emx2/pull/361
