### ISSUE TITLE
Details side model on networks page has incorrect url to cohort

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#3554]
**What version of EMX2 are you using (see footer)**
v10.48.0

**Describe the bug**
The link 'Detail page' on the detail side model has a incorrect url to the cohort

**To Reproduce**
1. Go to 'https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/Immune-Image/networks/Immune-Image'
2. Click on Cohorts 'Characterisation and validation of immunotracers in an experimental model of chronic inflammation'
3. Detail side model will be presented, click on Detail page (bottom right)
4. See error: empty blue screen

**Expected behavior**
You should see this page: https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/Immune-Image/cohorts/Immune-Image_Task_4.3

The incorrect url:
https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/cohorts/Immune-Image_Task_4.3
The correct url: 
https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/Immune-Image/cohorts/Immune-Image_Task_4.3

So we need to add the network to the url:
https://[server]/[schema]/ssr-catalogue/[**network**]/cohorts/[cohort]

**Screenshots**
![image](https://github.com/molgenis/molgenis-emx2/assets/4077085/0cc96713-ae82-409e-849c-0e31c71671c3)
When you click on Detail page:
![image](https://github.com/molgenis/molgenis-emx2/assets/4077085/3cff43a8-3419-495c-ac76-6d1f9bae89cd)
I should see the following page
![image](https://github.com/molgenis/molgenis-emx2/assets/4077085/7e83ff6d-b043-4111-b890-c043a1d16216)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04.4 LTS
 - Browser Brave

**Comment by EleanorHyde-UMCG** [comment]
Morris: small bugfix, doesn't have to wait for a next round
