### ISSUE TITLE
Limit or get rid of opening of new tabs

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#356]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I cannot find the right tab back in my web browser, because emx2 opens that many tabs.

**Describe the solution you'd like**
Less opening of new tabs

**Describe alternatives you've considered**
The alternative is already present: we can navigate the system via the breadcrumbs and the banner.

**Additional context**

**Comment by mswertz** [comment]
ah good point. Not necessary anymore so we can indeed remove the open in new tab
