### ISSUE TITLE
fix(forms): Decimal Field Accepts Only '.' as Decimal Separator and Does Not Allow Leading Zeroes

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis-emx2#3561]
**What version of EMX2 are you using (see footer)**
Software version: [v10.48.12](https://github.com/molgenis/molgenis-emx2/releases/tag/vv10.48.12)

**Describe the bug**
The decimal field in the application accepts only '.' as the decimal separator, and entering ',' does not work. Additionally, when attempting to add a value with a zero after the decimal point (e.g., 1.09), it is not possible; only when entering 1.9 first and then adding the zero. This behavior is unexpected and causes inconvenience to users.

**To Reproduce**
1. Open the application and navigate to the page with the decimal field.
2. Attempt to enter a value with a decimal comma (e.g., 1,5) in the decimal field.
3. Notice that the comma is not accepted as a decimal separator.
4. Try entering a value with a zero after the decimal point (e.g., 1.09).
5. Observe that it is not possible to enter the value directly; only when entering 1.9 first and then adding the zero.

**Expected behavior**
It is expected that the decimal field should accept both '.' and ',' as decimal separators and allow leading zeroes. Additionally, users should be able to enter values with leading zeroes after the decimal point without any workaround.

**Screenshots**
Correct Decimal handling
<img width="977" alt="correct_decimal_handling" src="https://github.com/molgenis/molgenis-emx2/assets/40240913/cc7e98ad-aee2-4ce2-8e3d-97685aa919c5">
Video showing; zero after decimal point

https://github.com/molgenis/molgenis-emx2/assets/40240913/78bfea29-6bb2-4301-b331-a426f8e32d29

**Comment by esthervanenckevort** [comment]
Is this something that can be done with standard semantic types for input?

**Comment by chinook25** [comment]
relevant article: https://stackoverflow.blog/2022/12/26/why-the-number-input-is-the-worst-input/

**Comment by mswertz** [comment]
Unless somebody has better day: I want to revert back to a normal string input that we validate ourselves? I think we had it originally like that.

**Comment by mswertz** [comment]
decide to use strings
