### ISSUE TITLE
The cohort overview is showing a field in the wrong place

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#3575]
**What version of EMX2 are you using (see footer)**
10.48.5

**Describe the bug**
The field 'Cohorts.design description' is shown right under the heading 'General design'. This is incorrect. There should not be anything displayed here. The field is displayed elsewhere in this section already, at 'design description'. If anything should be displayed here, it should be a description of what data to expect under this heading.

![image](https://github.com/molgenis/molgenis-emx2/assets/42644481/8b5e3f4e-80f3-424d-ad64-bb252a8e2ccd)

**To Reproduce**
1. Go to https://umcgresearchdatacatalogue.nl/UMCG/ssr-catalogue/all/cohorts/ARIADNE, see the text below the heading 'General design'
2. Go to https://umcgresearchdatacatalogue.nl/UMCG/ssr-catalogue/all/cohorts/LIFELINES_NEXT, see the text below the heading 'General design'

**Expected behavior**
There should be either no text displayed here or a description on what kind of metadata to expect under this section. Do not display data from a filled out field!

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by connoratrug** [comment]
duplicate https://github.com/molgenis/molgenis-emx2/issues/3534
