### ISSUE TITLE
Catalogue not accessible anymore on data-catalogue (multiple errors!)

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#358]
**What version of EMX2 are you using (see footer)**
6.7.4 (very old)

**Describe the bug**
After error described here #357  occurred and reloading the previous page in my web browser, the Catalogue option in the menu disappeared.

**To Reproduce**
1. Go to 'https://data-catalogue.molgeniscloud.org/'
2. Click on 'Catalogue', click on cohorts, view a cohort
3. wait a while (5 min may be enough)
4. return to web browser
5. Click on Catalogue, error described under #357 occurs
6. if you click on Molgenis logo, a 404 error is given 
![image](https://user-images.githubusercontent.com/42644481/125838117-632c9367-8b50-4a2e-b96a-1f01a4fcf9fd.png)

7. Return to previous page
8. Catalogue is not accessible anymore via the ribbon
![image](https://user-images.githubusercontent.com/42644481/125837846-0aeb46ef-7233-4d5b-a5ca-f3484a70ae37.png)

**Expected behavior**
I expect navigation through the database to work properly and not give errors after reloading pages.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
Why don't you update to latest version?

**Comment by mswertz** [comment]
Can you try to reproduce?
