### ISSUE TITLE
Catalogue List page layout gets shifted on macbook screen

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#3592]
**What version of EMX2 are you using (see footer)**
[v10.49.7](https://github.com/molgenis/molgenis-emx2/releases/tag/vv10.48.8).

**Describe the bug**
This screen is incorrect on macbook 13" screen (see screenshot below): https://data-catalogue-acc.molgeniscloud.org/testCatalogue/ssr-catalogue/testNetwork1/variables?page=1&view=list

Zooming out fixes the issue, could not reproduce on windows laptop or external monitor. Both Chrome and Safari show the same issue.

<img width="1423" alt="Screenshot 2024-04-03 at 16 12 56" src="https://github.com/molgenis/molgenis-emx2/assets/8653334/2f072f47-cea2-448f-9ce3-e28a2af4a173">

**Comment by erikzwart** [comment]
Version **v10.49.7** not v10.48.8, correct @marijevdgeest ?

**Comment by marijevdgeest** [comment]
Ah yes, thanks @erikzwart!
