### ISSUE TITLE
Variable repeats in harmonization details per cohort are not sorted

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#3605]
**What version of EMX2 are you using (see footer)**
v10.49.7

**Describe the bug**
The repeated variables in the harmonization details per cohort are not ‘naturally’ sorted.

**To Reproduce**
1. Go to https://data-catalogue-acc.molgeniscloud.org/testCatalogue/ssr-catalogue/all/variables/testVarRepeats_-testNetwork1_CDM-cdm_1-testNetwork1_CDM?keys={%22name%22:%22testVarRepeats_%22,%22resource%22:{%22id%22:%22testNetwork1_CDM%22},%22dataset%22:{%22name%22:%22cdm_1%22,%22resource%22:{%22id%22:%22testNetwork1_CDM%22}}}
5. Scroll down to: Harmonization details per cohort
6. See the error

**Expected behavior**
I **expect** that the list of repeated variables is as follows:
1. Name: testVarRepeats_
2. Name: testVarRepeats_1
3. Name: testVarRepeats_2
4. Name: testVarRepeats_3
5. Name: testVarRepeats_4
6. Name: testVarRepeats_5
7. Name: testVarRepeats_6
8. Name: testVarRepeats_7
9. Name: testVarRepeats_8
10. Name: testVarRepeats_9
11. Name: testVarRepeats_10

Instead I see the following (**incorrect**) order:
1. Name: testVarRepeats_
**2. Name: testVarRepeats_6**
3. Name: testVarRepeats_1
4. Name: testVarRepeats_2
5. Name: testVarRepeats_3
6. Name: testVarRepeats_4
7. Name: testVarRepeats_5
8. Name: testVarRepeats_7
9. Name: testVarRepeats_8
10. Name: testVarRepeats_9
11. Name: testVarRepeats_10

**Screenshots**
![harmo-detail-acc_10 49 7](https://github.com/molgenis/molgenis-emx2/assets/4077085/3cc6e1f3-aec7-4ab2-8052-d35371aaf306)

**Comment by connoratrug** [comment]
The repeated variables table is missing an order column , without it the is no reliable way to sort on name ( i.e. there is not natural order)   ; 1foo, 10-foo, 0032-foo-3 , ... possibility's are endless. The model could be updated with a order column to define the repeat order

**Comment by connoratrug** [comment]
https://github.com/molgenis/molgenis-emx2/tree/demo/sort-repeat-on-name

**Comment by EleanorHyde-UMCG** [comment]
Which preview number can I use to review this, @connoratrug?
