### ISSUE TITLE
fix: when setting isOidcEnabled is false, I can still log in via oidc

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#3619]
Observed by Brenda and Dieuwke.

Expected behavior:
- when I disable isOidcEnabled then both UI and backend are disabled.
- the OIDC client etc settings is via environment

**What version of EMX2 are you using (see footer)**
v10.48.8

**Describe the bug**
When setting isOidcEnabled is false, I can still log in via oidc

**To Reproduce**
1. Go to https://data-catalogue.molgeniscloud.org/apps/central/#/admin/settings and log in as admin
2.  See that setting isOidcEnabled is false, or set isOidcEnabled to false if it is true
3. Log out.
4. Log in via oidc.
5. See that you can still log in via oidc.

On the directory app this stays on/off. Check if there the menu doesn't look at the setting?

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
This setting can only be set via commandline, not via user interface

**Comment by BrendaHijmans** [comment]
Why is that? We used to be able to edit this setting via user interface.

**Comment by mswertz** [comment]
ok, so we want to set both via env an via setting. setting takes preference over env?

**Comment by BrendaHijmans** [comment]
In v10.103.1 the setting isOidcEnabled does work.

**Comment by BrendaHijmans** [comment]
in v10.93.1 it also works.

**Comment by BrendaHijmans** [comment]
Setting isOidcEnabled is still working now in v11.31.1, so I wonder whether we should merge this.
