### ISSUE TITLE
Biobank Directory Country filter should use the country field at the biobank level

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis-emx2#3645]
**What version of EMX2 are you using (see footer)**
v10.58.0

**Describe the bug**
When I search for biobanks in a specific country I only see the biobanks that have declared any collection, but not those without a collection, because the search is based on the collection.country instead of biobank.country.

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'
2. Click on 'directory-demo'
3. Select 'Norway' in the country filter
4. note the number of organisations found (8)
5. Go to the Tables
6. Go to Biobanks
7. Add a filter for Country and filter on Norway
8. Note the number of organisations found (11)

**Expected behavior**
The filter works based on the country at the biobank level.

**Comment by chinook25** [comment]
Isn't this the same issue as #3623? This should get fixed in #3643 as well.

**Comment by esthervanenckevort** [comment]
No, it is not the same issue. Because the collections.country is used instead of biobanks.country you cannot search for biobanks in Norway that offer Recontacting as a service for instance.
