### ISSUE TITLE
Changes made in the schema editor cannot be saved for schemas with inherited tables

### ISSUE THREAD

**Issue by YpeZ** [molgenis/molgenis-emx2#3655]
**What version of EMX2 are you using (see footer)**
v10.58.1

**Describe the bug**
When trying to save changes made in the schema editor on a schema with at least one inherited table, an error is raised along the lines of 
> Transaction failed: column "{first column}" of relation "{inherited table}" already exists.

See the screenshot.

**To Reproduce**
The schema used to demonstrate this problem is that of the _pet store_ with additional tables _Customer_ and _Seller_ that extend the _User_ table.

1. Go to 'https://emx2.dev.molgenis.org/SchemaEditor%20bug/schema/#/'
2. Add a column with arbitrary name to a table, delete it with the trash icon, click the `Save` button
3. See error

This procedure does not lead to an error on the [pet store schema](https://emx2.dev.molgenis.org/pet%20store/schema/#/), which has no inherited table.

**Expected behavior**
In the reproduction example, no actual changes were made to the schema, but the error is raised regardless.
Either it should be saved without error, or a warning should be shown that no changes were made.

**Screenshots**
<img width="1101" alt="image" src="https://github.com/molgenis/molgenis-emx2/assets/14897333/7ad3b493-2999-40f3-ba06-c9d7ff22e17f">

**Additional context**
The same error occurs when uploading a schema `molgenis.csv` file to a schema with already a schema in place.

**Comment by mswertz** [comment]
First thing to make clear if this error is from sql (then we create a column where we shouldn't) or an internal validation.
