### ISSUE TITLE
Cohorts are not displayed in the 'overview of harmonisation status' table if they have no data

### ISSUE THREAD

**Issue by timcadman** [molgenis/molgenis-emx2#3662]
**What version of EMX2 are you using (see footer)**
v10.58.0

**Describe the bug**
When in a 'network' then you expect in the harmonisation status to see all cohorts involved so you can quickly assess completeness of the harmonisation accross all cohorts. However, currently, only cohorts having mappings are shown, without explictly showing that the other cohorts don't have mappings.

**To Reproduce**
1. Go to [https://data-catalogue-acc.molgeniscloud.org/testCatalogue/ssr-catalogue/]()
2. Click on 'testNetwork1'
3. Click on 'Variables'
4. Search 'adhd'
5. In the variable view, click on 'testVarRepeats'
6. Scroll down to 'harmonisation view per cohort'
7. See that no information is displayed for 'testCohort2'

**Expected behavior**
If a cohort has no harmonisations, it should still be listed in the 'overview of harmonisation status' with the white square representing 'no data' displayed for each repeat

**Screenshots**
![Captura de pantalla 2024-04-22 a las 16 58 08](https://github.com/molgenis/molgenis-emx2/assets/41470917/d092f875-e1f2-4bbf-9cda-b1c7792298b8)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 122.0.6261.69

**Comment by mswertz** [comment]
duplicate
