### ISSUE TITLE
Unable to Save Multiple Treatments (extends) for a Subject (using refback to treatment)

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis-emx2#3670]
**What version of EMX2 are you using (see footer)**
Software version: [v10.58.0](https://github.com/molgenis/molgenis-emx2/releases/tag/vv10.58.0)

**Describe the bug**
I encountered an issue while attempting to save information for multiple treatments associated with a subject in EMX2. Here's the scenario:

1.  I have a subject in the database.
2. There are multiple questions regarding treatment for different conditions, such as epilepsy and delayed puberty.
3. I used an "extend" to specify treatment, with each question linking back to the "extendTreatment" entity.
4. When attempting to save information for more than one treatment for a patient, I encountered the following error:
5. `failed.: Transaction failed: SQL [update "extendTreatment"."rasopathies" set "belongsToSubject" = 'test', "subTypeRasopathy" = 'schwannomatosis', "prenatalImaging" = 'na', "abnormalThyroid" = 'hyper', "abnormalThyroidTreatment" = cast('{"d994a6d1-aa3a-493c-8f11-3f0c23b337d1"}' as varchar[]), "diabetes" = 'yes', "diabetesTreatment" = cast('{"b9675a4e-9c7c-4e93-8bf1-d6021bdc2312"}' as varchar[]), "linkToAuxology" = cast('{"b059f962-84df-417a-a5f1-8f2d2566714a"}' as varchar[]), "delayedPuberty" = 'yes', "delayedPubertyTreatment" = cast('{"97d49ca1-debe-4e45-a932-a25b3f13cf19"}' as varchar[]), "intellectualDisability" = 'na', "abnormalHeartMorphology" = 'no', "cardiomyopathy" = cast('{"no"}' as varchar[]), "lymphaticAnomaly" = 'no', "deafnessHearingImpairment" = 'no', "label" = 'schwannomatosis', "mg_draft" = false, "mg_updatedBy" = 'admin', "mg_updatedOn" = timestamp '2024-04-26 11:28:55.939786961' where "id" = '6ebb5c1f-4280-48b2-84b4-e11fea8f6a24']; Batch entry 0 update "extendTreatment"."rasopathies" set "belongsToSubject" = 'test', "subTypeRasopathy" = 'schwannomatosis', "prenatalImaging" = 'na', "abnormalThyroid" = 'hyper', "abnormalThyroidTreatment" = cast('{"d994a6d1-aa3a-493c-8f11-3f0c23b337d1"}' as varchar[]), "diabetes" = 'yes', "diabetesTreatment" = cast('{"b9675a4e-9c7c-4e93-8bf1-d6021bdc2312"}' as varchar[]), "linkToAuxology" = cast('{"b059f962-84df-417a-a5f1-8f2d2566714a"}' as varchar[]), "delayedPuberty" = 'yes', "delayedPubertyTreatment" = cast('{"97d49ca1-debe-4e45-a932-a25b3f13cf19"}' as varchar[]), "intellectualDisability" = 'na', "abnormalHeartMorphology" = 'no', "cardiomyopathy" = cast('{"no"}' as varchar[]), "lymphaticAnomaly" = 'no', "deafnessHearingImpairment" = 'no', "label" = 'schwannomatosis', "mg_draft" = false, "mg_updatedBy" = 'admin', "mg_updatedOn" = timestamp '2024-04-26 11:28:55.939786961' where "id" = '6ebb5c1f-4280-48b2-84b4-e11fea8f6a24' was aborted: ERROR: column "belongsToRASopathy" of relation "treatmentabnormalThyroid" does not exist Where: PL/pgSQL function "extendTreatment"."1rasopathies-abnormalThyroidTreatment_UPDATE"() line 16 at SQL statement Call getNextException to see other errors in the batch..
`
This error prevents me from saving data for multiple treatments for the same subject. It seems that there's a limitation or inconsistency in the database schema or data linkage that is causing this issue. Added treatments are visible in treatment tables.

**To Reproduce**
1. Create test database
2. Upload datamodel with additional ontologies (and dataprovider (optional))
3. Go to "/tables/#/Rasopathies"
3. Create dummy patient info (fill in all mandatory fields)
4. add two treatments, go to 'growth &GH', add 'yes' in question Abnormal thyroid function.
5. add 'treatmentabnormalThyroidFunction'
6. add 'yes' in question 'Diabetes'
7. add 'treatmentDiabetes'
8. See error

**Expected behavior**
I should be able to save information for multiple treatments associated with a subject without encountering any errors. The database schema and data linkage should support this functionality seamlessly.

**Screenshots**
<img width="1122" alt="Scherm­afbeelding 2024-04-26 om 11 26 58" src="https://github.com/molgenis/molgenis-emx2/assets/40240913/4f41ad6e-5dad-4d24-9283-e1461d52c876">
[ontology1714124552335.zip](https://github.com/molgenis/molgenis-emx2/files/15128592/ontology1714124552335.zip)

[dashboard_data.zip](https://github.com/molgenis/molgenis-emx2/files/15128597/dashboard_data.zip)
[extendTreatment1714125348515.zip](https://github.com/molgenis/molgenis-emx2/files/15128600/extendTreatment1714125348515.zip)

**Comment by chinook25** [comment]
I can't create a schema using the provided data, there might be some errors in de zip files.
