### ISSUE TITLE
Directory app gets stuck when clicking on the network overview on the side cards

### ISSUE THREAD

**Issue by konstantina-gkp** [molgenis/molgenis-emx2#3687]
**What version of EMX2 are you using (see footer)**
v10.63.4-SNAPSHOT

**Describe the bug**
When clicking the network overview link in either biobank or collection side cards, the app is stuck on a loading spinner and never displays the network report.

**To Reproduce**
1. Go to 'https://directory-emx2-acc.molgenis.net/'
2. Click on a biobank card
3. Click the network overview on the side card

**Expected behavior**
The application should display the network report

**Additional context**
The console throws this error
![network_report_issue](https://github.com/molgenis/molgenis-emx2/assets/143411718/750956cd-a6c9-49e0-a07e-34fdf65b9ffb)

**Comment by esthervanenckevort** [comment]
I cannot reproduce this

**Comment by konstantina-gkp** [comment]
After pulling the latest changes, the issue still persists. The issue is on master. So, it should be easy to reproduce.
