### ISSUE TITLE
Tables are broken when using refLabel

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis-emx2#3699]
**What version of EMX2 are you using (see footer)**
v10.63.3-SNAPSHOT

**Describe the bug**
In the tables app the columns that refer to a different entity and use refLabel to construct the value to display are broken, because these fields are no longer fetched after https://github.com/molgenis/molgenis-emx2/pull/3688

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/directory-demo/tables/#/Biobanks'
2. See an error in the head, contact, also known in columns

**Expected behavior**
The fields necessary for the refLabel are fetched and the ref label is shown.

**Screenshots**

<img width="1798" alt="Screenshot 2024-05-02 at 14 58 16" src="https://github.com/molgenis/molgenis-emx2/assets/1942445/b1da2ed0-6740-4b42-87b6-5e8b864fd940">

**Comment by mswertz** [comment]
To be discussed: Might be that with the 'JIT' disable we can up the expandLevel to '1' again. Also, you could make sure that these fields are part of a 'key' because all key are still included, or that there is a computed field that has key= enabled.

**Comment by mswertz** [comment]
Can you test again @esthervanenckevort . We have reverted this issue

**Comment by esthervanenckevort** [comment]
Has been resolved
