### ISSUE TITLE
fix(user): created tokens should be visible in the application for user and admin

### ISSUE THREAD

**Issue by dtroelofsprins** [molgenis/molgenis-emx2#3700]
**What version of EMX2 are you using (see footer)**
v10.63.3

**Describe the bug**
- There is no list with created tokens visible in the application. So it's unclear which tokens are created/ still valid
- Able to create two tokens with the same name, where both tokens are valid

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org'
2. Create a token
3. Refresh the page => token is not visible

**Expected behavior**
- I would expect to see a list with created tokens (creation date (evt expiration date)) and would be able to delete/retract or refresh the token.
- Obviously token itself should remain hidden always
- I would expect that it should not be possible to create tokens with the same name.
- (Feature request), it would be nice if there was a 'copy' button next to the token (just like in GitHub).

**Additional notes**
- It seems tokens don't have any end-date

Note:
- okay to craete a new 'settings' app for this.

**Comment by chinook25** [comment]
I'm going to splits this issue into 3 separate issues:
 - Show tokens for the current user and allow deletion (fix, should already work) + Prevent tokens with duplicate names [PR4202](https://github.com/molgenis/molgenis-emx2/pull/4202)
 - Add copy button (feat)
 - Make a tokens manager for admins (feat)
