### ISSUE TITLE
ATHLETE network is not shown on the front page of the catalogue

### ISSUE THREAD

**Issue by EleanorHyde-UMCG** [molgenis/molgenis-emx2#3703]
**What version of EMX2 are you using (see footer)**
Software version: v10.60.0

**Describe the bug**
The ATHLETE network is missing from the list of all networks (https://data-catalogue-acc.molgeniscloud.org/catalogue/ssr-catalogue) but by navigating via networks in the EU Child Cohort Network, you can see that ATHLETE really is in the system. For some reason it's not displayed on the list of all networks.

**To Reproduce**
1. Go to https://data-catalogue-acc.molgeniscloud.org/catalogue/ssr-catalogue
2. See that the ATHLETE network is not listed under Project Catalogues.
3. Go and navigate via the networks in EUChildCohortNetwork to see that ATHLETE is in the system:
4. Click on EUChildNetwork
5. Click on Networks
6. See that ATHLETE is listed at the top of the list.

**Expected behavior**
All networks should be listed in the list of all networks.

**Screenshots**
Catalogue front page without ATHLETE:
![image](https://github.com/molgenis/molgenis-emx2/assets/80456579/dc310ca4-4fca-4b1f-9eb8-f02664f51b5f)

List of networks:
![image](https://github.com/molgenis/molgenis-emx2/assets/80456579/3fa9f454-baa3-4422-8a14-05eb139fd660)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by EleanorHyde-UMCG** [comment]
Originally thought this bug might be caused by the fact that ATHLETE for some reason has no logo in acc. However, we have no logos in testCatalogue in acc either, and still the networks are shown, so there must be something else happening.

**Comment by connoratrug** [comment]
ATHLETE is not part of data base table: https://data-catalogue-acc.molgeniscloud.org/catalogue/tables/#/Catalogues

**Comment by EleanorHyde-UMCG** [comment]
data also needs fixing in acc
