### ISSUE TITLE
feat(forms): enable use of subclass name for DefaultValue and Expressions

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis-emx2#3752]
**Is your feature request related to a problem? Please describe.**
Description:
Currently, emx2 allows the use of attributes for setting default values and expressions. However, it would be beneficial to extend this functionality to utilize subclass names as well.

Use Case:
For instance, consider a scenario where a treatment class is extended to create specialized treatments such as diabetes treatment (treatmentdiabetes subclass). In this case, it would be useful to set a default value for the "treatment for" attribute to dynamically reflect the subclass name, providing clarity on the type of treatment in the overview.

**Describe the solution you'd like**
I propose extending emx2 to support the following:

**DefaultValue**: Allow the use of the subclass name to automatically set default values for specific attributes. For example, setting a default value for the "treatment for" attribute to reflect the subclass name.
**Expressions**: Enable the use of the subclass name in expressions to perform operations or comparisons based on the subclass type.

 Example of how the feature could be utilized in schema configuration:

      defaultValue: $subclass_name  # Use subclass name as default value
    expressions:
      is_diabetes_treatment: "subclass_name === 'treatmentdiabetes'"  # Use subclass name in expressions

**Describe alternatives you've considered**
I tried using current set-up for defaultvalue and expressions, but Didi 

This for ERN -ITHACA:

<img width="1139" alt="Scherm­afbeelding 2024-05-16 om 09 10 25" src="https://github.com/molgenis/molgenis-emx2/assets/40240913/0a1f9174-749b-4fd9-b916-c0b42602d247">

**Comment by mswertz** [comment]
Did you try mg_tableclass?

**Comment by mswertz** [comment]
should be mg_tableclass
