### ISSUE TITLE
In the variable explorer, when I have selected a topic I would like this indicated all the way up the topic tree

### ISSUE THREAD

**Issue by timcadman** [molgenis/molgenis-emx2#3753]
**Is your feature request related to a problem? Please describe.**
Currently when you select a topic, the topic you have selected is marked with a tick, and the parent of that topic is marked with a horizontal line. However, the parent of the parent is not affected and shows no indication a subtopic has been selected. This is frustrating because when the particular topic tree is collapsed it is not apparent which subtopic is selected.

![Captura de pantalla 2024-05-16 a las 9 56 14](https://github.com/molgenis/molgenis-emx2/assets/41470917/e433a6e7-b458-4fdb-8b77-1c9c6ca9a527)

**Describe the solution you'd like**
The current behaviour is extended to the top level of the topic tree. If all subtopics are selected a tick is displayed the next level up, if some subtopics are selected a horizontal line is displayed the next level up, e.g.
![requested](https://github.com/molgenis/molgenis-emx2/assets/41470917/266b3d64-5fbe-4d5d-8172-fcf76fd91f5b)

**Comment by erikzwart** [comment]
Similar to #3604
