### ISSUE TITLE
Directory App: Concurrency issue with filters leads to old data being shown

### ISSUE THREAD

**Issue by dtroelofsprins** [molgenis/molgenis-emx2#3763]
**What version of EMX2 are you using (see footer)**
v10.66.4

**Describe the bug**
When selecting two filter options and then "match all" in the Directory App, the match all is not performed (results show match any).

**To Reproduce**
1. Go to 'https://directory-emx2-acc.molgenis.net'
3. Click on Categories filter and select Cancer and Covid19, then select Match all
4. Results show about 157 biobanks with about 500 (sub)collections, this should be 3 (or 30 incase #3733 is not fixed yet) biobanks and 3 collections 

**Expected behavior**
I would expect that in all cases the match al filter is performed well

**Additional context**
It might be a bit of a trial and error, because in case the match all is selected quicker (or slower) or you first wait till results are shown and then choose match all it seems to go OK. But independently of selecting things results should always be consistent (and right).

**Comment by chinook25** [comment]
@dtroelofsprins I can't reproduce this. Though it reads like it is a race condition of the requests made to the back-end.

**Comment by dtroelofsprins** [comment]
Yes, I think it's probably a race condition. I've tested several filters.
Material types goes too fast => can't reproduce it there.
Collection types: click case control and cohort => then wait till query starts and then quickly push match all
categories: covid19 and cancer, it happens here also

https://github.com/molgenis/molgenis-emx2/assets/57137088/7ab3f215-1430-4724-9bb0-f8b0b287c171

**Comment by konstantina-gkp** [comment]
I also tested all the cases mentioned in the conversation, and cannot reproduce the issue in any of them. When combining two filters with "match all", the application retrieves the proper results (for me at least).

I re-introduced the race-condition fix in the previous sprint and suppose that has fixed the initial issue mentioned in the ticket.
If we see that the problem still persists somewhere, I can check it further.

**Comment by esthervanenckevort** [comment]
I can still reproduce it after a few tries. So we still have a race condition here.
