### ISSUE TITLE
test(catalogue): get test data from ACC into github once all test data is finished

### ISSUE THREAD

**Issue by EleanorHyde-UMCG** [molgenis/molgenis-emx2#3813]
We've made changes to the data in testCatalogue in ACC and this needs to be copied over to the github demodata repository before we lose them. First we need to finish creating the test data and then we can copy everything over in one go.

**Comment by mswertz** [comment]
why don't you make this part of the other story?

**Comment by EleanorHyde-UMCG** [comment]
..because it's two different actions and requires two different people!
