### ISSUE TITLE
Table explorer not displaying collections in "Collections" table in directory app

### ISSUE THREAD

**Issue by konstantina-gkp** [molgenis/molgenis-emx2#3838]
**What version of EMX2 are you using (see footer)**
v10.77.1

**Describe the bug**
The "Collections" table is not displaying the collections of the directory app and throws an following error at the top of the page "Invalid syntax with offending token '}' at line 9 column 569".

**To Reproduce**
1. Go to molgenis
2. Select the directory schema
3. Click on "Collections" table.

**Expected behavior**
The collections need to be displayed on the "Collections" table.

**Screenshots**
![collections_table_issue](https://github.com/molgenis/molgenis-emx2/assets/143411718/d4c66411-7ec5-4e33-ad13-095160b66212)

**Comment by dtroelofsprins** [comment]
Just upgraded the https://directory-emx2-acc.molgenis.net to v10.77.2 and there the Collections are displayed without any errors.

**Comment by MaxPostema** [comment]
I think we can close the issue. On a database from early may the error is 'index-5a88f377.js:16 TypeError: Cannot read properties of undefined (reading 'tableType')'. Updating to the newest database fixes every thing for me.

( then again we probably don't want errors even with broken databases loaded )

**Comment by mswertz** [comment]
this was indeed a known issue related to cross schema references. That has been fixed as side effect of #3725
