### ISSUE TITLE
As soon as cohort filters are applied, the variable explorer should not show cohorts which are selected but which have no mappings for the variables selected

### ISSUE THREAD

**Issue by EleanorHyde-UMCG** [molgenis/molgenis-emx2#3866]
**What version of EMX2 are you using (see footer)**
v10.79.3-SNAPSHOT

**Describe the bug**
Too many cohorts are shown in the variable explorer: those selected but crucially WITHOUT a mapping to the variable(s) selected should not be shown in the harmonisation matrix.

**To Reproduce**
1. Go to https://preview-emx2-pr-3865.dev.molgenis.org/catalogue-demo/ssr-catalogue/testNetwork1/variables  [or the equiv in the correct prev / or in acc]
2. Click on Harmonisations.
3. See that there are 8 variables, with different mappings. testCohort2 has no mappings at all, but is shown. This is correct, because the cohort filter has not been applied.
4. Select testcohort2 only in the list of cohorts bottom left.
5. See that zero variables are displayed. This is correct.
6. Select testcohort3 alongside testcohort2.
7. See that all the variables for which testcohort3 has a mapping are shown (4), but that testcohort2 is ALSO shown. Display of testcohort 2 is incorrect.

**Expected behavior**
In step 7, testcohort2 should not be shown, because it has no mappings to the variables filtered on. As soon as the cohort filter is applied, only cohorts with mappings to the variables which result from the filtering are shown.

**Screenshots**
No cohortfilters applied: correct 
![image](https://github.com/molgenis/molgenis-emx2/assets/80456579/ebcaaef3-7b5c-49e6-a744-7a1e259037e4)

Only testcohort2 filtered: correct
![image](https://github.com/molgenis/molgenis-emx2/assets/80456579/72bbaa0a-1aa8-4af9-9a55-9970f734f725)

testcohort2 and testcohort3 selected: incorrect, testcohort2 should not be shown at all
![image](https://github.com/molgenis/molgenis-emx2/assets/80456579/2943a094-f229-4040-8eea-eb7d718adc5e)

**CONVERSELY**:

1. Go to the list of variables for testnetwork1: https://data-catalogue-acc.molgeniscloud.org/testCatalogue/ssr-catalogue/testNetwork1/variables
2. Click on testVarRepeats.
3. In the 'harmonisation status' block, all the repeats are shown with their mappings to the cohorts. Testcohort2 should be shown here because this matrix shows all the cohorts of the network in question with their mappings (fully, partially, NA). Leaving testcohort2 out here is incorrect.

**Screenshots**
![image](https://github.com/molgenis/molgenis-emx2/assets/80456579/5e4d63d7-28d3-42de-a16c-3f55ee6e10f5)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Chrome

**Comment by EleanorHyde-UMCG** [comment]
(see the 'conversely' part underneath as well, added later)

**Comment by mswertz** [comment]
Is this not a feature? I would like to explicitly see that testcohort2 has no mappings?

**Comment by mswertz** [comment]
the 'conversely' is also interesting but a seperate issue. And there, 

option1:
we would like to show all cohorts that have mapping unless specific cohorts are selected then I would also like to see those cohorts.

OR

option2:
do you want to have all cohorts that are partner in the network. And if so, what to do outside a network.

I would prefer option 1

**Comment by EleanorHyde-UMCG** [comment]
bug #3868 has been created for the 'conversely' part

**Comment by mswertz** [comment]
Works as intended. I don't want to do this

**Comment by EleanorHyde-UMCG** [comment]
Within the team we are in agreement that displaying cohorts actively selected whether or not they have mappings to the variables selected is beneficial to the user. This is not a bug and will be closed!
