### ISSUE TITLE
'AllVariables' table does not show anything

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#389]
**What version of EMX2 are you using (see footer)**
7.0.1

**Describe the bug**

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
this is by design, right?

**Comment by mswertz** [comment]
duplicate #181
