### ISSUE TITLE
Add publications section to cohort details view 

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#3894]
**Is your feature request related to a problem? Please describe.**
Add publications section to cohort details view, so user knows about related publications ( from schema; _Other publication(s) about this resource_)

**Describe the solution you'd like**
The publications field is part of the 'information' chapter when filling out the records data, a cohort may contain zero or more publications ( might even be more the 10 ), therefore it would be good to display these using the table component, initially showing the most important field and allowing the user view view all details ( use side modal component). If need we can further link the side-modal to a publication detail page or external doc / app

**Describe alternatives you've considered**
Adding to general design, not a good idea as this might be confusing with design paper field

**Comment by EleanorHyde-UMCG** [comment]
Looks good, could you make the DOI in the pop-up clickable, please, so that you then open the article in a new window?

**Comment by EleanorHyde-UMCG** [comment]
looks good!
