### ISSUE TITLE
fix(upload): When creating or updating a schema (metadata) using the molgenis-emx2-pyclient I need to re-login again to see the new /updated schema

### ISSUE THREAD

**Issue by dtroelofsprins** [molgenis/molgenis-emx2#3902]
**What version of EMX2 are you using (see footer)**
v10.86.0

**Describe the bug**
When creating a schema with create or recreate_schema or update the schema by uploading an adjusted molgenis.csv the new schema or updated metadata are not visible on a server if you are already logged in. You first need to logout and login again before being able to see that the script ran indeed successful. 
This already took quite some time from several people as they were not aware of this (or have forgotten that this occurs) and started debugging as they thought that the script was not working properly!

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'

**Expected behavior**
When I run a script (locally) using the molgenis-emx2-pyclient that creates a schema or updates the metadata I should see the results without having to logout and login again on the server where the script ran on. 

**Additional context**
We speculate that this goes wrong via tokens and that the databaselistener doesn't hit all the existing sessions.
It works fine when adding/updating/deleting data in tables.
Check if the frontend cached.

**Comment by mswertz** [comment]
DatabaseListener doesn't fire?
