### ISSUE TITLE
Catalogue ( tailwind / ssr ) 'random 'logo' appears on cohorts page when screen side is below lg 

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#3930]
**What version of EMX2 are you using (see footer)**
10.98.0

**Describe the bug**
Catalogue ( tailwind / ssr ) 'random 'logo' appears on cohorts page when screen side is below lg 

**To Reproduce**
1. Go to all/cohorts page 
2. reduce screen size until small header is shown

**Expected behavior**
no 'random' logo appears

**Screenshots**
![Screenshot 2024-06-27 at 13 35 23](https://github.com/molgenis/molgenis-emx2/assets/47183404/51732bcc-00e6-42fc-98d9-8898ae956999)

**Desktop (please complete the following information):**
 - mac os 
 - Browser chrome

**Comment by BrendaHijmans** [comment]
cannot reproduce on windows, chrome browser
