### ISSUE TITLE
feat(user): Have besides viewer, editor and manager, a "user" role for menu items so menu item is shown for authorized users

### ISSUE THREAD

**Issue by dtroelofsprins** [molgenis/molgenis-emx2#3980]
demo:
* in the menu manager I can choose 'authorized user' as role that you need to show a menu item
* when authorized user views the menu also those item are shown

**Is your feature request related to a problem? Please describe.**
In the Directory data managers of the National Node can login to add/update data. To get to their own schema, a "Navigator" tab is included in the menu items. The navigator menu-item is now available for Viewers in the ERIC schema as this is where you are redirected to after login, which means that's also visible for anonymous as anonymous has viewer role. This is rather unwanted (the data in the ERIC/DirectoryOntologies schema is not sensitive, but it's not relevant that people see this). 

**Describe the solution you'd like**
Have the option to make a menu item visible for logged in users only

**Describe alternatives you've considered**
- Accept that anonymous people can see the schema list.
- Setting Navigator to Editor role does not solve it, because then people can also edit the ERIC schema and that's unwanted.

**Additional context**
- In the EMX1 version of the Directory this is feasible as described.
- This for certain is not only applicable for the Directory but this is certainly also relevant for other servers/projects

**Comment by mswertz** [comment]
does the 'authorised user' exist?

**Comment by mswertz** [comment]
or can this be hacked by checking if current user is anonymous?
because if the user is signed in you can ask the user.
Bottomline: in the config of menu we should then be able to enable this.
