### ISSUE TITLE
Ref columns with composite keys are broken in forms

### ISSUE THREAD

**Issue by YpeZ** [molgenis/molgenis-emx2#4002]
**What version of EMX2 are you using (see footer)**
v10.93.1

**Describe the bug**
When trying to add a new entry in a table that references another table on the same schema, the entries in that that table cannot be loaded and the message `Failed to load data` is shown (see screenshot 1).
When a referenced value in an existing entry is clicked, a dialog pops up. Instead of showing the information related to the referenced item, a spinner is shown spinning ad infinitum (see screenshot 2).
A quick look into the GraphQL queries reveals that the referenced table is requested with a filter that contains too much information.

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org'
2. Sign in as admin
3. Go to the 'catalogue' schema, to the tables view
4. Click the 'Variables' table and click on the ➕ to add a new entry.
5. Select any 'resource' in the first field and then click the 'dataset' field
6. See error 1
7. Close the entry dialog and click on any cell in the 'dataset' column
8. See error 2

**Expected behavior**
The data should just load and appear.

**Screenshots**
Screenshot 1
![image](https://github.com/molgenis/molgenis-emx2/assets/14897333/ef020bf4-73fe-4b02-a19f-46b622aaeada)
Screenshot 2
![image](https://github.com/molgenis/molgenis-emx2/assets/14897333/c7126795-c548-4297-a176-68fae27d6a2b)

**Additional context**
The 'Resources' table referenced in the column 'resource' does load, however.

**Comment by mswertz** [comment]
do you know what version it did still work?
