### ISSUE TITLE
fix(catalogue): reference between Subcohort and collection event does not work in the UMCG Research Data Catalogue

### ISSUE THREAD

**Issue by kimmeijercbch** [molgenis/molgenis-emx2#4025]
**What version of EMX2 are you using (see footer)**
v10.93.1

**Describe the bug**
IN the table Collection events Subcohorts are selected. Currently this connection seems 'broken'.

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'](https://umcgresearchdatacatalogue.nl/AHON/tables/#/Cohorts)
2. Go to Collection event 'event 1'
3. Under 'subcohorts' two are selected: 'AHON' and 'RNG'.
4. Both options are also shown below, in red. 
5. Furthermore there is a warning message: value should match your selection in column 'resource'
6. You can remove the chosen subcohorts, and select them again. But after closing the collection event, and opening is again, the same problem occurres. 

Screenshots
![image](https://github.com/molgenis/molgenis-emx2/assets/139363752/334bc9d6-1f5f-44dd-9d33-f96a97677d9d)

**Additional context**
Comment Brenda: Collection events.subcohorts is een ref_array naar Subcohorts, een tabel met een composite key

The issue is probably related to issue #4002

**Comment by hslh** [comment]
![Screenshot 2024-08-14 at 15 37 47](https://github.com/user-attachments/assets/708cd7c6-2796-4086-8ed4-40ecaed4d497)
Bug no longer present in v10.109.1, probably fixed when #4002 was fixed.
