### ISSUE TITLE
fix(forms): some design paper are de-selected and therefore not shown in the catalogue <= waiting on kim, otherwise done?

### ISSUE THREAD

**Issue by kimmeijercbch** [molgenis/molgenis-emx2#4026]
First step: Check if still broken

**What version of EMX2 are you using (see footer)**
v10.93.1

**Describe the bug**
Most or all of the design papers that have been added to the staging areas of the cohorts are de-selected, and therefore not shown in the catalogue. 

**To Reproduce**
1. Go to https://umcgresearchdatacatalogue.nl/AHON/tables/#/Cohorts
2. Go to chapter 'Other information'
3. Under design paper there is one selected. The rest is not. 

**Expected behavior**
All design papers that have been entered should be selected, and therefore be visible in the catalogue. 

**Screenshots**
![image](https://github.com/molgenis/molgenis-emx2/assets/139363752/dcac8e7d-9b25-4d32-b619-98d9dda6edac)

**Additional context**
This issue might be related to issues #4002 and #4025

**Comment by BrendaHijmans** [comment]
Need feedback from Kim about validity of data under 'design paper' in staging areas

**Comment by BrendaHijmans** [comment]
This is related to an existing issue: Publications are not always synced to the catalogue, issue here: https://github.com/molgenis/molgenis-emx2/issues/4103
