### ISSUE TITLE
Fix error and out.log so it can be parsed into filebeat

### ISSUE THREAD

**Issue by mswertz** [molgenis/molgenis-emx2#403]
- right format
- rotation

**Comment by connoratrug** [comment]
https://github.com/molgenis/molgenis-emx2/blob/54afe0db2da727ab9877f1950b104f14625a6273/backend/molgenis-emx2/src/main/resources/log4j2.xml#L5

**Comment by christianhilbrands** [comment]
maybe this can help... [log4j2 rolling file appender](https://howtodoinjava.com/log4j2/log4j2-rollingfileappender-example/)

**Comment by connoratrug** [comment]
Done: 

- The date was added to the default log4j2.xml logging config
- The VM deployment used a external log4j2.xml config to define the rolling file log ( file location , rollovers , ... ) 
- external log4j2 config can be loaded when running the jar ```-Dlog4j2.configurationFile=/path/to/log4j2.xml``` 

<img width="1163" alt="Screenshot 2021-08-06 at 16 04 14" src="https://user-images.githubusercontent.com/47183404/128522349-7301e064-9a6d-4092-a0ba-230234698ac5.png">
