### ISSUE TITLE
Database creation times out after 1 minute when creating database from template

### ISSUE THREAD

**Issue by YpeZ** [molgenis/molgenis-emx2#4037]
**What version of EMX2 are you using (see footer)**
v10.97.2

**Describe the bug**
When creating a database on a server with certain templates, it appears as if this process takes a really long time.
This is vindicated by the statement _creating schema, may take a while ..._ (see screenshot).
In reality the process is aborted after one minute, but this is not relayed to the user.
The timeout needs to be increased and the fact that the process is aborted needs to be shown.

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org' and sign in as admin
2. Open the dialog for creating a new database
3. Choose a name and select the `FLAT_DATACATALOGUE` template
4. Wait and see how the schema is not actually created

**Expected behavior**
The creation should firstly not time out.
Now that it does, it should at least be shown that a timeout has reached, otherwise you can keep waiting until eternity.

**Screenshots**
<img width="976" alt="image" src="https://github.com/user-attachments/assets/35713ab4-dcbb-46a5-9d2f-c335c4e5dd87">

**Additional context**
Creating a database with the Pyclient or directly with GraphQL yields the same result.

**Comment by mswertz** [comment]
will be fixed using #3059
