### ISSUE TITLE
Deprecated api endpoint for sending requests to the negotiator in the directory app

### ISSUE THREAD

**Issue by konstantina-gkp** [molgenis/molgenis-emx2#4045]
**What version of EMX2 are you using (see footer)**
v10.97.2-SNAPSHOT

**Describe the bug**
The directory app is currently using a deprecated endpoint to send requests to the negotiator. I noticed on [Swagger](https://negotiator.acc.bbmri-eric.eu/api/swagger-ui/index.html#/) that there is a new API endpoint for POST requests: /v3/requests. The new api endpoint accepts a JSON payload in the following format:

```{
  "url": "string",
  "humanReadable": "string",
  "resources": [
    {
      "id": "string",
      "name": "string",
      "organization": {
        "id": 0,
        "externalId": "string",
        "name": "string"
      }
    }
  ]
}
```
**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org'
2. Go to the directory app
3. Add a collection to the negotiator selection
4. Click "Request"
5. See "Bad request" error on the Network tab.

**Expected behavior**
The endpoint and the payload should be updated.

**Comment by esthervanenckevort** [comment]
Has been resolved in #4044
