### ISSUE TITLE
feat(ern): Create Internal Pseudonym (using Auto ID #183 dev team)

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis-emx2#4066]
**Is your feature request related to a problem? Please describe.**
For ERN ITHACA local installations we need a local pseudo-tool (Create Internal Pseudonym). This feature request provides a foundation for implementing the "Create Internal Pseudonym" feature. It ensures that patient identifiable information is stored separately from other patient data, with a pseudonym linking the two databases.

**Describe the solution you'd like**
**System Components:** EMX2 installation, with two ILIAD databases: ”subject” and “internalIdentifier”
**User Interface:**
a. New Patient Creation Form (can be plus sign in EMX2)
b. Pop-up Modal for Patient Identification (<needs to be created)
**Workflow:**

1. User initiates "New Patient" action
2. System displays Pop-up Modal with fields:

- First Name (required)
- Last Name (required)
- Date of Birth (required)
- Hospital Identifier (optional)

3. User fills in the required information
4. User submits the form
5. System performs duplicate check
6. If duplicate found, display warning with existing pseudonym
7. If no duplicate, generate pseudonym and proceed
8. System displays Patient Information Form pre-filled with pseudonym
9. User completes Patient Information Form
10. System saves data to respective databases

**Detailed Component Specifications:** 
_a. Pop-up Modal:_
- Fields: First Name, Last Name, Date of Birth, Hospital Identifier
- Validation: Ensure required fields are filled
- Submit button

_b. Application Server:_
- Duplicate Check Logic
- Pseudonym Generation Algorithm (for now can be something easy, using molgenis-logic, computed value: ​​dataprovider.name_${mg_autoid})

**Additional context**
In the future, fields that are required to create pseudonym, can be changed. 
And creation of pseudonym can be more complex, then my solution dataprovider.name_${mg_autoid}.

Design:
~~- if the hospital identifier is given, we use that to generate the pseudoid. Otherwise we use firstname, lastname, birthdate.
~~- we want the id field to check in the database if it already exists before we save, so that we can give the error immediately. ~~"There is already a pseudoid 'xxxx' for this hospital id/firstname/lastname/birthdate" => if(mg_clientside) 
~~....;
~~- we use the firstname/lastname/birthdate OR hospitalid for the duplicate check, not the generated pseudoid so that the pseudo can be totally random. 
=> this means we can use the autoid? <= can we make that shorter?

emx1 genetic line psuedo id: 
https://registry.molgenis.org/#browse/browse:appstore:molgenis-app-pseudonym-registration%2F1.2.0%2Fmolgenis-app-pseudonym-registration.v1.2.0.zip

**Comment by mswertz** [comment]
kan dit niet met aparte patienten details tabel (met dus pseudo, firstname, lastname, birthdate en dat je dan vanuit je research data tabel daarnaar verwijst (zodat je die research data apart kunt exporteren met alleen de pseudo)

**Comment by Fernananas** [comment]
Close, issue. Since workaround is good enough, other feedback more important. If needed we can revisit, when requested

**Comment by Fernananas** [comment]
Close, issue. Since workaround is good enough, other feedback more important. If needed we can revisit, when requested
