### ISSUE TITLE
Allow localhost usage in emx2-pyclient

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis-emx2#4075]
## Current Behavior
The current `parse_url` function in pyclient enforces HTTPS, which prevents the use of localhost. This makes it difficult to create uniform scripts for local installations without knowing the specific URL.

## Desired Behavior
We should be able to use localhost in pyclient, allowing for uniform scripts across local installations. This was possible in EMX1 and should be implemented in the current version.

## Proposed Solution
Modify the `parse_url` function to allow for localhost connections. Here's a suggested implementation:

```python
def parse_url(url: str) -> str:
    """
    Standardises the host by removing trailing slash and ensuring url starts with 'http://' or 'https://'.
    Allows for localhost connections.
    """
    url = url.rstrip('/')
    if url.startswith('localhost') or url.startswith('127.0.0.1'):
        return f'http://{url}'
    elif not url.startswith(('http://', 'https://')):
        return f'https://{url}'
    return url

**Comment by mswertz** [comment]
remove the validation, this is up to the user
