### ISSUE TITLE
feat(forms): expression simplePostClient backend suport

### ISSUE THREAD

**Issue by MaxPostema** [molgenis/molgenis-emx2#4078]
**Is your feature request related to a problem? Please describe.**
In a frontend expression its possible to do a "simplePostClient" request to check values from an other table. This worked for a while. Possible a bug fix in the backend broke this. #3695 

**Describe the solution you'd like**
That backend before the bugfix never ran the query. The best solution might be to have a "simplePostClient" request functionality in the backend itself, making bulk uploads also do the expression checks.

**Describe alternatives you've considered**
- Having a way so tell the backend not to execute a selected (frontend only) query

**Additional context**
simplePostClient in manual:
https://emx2.dev.molgenis.org/maxTest/docs/#/molgenis/use_schema?id=helper-functions

simplePostClient in code:
https://github.com/molgenis/molgenis-emx2/blob/master/apps/molgenis-components/src/components/forms/formUtils/formUtils.ts#L177

@Fernananas needs this for ernithaca

**Comment by mswertz** [comment]
I think this bugfix https://github.com/molgenis/molgenis-emx2/pull/3695 didn't break it but made issue visible in our specific cases
