### ISSUE TITLE
SSR catalogue is broken due to a query involving Networks.partOfNetworks refback which breaks the data model <= cannot reproduce?

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#4086]
**What version of EMX2 are you using (see footer)**
10.106.2

**Describe the bug**
The SSR interface is broken since this merge: #4048, when a query was implemented using a data model change that makes a circular reference. 
![image](https://github.com/user-attachments/assets/b5626aa0-6a83-4c7b-ac7b-4b166d752b77)

**To Reproduce**
1. Go to https://emx2.dev.molgenis.org/catalogue-demo/ssr-catalogue/
2. Click on any catalogue
3. Get a blue screen, without any call to action buttons

**Expected behavior**
A clear and concise description of what you expected to happen.Expect to see call to action buttons

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
As part of the migration you should create the 'partOfNetworks' refback field.

E.g. using attached file
[molgenis.csv](https://github.com/user-attachments/files/16423781/molgenis.csv)

**Comment by mswertz** [comment]
@BrendaHijmans please help me: were are migrations for data catalogue documented?

**Comment by mswertz** [comment]
I was actually able to upload a edited download of demo catalogue where I added the partOfNetworks

[catalogue-demo_ 202407300815.csv](https://github.com/user-attachments/files/16424530/catalogue-demo_.202407300815.csv)

**Comment by mswertz** [comment]
I cannot reproduce
