### ISSUE TITLE
Bookmark functionality in directory app does not work for checkout store

### ISSUE THREAD

**Issue by konstantina-gkp** [molgenis/molgenis-emx2#4097]
**What version of EMX2 are you using (see footer)**
v10.106.4-SNAPSHOT

**Describe the bug**
The checkout store in the directory app has the functionality of adding the negotiator selection as a bookmark. The bookmark functionality is broken.

**To Reproduce**
1. Go to the directory app
2. Click on a biobank
3. Add a collection of the biobank to the negotiator selection
4. Click "Request"
5. Copy the URL and paste it in a new browser
6. The new page does not have the collection which was added to the negotiator selection

**Expected behavior**
The bookmark should either work properly or should be removed entirely.

**Comment by dtroelofsprins** [comment]
I'm not sure if it relates to this, but the Negotiator itself doesn't have/use bookmarks anymore.

@esthervanenckevort is this indeed an issue, or can the code be removed as it's indeed not relevant anymore?

**Comment by esthervanenckevort** [comment]
Bookmarking is only used for a search, not for the selection of collections, so this is not relevant.
