### ISSUE TITLE
The cohort filter and harmonisation tab do not show all cohorts within a network of networks

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#4104]
**What version of EMX2 are you using (see footer)**
v10.103.1

**Describe the bug**
Only the cohorts that are directly linked to the network under [Networks.cohorts](https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/networks/EHEN) are shown here:
![image](https://github.com/user-attachments/assets/baf8429a-356d-476f-8bce-912db36bfd5b)

There should be more cohorts and harmonisation options, because there are more cohorts linked via Networks.networks: 
![image](https://github.com/user-attachments/assets/a776692a-3c85-4573-acf1-45a997feaa5b)

**To Reproduce**
1. Go to https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/EHEN
2. See that 75 cohorts are linked
3. Click on Variables
4. Click on 'cohorts' on the left to expand the cohorts filter, there are only about 15 cohorts there
5. Click on Harmonisations
6. See that the same cohorts are there and not n=75.

**Expected behavior**
All cohorts within the network of networks should be shown

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
Probably same as #2204
