### ISSUE TITLE
fix(directory): bookmarkable URL fails

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis-emx2#4121]
**What version of EMX2 are you using (see footer)**
v10.106.4

**Describe the bug**
Error when opening a bookmarked URL searching for country=AT and Diagnosis available=icd:II (Neoplasms)

**To Reproduce**
1. Go to 'https://directory.bbmri-eric.eu/ERIC/'
2. Click on 'country' and select Austria
3. Click on 'diagnosis available' and select 'II Neoplasms'
4. Copy the URL and paste it in a new browser window
5. App gets stuck with a spinner and there is an error in the console

**Expected behavior**
The app restores the search state.

**Screenshots**
<img width="1316" alt="Screenshot 2024-08-12 at 10 29 21" src="https://github.com/user-attachments/assets/19572c29-272b-4edb-9aad-c8ef884990ad">

**Comment by mswertz** [comment]
We noticed it fails in safari 17.6 but worked in 17.4.1.

However we also notice that all children are selected, is that necessary?

**Comment by esthervanenckevort** [comment]
Issue is still present in the specific Safari version mentioned (17.6 latest version at this moment). I discovered that Safari will not copy the entire URL if you copy it from the address bar, but it does work from the share sheet (mail URL, bookmark, etc). So I closed this issue since this is a Safari issue.
