### ISSUE TITLE
Not possible to add records via UI in an empty table

### ISSUE THREAD

**Issue by dtroelofsprins** [molgenis/molgenis-emx2#4130]
**What version of EMX2 are you using (see footer)**
v10.109.1 => v10.109.0 WORKS FINE

**Describe the bug**
When either, using a template (without demo data), create a database and then upload molgenis.csv or add a new table via the Schema editor => in alle cases opening a table doesn't show the table explorer (actually it's quickly shown, but then an empty screen is shown), making it impossible to add data via UI in an empty table

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org'
2. Create a database with the pet store template without demo data
3. Open one of the tables, f.e. the Pets
4. See an empty screen

**Expected behavior**
Adding data to an empty table should be possible by using the table explorer!

**Screenshots**
![image](https://github.com/user-attachments/assets/39ae60d2-bd26-4bd8-ad00-ce97332dc5f1)

**Desktop (please complete the following information):**
 - Browser: both Chrome and Safari

**Additional context**
When demodata option = true OR adding data via upload, the table explorer works fine.

**Comment by MaxPostema** [comment]
Quick look, i think in this PR some use case was overlooked:
https://github.com/molgenis/molgenis-emx2/pull/4108
