### ISSUE TITLE
feat(scripts/jobs): include complete logging in notification email

### ISSUE THREAD

**Issue by dtroelofsprins** [molgenis/molgenis-emx2#4177]
**Is your feature request related to a problem? Please describe.**
Recently the possibility to send a notification email in case a script fails has been implemented. This works nice. However it only sends the first line of the logging:
`Molgenis script testFailingJob failed with error:
Script failed. Exit value: 1 in 5346ms` 

This is not really informative (a.o what is the actual error, which server?).

**Describe the solution you'd like**
- minimally the real error (at the bottom of the logging) could be send,
- ideally event complete logging 

**Describe alternatives you've considered**
Accept this and check the email message details to check which server the message originated from. This is not optimal and when using support@molgenis.org (which probably will often be the case), the message will end up like a ticket in which message details cannot be checked at all. 

**Additional context**
What really, really would be nice if in some way also the server where the script ran could be included in f.e. the subject of the message. 
We now (at least try) to include a `print("serverURL")` in the script to easily see on which server the script that failed ran.

**Comment by dtroelofsprins** [comment]
Just discussed during standup and Esther mentioned that including the whole log would include a potential risk leaking sensitive information. 

=> Then "Additional context" would be the preferable option (or even a must have).

**Comment by mswertz** [comment]
Ah, would we instead be able to provide a link to the failed job?

**Comment by dtroelofsprins** [comment]
That would indeed also be a very good idea!
