### ISSUE TITLE
fix(catalogue): On variables overview page, filtering on variable name ‘asthma’ and selecting the 4 test cohorts doesn’t display any variables.  

### ISSUE THREAD

**Issue by mswertz** [molgenis/molgenis-emx2#4247]
See: $testCatalogue/ssr-catalogue/all/variables?page=1&conditions=[{"id":"search","search":"asthma"},{"id":"collections","conditions":[{"name":"testCohort4"},{"name":"testCohort3"},{"name":"testCohort2"},{"name":"testCohort1”}]}]. (test 7 step 10)

**Comment by hslh** [comment]
Expected outcome according to test plan: "See that the same list of 15 variables is displayed, with zero mappings for all four cohorts."

**Comment by hslh** [comment]
What is the behaviour we want to see here? That's something we should answer first.

**Comment by hslh** [comment]
Discussed this with @EleanorHyde-UMCG , we do want to maintain the original behaviour. For an example, search all variables in the production catalogue, search on 'asthma' and select 'ABCD' cohort. @connoratrug

**Comment by EleanorHyde-UMCG** [comment]
@EleanorHyde-UMCG

**Comment by BrendaHijmans** [comment]
agebirth_p_fath:

https://data-catalogue-acc.molgeniscloud.org/catalogue/ssr-catalogue/EHEN/variables?page=1&conditions=[{%22id%22:%22resources%22,%22conditions%22:[{%22name%22:%22BIB%22}]}]&view=harmonisation

maar BIB mapping status is 'completed'

https://data-catalogue-acc.molgeniscloud.org/catalogue/ssr-catalogue/EHEN/variables/agebirth_p_fath-LifeCycle-core-LifeCycle?keys={%22name%22:%22agebirth_p_fath%22,%22resource%22:{%22id%22:%22LifeCycle%22},%22dataset%22:{%22name%22:%22core%22,%22resource%22:{%22id%22:%22LifeCycle%22}}}

**Comment by hslh** [comment]
We've decided to make it internally consistent by not showing empty matrices anymore but simply showing the message 'No variables found with current filters'. So, the behaviour shown here is intended and this issue is no longer relevant. 

The BIB/agebirth_p_fath issue is a separate one.

**Comment by mswertz** [comment]
I have been testing the 'master' and there it seems to be showing this behavior.

**Comment by BrendaHijmans** [comment]
Note that 'filtering on variable name' is incorrect here: When using the search box, you search through all attributes inside the table Variables that may contain the word 'asthma', also the variable description.
