### ISSUE TITLE
Filtering on network shows no variables in variable explorer

### ISSUE THREAD

**Issue by hslh** [molgenis/molgenis-emx2#4262]
**What version of EMX2 are you using (see footer)**
v11.14.1

**Describe the bug**
Filtering on a network in the variable explorer shows no variables.

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/catalogue-demo/ssr-catalogue/all/variables'
2. Click the filter for testNetwork1
3. See error
4. Compare to 'https://emx2.dev.molgenis.org/catalogue-demo/ssr-catalogue/testNetwork1/variables', which does show testNetwork1's variables

**Expected behavior**
Filtering on a network in the variable explorer shows variables.

**Comment by BrendaHijmans** [comment]
Network filter was removed from page.
