### ISSUE TITLE
Table explorer in network staging cannot display Resources table

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#4264]
**What version of EMX2 are you using (see footer)**
11.14.1, still in v11.25.1

**Describe the bug**
The table explorer expects to find a column 'local name' in the Resources table. This is not present in the 4.x or 5.x 'Networks staging model', so the Resources table cannot be viewed in a network staging area.
This happens in model 4.x and 5.x in the networks staging areas. I guess because Resources.localName is not in the NetworksStaging profile, but it is in the catalogue schema. And the NetworksStaging has a ref_array to Resources in the catalogue schema.

![image](https://github.com/user-attachments/assets/a2892bf6-769a-479d-9c63-9a6dbb7f2b54)

**To Reproduce**
1. See error at https://data-catalogue-acc.molgeniscloud.org/testNetwork/tables/#/Resources

OR:
1. Go to https://emx2.dev.molgenis.org/apps/central/#/
2. Create new database with template DATA_CATALOGUE_NETWORK_STAGING
3. Go to the newly made staging area and try to open the Resources table

**Expected behavior**
I want to be able to view the Resources table in the network staging area.

**Comment by BrendaHijmans** [comment]
Resources.resources refers to the catalogue Resources table. This is by design, we need to be able to express from a staging area of a network which resources are involved.

**Comment by mswertz** [comment]
Cannot reproduce on https://emx2.dev.molgenis.org/catalogue-demo/tables/#/Resources
