### ISSUE TITLE
Cannot enter admin area from menu when signed in as admin

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#431]
**What version of EMX2 are you using (see footer)**
8.0.2 and 7.6.1

**Describe the bug**
Cannot enter admin area from menu when signed in as admin, see screen shot: 
<img width="960" alt="admin_error" src="https://user-images.githubusercontent.com/42644481/129028175-915add56-756e-4dde-93f0-001a3acc0541.png">

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'
2. Sign in as admin
3. Click on Admin in menu

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win 10
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by connoratrug** [comment]
`{
  "errors" : [
    {
      "message" : "Error: Validation error of type FieldUndefined: Field '_admin' in type 'Query' is undefined @ '_admin'"
    }
  ]
}`
