### ISSUE TITLE
some types are shown incorrectly on catalogue startpage as 'resources'

### ISSUE THREAD

**Issue by mswertz** [molgenis/molgenis-emx2#4342]
Actual:

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/eeb6ed7b-a507-45a8-95e1-f7f5b5225c06">

Expected:

clinical trials and common data elements are shown.

Note: fall back should not be 'resources' but should be the type name.

**Comment by EleanorHyde-UMCG** [comment]
We need to check numbers given under each CTA because at the moment the first 'resources' CTA says '3' but there are 924 items in the list behind the CTA.
