### ISSUE TITLE
Building the software results in db changes 

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#435]
**What version of EMX2 are you using (see footer)**
8.x

**Describe the bug**
When i run the gradle build command the e2e tests get run these update the database ( reset admin pw)

**To Reproduce**
initialise app with given admin PW as described in the docs
(re)build the jar using gradle
run the app again 
login as admin using the given admin pw

**Expected behavior**
succesfull admin login using PW as set during initialisation

**Comment by mswertz** [comment]
e2e test indeed change the admin password, I assumed e2e would never be run on production machine. So I am a bit torn if we should call this a 'bug'. More importantly, how important is this in view of our time? We can suffice with a note in the docs?

Primary motivation is that currently emx2 can have only 1 admin user called 'admin' and to run tests validating web services that are 'admin-only' we needed to sign in using proper password. 

See https://github.com/molgenis/molgenis-emx2/blob/master/backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java

Now, with some hassle I assume we can change the software so we can do the sign in and sign out server side and then bypass the sign in step. Or we can implement JWT and use those.

**Comment by connoratrug** [comment]
_"@connoratrug are you using the environment variable MOLGENIS_ADMIN_PW for the password? Then we could update the tests to use that password to retrieve the passwords in the test without needing to change it?"_ yes that would be better , still think test should clean up after themselves, and leave db in the state it was found.

**Comment by mswertz** [comment]
I actually often use the test output for interactive tests whilst developing. So I don't like the 'cleanup' option because it would destroy my developer experience. 

Meanwhile, I think the 'changes admin password' still qualifies as a bug then needs fixing so that I would make scope of this story.
