### ISSUE TITLE
fix(catalogue): correction of the yy-mm-dd date format into yyyy-yyyy for start/end years needs to be carried out on the collection event, too

### ISSUE THREAD

**Issue by EleanorHyde-UMCG** [molgenis/molgenis-emx2#4367]
testplan 5, step 48
1. go to https://data-catalogue-acc.molgeniscloud.org/testCatalogue/ssr-catalogue/all/cohorts/testCohort2
2. scroll down to collection events
3. click on test collection event for cohort 2
4. see that the start/end year is still in yy-mm-dd format.

This needs to be in yyyy-yyyy format.

**Comment by EleanorHyde-UMCG** [comment]
@BrendaHijmans did you say that there are different date formats used for different types of resource? We should conform to whatever is the 'norm' for collection events. Do you know what that is?

**Comment by BrendaHijmans** [comment]
Why are we changing a date that is filled out into year? We made a deliberate choice to include start and end date into the collection events and end year/start year for resources. Data collection period may be more precisely recorded than the start/end of a resource.

**Comment by EleanorHyde-UMCG** [comment]
Let's keep it with full dates, then. The only reason this came up was that in another resource (cohort level?) the date presentation was changed wth the new data model and so for me it was the question whether the collection event, too, needed to be changed in line with that. That question has now been answered. We'll keep this as it is.
