### ISSUE TITLE
Catalogue variable explorer harmonisation overview tab route 

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#438]
**What version of EMX2 are you using (see footer)**
8.2.2

**Describe the bug**
No harmonization grid is shown when selecting the tab

**To Reproduce**
Got the the variable explorer 
Select the harmonization tab

**Expected behavior**
Harmonizaton grid is shown for variables with in selection

**Comment by mswertz** [comment]
thank your for spottings. seems urgent.

**Comment by connoratrug** [comment]
Turn out to be a config error specific to 
https://data-catalogue.molgeniscloud.org/

page for explorer app was set to

`../catalogue/#/variable-explorer/` 

should be 
`../catalogue/#variable-explorer`
