### ISSUE TITLE
fix(Jobs & Scripts): Disabling of a Task does not work, still able to run script

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#4388]
**What version of EMX2 are you using (see footer)**
v11.23.0

**Describe the bug**
Disabling a Task (Jobs & Scripts) does not work. The script is still able to run.

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/erik-test/tasks/#/scripts'
2. Click on 'The pencil to edit the `hello world` Script'
3. Set disable to *true* and save
4. Back on 'https://emx2.dev.molgenis.org/erik-test/tasks/#/scripts' click on the play button

**Expected behavior**
I would expect a message telling me I can not run this script because it has been disabled.

**Screenshots**
![image](https://github.com/user-attachments/assets/83e8b1a9-e01c-4660-a533-bbed0ba53924)

![image](https://github.com/user-attachments/assets/9a5a64d8-3342-4076-a13b-99a926cbc5a9)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser [brave]
 - Version [1.71.114]

**Comment by dtroelofsprins** [comment]
I thought disable=true would not start cron when scheduled, but manual start is still possible (as you describe). However the manual indeed says differently:
![image](https://github.com/user-attachments/assets/5d3c3203-b8e5-4da7-81fe-bfe1c14d8d25)

**Comment by erikzwart** [comment]
I just tested and indeed if disabled = true then the cronjob is not executed with a set cron schedule.

The manual text needs to change to something like:
`disabled, when set to true the script will not run if a cron schedule is set`
