### ISSUE TITLE
I want to be able to change the order in which data items appear in forms

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#440]
**Is your feature request related to a problem? Please describe.**
For the catalogue data model we use 'abstract' tables (such as Resources) that are used as a blue print for other tables (such as Cohorts). All data items of Resources are inherited by Cohorts, and the order of the data items is first all items of Resources and then all items of cohorts in the order in which they appear in the molgenis.csv. In Cohorts there are some specific data items that need to appear more at the top of the forms, otherwise the flow of data entry is disturbed.

**Describe the solution you'd like**
Option 1: Change the order in which the items appear in forms.
Option 2: Get rid of 'abstract' tables (this will have an impact on the data model though, since Resources are used to link Releases to Variables).

**Describe alternatives you've considered**

**Additional context**

**Comment by mswertz** [comment]
I fully agree. Would be great.

How about proposal below @BrendaHijmans ? 

Proposal: The user interface will show columns in the order that you imported them.

For example: given molgenis.csv:
```
tableName,tableExtends,columnName,key,description
shape,,,,root class is shape that has general properties
square,shape,,,special shape that has sidelength
circle,shape,,,special shape that has radius
shape,,name,1,should be first column in all shapes
square,,sidelength,,should be second column in square
circle,,radius,,should be second column in circle
shape,,description,,all shapes have description, should be last column in all shapes in this schema
```

Then you would have
* shape: name,description
* cirlcle: name,radius,description
* square: name, sidelength, description

Of course, during export this order would be maintained for next import.
And we need to change the 'schema editor' user interface to show 
* one dialogue for table inheritance tree
* one list of columns for all subclasses so you can indicate overall order
* with the option to indicate if a column is part of the 'root' of the inheritance tree or of a subclass

**Comment by mswertz** [comment]
BTW, alternative solutions:

1. add a 'position' column to emx2 format (which actually exists in the software) and use that for sorting
2. if you want to do per table different column order, allow a 'order' column in emx2 format where you can list the columns again, but then in the order you like. E.g. order=radius,name,description
