### ISSUE TITLE
design(catalogue): Network information page doesn't show resources or variables - spec required

### ISSUE THREAD

**Issue by hslh** [molgenis/molgenis-emx2#4415]
**What version of EMX2 are you using (see footer)**
v11.25.0

**Describe the bug**
The network information page (e.g. /all/networks/ATHLETE) doesn't show the resources and variables which are part of the network. It used to show cohorts, data sources, variables. 

**To Reproduce**
1. Go to 'https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/ATHLETE/networks/ATHLETE'
2. See that a list of cohorts and a link to the variable explorer are shown
3. Go to 'https://data-catalogue-acc.molgeniscloud.org/catalogue/ssr-catalogue/ATHLETE/networks/ATHLETE'
4. See that neither cohorts (now: resources) nor a link to the variable explorer are shown.

**Expected behavior**
The network information page shows a list of resources, similar to the mock-up screenshot below and have a link to the variable explorer (filtered on the network). Since networks are resources, I assume this should also apply for other types of resources? (which can contain resources themselves)

**Screenshots**
![Screenshot 2024-10-31 at 10 12 40](https://github.com/user-attachments/assets/c95a98e0-5a11-486e-b1cd-992ed467d19b)

Mock-up of a list of resources for the network information page, based on the list of cohorts shown previously. 

**Desktop (please complete the following information):**
 - MacOS Sequoia, Firefox 131

**Additional context**
More examples: 
https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/all/networks/BBMRI-ERIC 
vs. 
https://data-catalogue-acc.molgeniscloud.org/catalogue/ssr-catalogue/all/networks/BBMRI-ERIC 

&

https://data-catalogue.molgeniscloud.org/testCatalogue/ssr-catalogue/testNetwork1/networks/testNetwork1 
vs. 
https://data-catalogue-acc.molgeniscloud.org/testCatalogue/ssr-catalogue/testNetwork1/networks/testNetwork1

**Comment by BrendaHijmans** [comment]
@mswertz: you mentioned this was a deliberate choice? Can the issue be closed?

**Comment by hslh** [comment]
Blocked on #4477

**Comment by EleanorHyde-UMCG** [comment]
gedekt door #4477
