### ISSUE TITLE
Year 0 harmonisation details check mark is displayed while there is no data for this mapping

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#4428]
**What version of EMX2 are you using (see footer)**
v11.25.2

**Describe the bug**
Year 0 harmonisation details are not displayed in variable harmonisations detail view.

**To Reproduce**
1. Go to https://data-catalogue-acc.molgeniscloud.org/testCatalogue/ssr-catalogue/testNetwork1/
2. Click on Variables
3. Click on testVarRepeats_
4. See in harmonisation matrix ('Harmonisation status per data source') that Year 0 to Year 10 are present (so 11 variables) and that testCohort 1 has harmonised Year 0 to Year 10
5. Go to the underlying data: https://data-catalogue-acc.molgeniscloud.org/testCatalogue/tables/#/VariableMappings
6. Search for testVarRepeats. 
7. See that there is no mapping to year 0 for testCohort1 for testVarRepeats

**Comment by hslh** [comment]
Okay, we'll have to fix this in test data then at some point.

**Comment by BrendaHijmans** [comment]
Hmm, then the bug is the other way around: the check mark for testCohort1 for Year 0 should not be shown in the harmonisation matrix
![image](https://github.com/user-attachments/assets/cce7ee8f-5ae9-4ca3-b760-02e4455abe1a)
