### ISSUE TITLE
Error message when wanting to display data about an individual cohort

### ISSUE THREAD

**Issue by EleanorHyde-UMCG** [molgenis/molgenis-emx2#471]
**What version of EMX2 are you using (see footer)**
8.6.1

You get an error message when you want to display the data about an individual cohort.

**To Reproduce**
1. Go to https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/
2. Click on Cohorts
3. Click on a cohort in the list
4. See error "Error: Validation error of type FieldUndefined: Field 'dataCategories' in type 'CollectionEvents' is undefined @ 'Cohorts/collectionEvents/dataCategories'"

**Expected behavior**
No error message, and presentation of the relevant data in the fields below for the cohort chosen.

**Screenshots**
[20210825 individuele cohort bekijken.docx](https://github.com/molgenis/molgenis-emx2/files/7048352/20210825.individuele.cohort.bekijken.docx)

**Desktop (please complete the following information):**
 - OS: Microsoft
 - Browser Chrome
 - Version ??

**Additional context**

**Comment by EleanorHyde-UMCG** [comment]
A very similar issue (but not identical) occurs in the Conception catalogue when viewing an individual data source or data bank. 

Data source: "Error: Validation error of type SubSelectionNotAllowed: Sub selection not allowed on leaf type String of field inclusionCriteria @ 'Datasources/inclusionCriteria'"
Data bank: "Error: Validation error of type SubSelectionNotAllowed: Sub selection not allowed on leaf type String of field keywords @ 'Databanks/keywords'"

**Comment by mswertz** [comment]
fixed in #460
