### ISSUE TITLE
As emx2 server owner I would like users to directly go from URL to the database in question and not being distracted by other databases

### ISSUE THREAD

**Issue by mswertz** [molgenis/molgenis-emx2#477]
Ideal situation: I can link a URL to a specific database (so I can have multiple databases on one server)

Second best: I can give a default database so users will bypass the 'databases' list and go directly to the database I intend to share.

In both cases, we will remove the 'databases' from the breadcrumb 

Example use case: as LongITools I would like short URL 'http://catalogue.longitools.eu' that immediately shows the catalogue landing page.

**Comment by esthervanenckevort** [comment]
This has been solved by setting the LANDING_PAGE property.
