### ISSUE TITLE
Link to VariableMappings is not working

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#507]
**What version of EMX2 are you using (see footer)**
8.9.2

**Describe the bug**
In the catalogue app, the tile 'VariableMappings' does not refer to Variable Mappings, link is https://emx2-conception.test.molgenis.org/ConcePTION/tables/#/Variables; or in test; https://emx2.test.molgenis.org/UMCG%20Data%20Catalogue/catalogue/#/explorer

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'
2. Click on ConcePTION
3. Click on Catalogue
4. Click on VariableMappings

**Expected behavior**
I expect to go to VariableMappings

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
should have linked to variable-explorer. fixed in #460
