### ISSUE TITLE
Tables with ontology_arrays are not loaded

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#511]
**What version of EMX2 are you using (see footer)**
8.9.2, 8.9.0

**Describe the bug**
When uploading model with data the data in tables that contain a columnType ontology_ref are not loaded. 
Data file: 
[UMCG Data Catalogue1630491505185.xlsx](https://github.com/molgenis/molgenis-emx2/files/7092373/UMCG.Data.Catalogue1630491505185.xlsx)

In the upload interface it seems that the data is loaded, see image, Subcohorts and CollectionEvents
![image](https://user-images.githubusercontent.com/42644481/131697658-2caf558b-5e5e-47e4-ab7c-9142699e9b4a.png)
But error are present when navigating to those tables via Tables,
![image](https://user-images.githubusercontent.com/42644481/131697808-9d84a723-8c8e-4a2c-b679-936a0e3217a8.png)
 and the data is not there in forms: 
![image](https://user-images.githubusercontent.com/42644481/131698150-c8a75472-687d-4b8a-a5af-aa48039a4bc8.png)

When I change the ontology_ref to ref_array in the datamodel, the data is loaded correctly.

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
fixed in #502
