### ISSUE TITLE
No variables shown in variable explorer 

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#546]
**What version of EMX2 are you using (see footer)**
8.15.1

**Describe the bug**
No variables are listed

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/catalogue/catalogue/#/variable-explorer/'
2. See error, no variables

**Expected behavior**
List of variables

**Comment by mswertz** [comment]
duplicate
