### ISSUE TITLE
email does not fit in field

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#549]
**What version of EMX2 are you using (see footer)**
8.15.1

**Describe the bug**
email form field is to small for 'normal' email to fit

**To Reproduce**
1. Go to settings ( as admin )
2. Add a user , try to copy paste email adres

**Expected behavior**
Email adres to be added is readable ( fit the field) ( and basic email validation) 

**Screenshots**
![Screenshot 2021-09-15 at 14 46 27](https://user-images.githubusercontent.com/47183404/133436209-5d155cfe-082d-428b-aaf9-031be4f98911.png)

**Comment by mswertz** [comment]
well, there is more wrong here. We currently treat this as username so it doesn't need to be an email. Would like to have functional discussion between us if we want to force user names to be email addresses?

**Comment by mswertz** [comment]
Proposed action: make it bigger and change to EmailInput

**Comment by MaxPostema** [comment]
Fixed by: https://github.com/molgenis/molgenis-emx2/pull/2684
