### ISSUE TITLE
Trying to log into the catalogue anywhere but in the root gives an error message

### ISSUE THREAD

**Issue by EleanorHyde-UMCG** [molgenis/molgenis-emx2#550]
**What version of EMX2 are you using (see footer)**
8.9.2

**Describe the bug**
Trying to enter a catalogue for which you've not yet logged in anywhere other than in the root gives an error message rather than letting you log in.

**To Reproduce**
1. make sure you're logged out of the catalogue you're going to test
2. Use the link to eg the tables page, eg: https://emx2-conception.test.molgenis.org/ConcePTION/tables/#/
3. Get error message
4. The only workaround is to log into https://emx2-conception.test.molgenis.org/ and then go to where you wanted to go.

**Expected behavior**
I would expect to get the normal login page, be able to log in and then be brought straight to the page I'd typed in in the address bar

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
[20210915 login error.docx](https://github.com/molgenis/molgenis-emx2/files/7170224/20210915.login.error.docx)

**Comment by mswertz** [comment]
fixed in current version.

**Comment by EleanorHyde-UMCG** [comment]
yep, tested in Minerva and Conception and it looks to be fixed, thanks
