### ISSUE TITLE
As data base editor it look like i can upload a schema

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#551]
**What version of EMX2 are you using (see footer)**
8.15.1

**Describe the bug**
As editor it looks like i can upload a schema

**To Reproduce**
1. Log in with editor role
2. Select Up/Download
3. Up load a schema

**Expected behavior**
Expect the upload option to be hidden or blocked 

**Screenshots**
![Screenshot 2021-09-15 at 15 13 35](https://user-images.githubusercontent.com/47183404/133439825-99c2bd15-d47a-45fc-b440-420feeda3474.png)

**Comment by mswertz** [comment]
very curious how you ended up here? because indeed, if you are not an 'editor' then you should not see the upload option. Might it be you signed out in another screen?

**Comment by mswertz** [comment]
cannot reproduce
