### ISSUE TITLE
When signing-in be able to use tab (once) to go to password field and use enter (keyboard) to sign in

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#552]
When signing into molgenis as a user I would like to use [tab] to go to the next input field (password) instead of selecting cross (see attached screenshot). Also if username and password are filled in I would like to be able to press [enter] instead of clicking on 'sign in'.

**Additional context**
![molgenis-login-menu](https://user-images.githubusercontent.com/4077085/133439861-01e1888d-50e6-4b98-88d9-cf447c5b2dd0.png)

**Comment by chinook25** [comment]
Tabbing fixed in https://github.com/molgenis/molgenis-emx2/pull/1011
Enter to login added with https://github.com/molgenis/molgenis-emx2/pull/973
