### ISSUE TITLE
In Conception I can't view an individual datasource or databank

### ISSUE THREAD

**Issue by EleanorHyde-UMCG** [molgenis/molgenis-emx2#557]
**What version of EMX2 are you using (see footer)**
8.9.2

**Describe the bug**
If I view an individual datasource or an individual databank I get an error message and the fields are not filled.
Possibly related to bug #471?

**To Reproduce**

DATASOURCE
1. Go to https://emx2-conception.test.molgenis.org/ConcePTION/catalogue/#/datasources
2. Click on an individual datasource
3. See error

DATABANK
1. Go to https://emx2-conception.test.molgenis.org/ConcePTION/catalogue/#/databanks
2. Click on an individual databank
3. See error

**Expected behavior**
The individual datasource or databank is displayed with the correct fields filled, with no error message.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Chrome
[20210916 error message with individual databank or datasource in Conception.docx](https://github.com/molgenis/molgenis-emx2/files/7177746/20210916.error.message.with.individual.databank.or.datasource.in.Conception.docx)

**Comment by mswertz** [comment]
@EleanorHyde-UMCG please always ask data managers to first update server to latest version before you do testing. Otherwise you waste your own time reporting bugs that have been meanwhile fixed
