### ISSUE TITLE
Catalogue Studies details not shown

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#559]
**What version of EMX2 are you using (see footer)**
8.15.1

**Describe the bug**
From the Catalogue page I select the Studies, when clicking to see their details I see an empty page

**To Reproduce**
1. Go to 'https://minerva.molgeniscloud.org/Minerva/catalogue/#/'
2. Click on 'Studies' see screenshot yellow circle
3. Select any of the Studies and click to see details
4. empty page is shown

**Expected behavior**
I expect to see the details of the selected Studie(s)

**Screenshots**
Overview
![molgenis-catalogue-studies](https://user-images.githubusercontent.com/4077085/133617196-dce8fb1c-ff83-458e-89d0-c4f6544a4f97.png)
Detail view
![molgenis-catalogue-studies-empty](https://user-images.githubusercontent.com/4077085/133617241-ecf962f5-b68c-4b1d-93c4-c656c5b14001.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser Chomium
 - Version 93.0.4577.82

- Browser Firefox
- Version 92.0

**Comment by mswertz** [comment]
close in pull request #586
