### ISSUE TITLE
Catalogue variable mappings: variable-explorer reports no results

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#560]
**What version of EMX2 are you using (see footer)**
8.15.1

**Describe the bug**
variable-explorer is empty

**To Reproduce**
1. Go to 'https://minerva.molgeniscloud.org/Minerva/catalogue/#/'
2. Click on 'variable mappings' (see screenshot)
3. variable-explorer is empty

**Expected behavior**
Expect to see details of variable mappings 

**Screenshots**
Catalogue
![molgenis-catalogue-variable-mappings](https://user-images.githubusercontent.com/4077085/133618964-c2359f70-9c5c-4ad4-b056-d9157e896348.png)

variable-explorer
![molgenis-catalogue-variable-mappings-empty](https://user-images.githubusercontent.com/4077085/133619036-2c62d24b-a240-4294-adee-86e2622c53d5.png)

**Desktop (please complete the following information):**
- OS: ubuntu 20.04
- Browser Chomium
- Version 93.0.4577.82

- Browser Firefox
- Version 92.0

**Comment by mswertz** [comment]
has been fixed in 8.17.1

**Comment by mswertz** [comment]
relates to story in trac https://trac.molgeniscloud.org/ticket/8523 and pull request #545
