### ISSUE TITLE
CONCEPTION When wanting to view an individual study, I get an empty screen

### ISSUE THREAD

**Issue by EleanorHyde-UMCG** [molgenis/molgenis-emx2#562]
**What version of EMX2 are you using (see footer)**
8.15.1

**Describe the bug**
After clicking on an individual study in the list of studies behind the 'Studies' block on the dashboard, I get an empty screen.

**To Reproduce**
1. Go to https://conception-acc.molgeniscloud.org/Conception/catalogue/#/
2. Click on Studies
3. Click on an individual study in the list
4. Get an empty page

**Expected behavior**
You should get a page with the information for the individual study.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by EleanorHyde-UMCG** [comment]
screenshot vergeten
[20210917 leeg scherm met individuele study.docx](https://github.com/molgenis/molgenis-emx2/files/7185333/20210917.leeg.scherm.met.individuele.study.docx)

**Comment by erikzwart** [comment]
Same issue: #559
