### ISSUE TITLE
Download and upload cohort

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#564]
**What version of EMX2 are you using (see footer)**
 8.15.1

**Describe the bug**
Uploading downloaded records fails 

**To Reproduce**
1. Upload catalogue model
2. Add a cohort record
3. Download the cohorts via the api/csv endpoint
4. make small change
4. Upload the cohorts via the api/csv endpoint

**Expected behavior**
Records are uploaded , en user is given error about duplicate rows 

**Additional context**

`Upsert into table 'Cohorts' failed.: Transaction failed: column 'pid' is required in ROW(cc8a556808d1a484535b7048c2640e36='Content-Disposition: form-data; name="file"; filename="data3.csv"' mg_tableclass='UMCG.Cohorts' )
`
[data3.csv](https://github.com/molgenis/molgenis-emx2/files/7186244/data3.csv)

**Comment by connoratrug** [comment]
Issue seems to that the api does not no how to extract the csv from the request, nor do the api docs state how the request should be formated.

![Screenshot 2021-09-17 at 16 54 06](https://user-images.githubusercontent.com/47183404/133803855-3d3f4081-3405-45d5-894e-bcb63b3fdfe0.png)
t

**Comment by mswertz** [comment]
should be fixed in #592
