### ISSUE TITLE
Download results in empty file

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#570]
**What version of EMX2 are you using (see footer)**
8.15.2

**Describe the bug**
Downloading the resource table results in empty csv

**To Reproduce**
1. Load molgenis catalogue model into 8.15.2 version 
2. Create set of resources row 
3. download as zip
4. extract zip
5. view csv file, it's empty

**Expected behavior**
csv file with rows created in step 2

**Comment by mswertz** [comment]
that is how it should be right? if you only have values in subclass tables than this should be empty?
