### ISSUE TITLE
Transaction failed: null while creating new database

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#571]
**What version of EMX2 are you using (see footer)**
8.15.1

**Describe the bug**
Error while creating new database, but database schema is created fine. See screenshots

**To Reproduce**
1. Go to 'https://emx2-conception.test.molgenis.org/apps/central/#/'
2. Click on 'plus sign to create new database'
3. Fill in a name and click 'create database' 
4. See error in screenshot

**Expected behavior**

**Screenshots**
after creating new database
![create-database_8 15 1-error](https://user-images.githubusercontent.com/4077085/133984442-1b064537-d117-40f9-9cb6-ff66c2ad7b68.png)

after clicking close
![create-database_8 15 1-error-1](https://user-images.githubusercontent.com/4077085/133984338-f7119d98-f187-47d9-b1b3-b76683f1704e.png)
**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser chromium
 - Version 93.0.4577.82

**Additional context**
This issue is not consistent and happens what seems to be at random try's

**Comment by mswertz** [comment]
what I notice is that this happens if you act very fast. When you wait a sec before you create this doesn't seem to happen. Did you observe same?

**Comment by mswertz** [comment]
Can't reproduce in [8.189.2](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.189.2)
