### ISSUE TITLE
File download when clicking on menu item

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#584]
**What version of EMX2 are you using (see footer)**
8.15.1, also on dev (8.15.6-SNAPSHOT)

**Describe the bug**
When I click on 'Databases' in the menu, an empty file 'tables' is downloaded.
![image](https://user-images.githubusercontent.com/42644481/134671915-b3c9d4cc-11bf-479b-aae4-cc0e739e885b.png)

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/apps/central/#/'
2. Click on 'Databases'
3. A file is downloaded

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by erikzwart** [comment]
Same as: #547
