### ISSUE TITLE
download fails to download all rows

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#590]
**What version of EMX2 are you using (see footer)**
8.16.1

**Describe the bug**
Download table data , not all rows are downloaded

**To Reproduce**
1. Go to 'https://catalogue-acc.molgeniscloud.org/'
2. UMCG
3. go to download ( download as exel) 
4. view downloaded sheets, look at Regions sheet and compare with the data in the app 
5 the row "The Netherlands" is not part of the download

**Expected behavior**
All rows are downloaded

**Comment by connoratrug** [comment]
note: csv download does contain all the rows

**Comment by mswertz** [comment]
might be related to #594

**Comment by mswertz** [comment]
I cannot reproduce.
