### ISSUE TITLE
Unable to upload inheritance trees when subtrees have same identifier

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#594]
**What version of EMX2 are you using (see footer)**
8.15.1

**Describe the bug**
Unable to add OntologyTerms item

Multiple tables like DatabankFamilies, InstitutionRoles, PopulationEntryCauses, etc. store there values in OntologyTerms. The issue now is that I want to be able to add ‘other’ to DatabankFamilies and InstitutionRoles. This will not work because I can not add this value ‘other’ twice, see error message.

The situation now is that I can define ‘other’ one time for the table DatabankFamilies for instance and not use ‘other’ for any different table like InstitutionRoles.. 

**To Reproduce**
1. Go to 'https://minerva.molgeniscloud.org/'
2. Go to 'DatabankFamilies'
3. And add new item 'other'

**Expected behavior**
Be able to either select 'other' from a list of already defined OntologyTerms or be able to add 'other' and make sure the error does not occur.

**Screenshots**
![molgenis-dup-OntologyTerms](https://user-images.githubusercontent.com/4077085/135058079-acd695cb-f01d-40ab-bb78-57bd271c3932.png)

![molgenis-ontology-terms](https://user-images.githubusercontent.com/4077085/135058173-17430d16-4f2a-4a6b-95a9-858cd74cf3fa.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser chromium
 - Version 93.0.4577.82

**Additional context**

**Comment by mswertz** [comment]
I want to fix this by changing implementation of ontology terms. Clearly, we now see it was a bad idea to have them inherit from same base table. 

Two functional solutions I have in mind:
* autogenerate table in case of ontology or ontology_array => so then DM doesn't need to do anything (prefered)
* alternatively, we could make composite key of mg_tableclass,name
