### ISSUE TITLE
Current Catalogue model gives error when loaded twice

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#595]
**What version of EMX2 are you using (see footer)**
8.16.0

**Describe the bug**

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/'
2. Load the current catalogue datamodel:  [molgenis.csv](https://github.com/molgenis/molgenis-emx2/files/7250419/molgenis.csv)
3. Try to load it another time
4. See error: 
![image](https://user-images.githubusercontent.com/42644481/135236991-32135f8b-0b9f-4639-8099-b24bde082631.png)

**Expected behavior**
Data model should load again without issues.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
should be fixed in https://github.com/molgenis/molgenis-emx2/pull/592
