### ISSUE TITLE
rows per page option should not include 'null'

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#596]
**What version of EMX2 are you using (see footer)**
8.16.0

**Describe the bug**
Should not show 'null' in option list for rows per page

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/pet%20store/tables/#/Order
2. Click on 'Rows per page'
3. select the top 'empty' option

**Expected behavior**
cannot select error option

**Screenshots**
![molgenis-rows-per-page](https://user-images.githubusercontent.com/4077085/135288895-f75c7c68-a3b5-4bd5-a0f2-3b77fde3aded.png)

**Comment by mswertz** [comment]
Should not be able to select that option.
