### ISSUE TITLE
adding databases with a # results in logging out

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#597]
**What version of EMX2 are you using (see footer)**
8.16.0

**Describe the bug**
After adding a database with a hashtag: git#593 results in being logged out and unable to see the database

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/apps/central/#/'
2. Click on '+'
3. Enter a name with # like git#593
4. see screenshot

**Expected behavior**
Not able to enter # or it should be escaped as special character

**Screenshots**
![molgenis-createdb-hashtag-1](https://user-images.githubusercontent.com/4077085/135296985-a811b1f7-597d-4b78-8e8f-b3b91482178f.png)
![molgenis-createdb-hashtag-2](https://user-images.githubusercontent.com/4077085/135297013-ecb17768-5adf-4086-a2a2-8773608573ae.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser chromium
 - Version 93.0.4577.82

**Comment by mswertz** [comment]
proposal to forbid # in name, agreed?
