### ISSUE TITLE
Theme settings are only visible after a couple of clicks through the catalogue

### ISSUE THREAD

**Issue by EleanorHyde-UMCG** [molgenis/molgenis-emx2#622]
**What version of EMX2 are you using (see footer)**
8.15.1

**Describe the bug**
When I log into the Conception catalogue, I see the new logo straight away but the theme only changes to the correct colour after a couple of clicks through the catalogue.

**To Reproduce**
1. Go to https://conception-acc.molgeniscloud.org/Conception/catalogue/#/
2. Log in
3. See that the logo is visible but the new theme not yet.
4. Click on Institutions.
5. See that the colour theme doesn't change.
6. Click on Catalogue in the top ribbon.
7. See that the colour theme then changes.

**Expected behavior**
The logo and colour theme should be visible as soon as login has been completed. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
[20211007 logo and theme.docx](https://github.com/molgenis/molgenis-emx2/files/7299942/20211007.logo.and.theme.docx)

**Comment by connoratrug** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Theme settings are only visible after a couple of clicks through the catalogue #622](https://trello.com/c/VcBBi1KE/298-theme-settings-are-only-visible-after-a-couple-of-clicks-through-the-catalogue-622)
