### ISSUE TITLE
Error while fetching data after loging in

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#639]
**What version of EMX2 are you using (see footer)**
8.15.1

**Describe the bug**
After logging in as admin I get the following error:
Error: Exception while fetching data (/_schema) : null

**To Reproduce**
1. Go to 'https://minerva.molgeniscloud.org/Minerva/tables/#/'
2. Log in as admin
3. Error will appear at seeming random try's

**Expected behavior**
I expect to see the Data Catalogue

**Screenshots**
![molgenis-login-data-schema-missing](https://user-images.githubusercontent.com/4077085/137127587-978fd5e6-97c9-4013-8c27-4b8c7e4fe0d1.png)

**Desktop (please complete the following information):**
 - OS:ubuntu 20.04
 - Browser chromium
 - Version 94.0.4606.81

**Comment by mswertz** [comment]
cannot reproduce in 8.33 using https://minerva.molgeniscloud.org/Minerva/
