### ISSUE TITLE
catalogue radio button true/false options are not shown in datasources and databank details

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#646]
**What version of EMX2 are you using (see footer)**
8.20.5

**Describe the bug**
While editing or updating a datasource or databank the true or false options like 'accessSubjectDetails' or not shown in the datasources/databanks detail overiew

**To Reproduce**
1. Go to 'https://minerva.molgeniscloud.org/Minerva/catalogue/#/datasources'
2. Click on 'pencil to edit datasource'
3. edit 'accessSubjectDetails' to TRUE
4. Save datasources
5. Click on the Datasources you just edited and you will notice accessSubjectDetails is missing

**Expected behavior**
Expect to see the TRUE value I just added

**Screenshots**

![molgenis-8 20 5_true-false_radio_1](https://user-images.githubusercontent.com/4077085/137297766-9ffe6b27-3a01-4050-be55-5ddba6a7789d.png)

![molgenis-8 20 5_datasource-detail](https://user-images.githubusercontent.com/4077085/137297779-c589f47c-e280-4924-9a10-b0154db0d2f5.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser chromium
 - Version 94.0.4606.81

**Comment by connoratrug** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix 646 boolean not shown of false in resource detail view](https://trello.com/c/WzXq3hLv/309-fix-646-boolean-not-shown-of-false-in-resource-detail-view)
