### ISSUE TITLE
catalogue radio button true is saved but false is not in datasources and databank

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#647]
**What version of EMX2 are you using (see footer)**
8.20.5

**Describe the bug**
While editing datasources or databanks and setting a true/false field like 'accessSubjectDetails' to TRUE and saving the datasource, the true value is saved. In contrast to setting the value of 'accessSubjectDetails'  to FALSE, this value is not stored.

**To Reproduce**
1. Go to 'https://minerva.molgeniscloud.org/Minerva/catalogue/#/datasources'
2. Click on 'pencil to edit'
3. Set the value 'accessSubjectDetails' to FASLE and save
4. Click on the pencil to edit again.
5. The value accessSubjectDetails of not saved (emptt)

**Expected behavior**
Value FALSE should be saved

**Screenshots**
Set as TRUE and saved
![molgenis-8 20 5_true-false_radio_1](https://user-images.githubusercontent.com/4077085/137312720-847ae8c3-e786-4ab5-9189-f509728be9cd.png)

Set as FALSE
![molgenis-8 20 5_true-false_radio_2](https://user-images.githubusercontent.com/4077085/137312753-17fa1b97-94cc-4606-a61b-54078112ddf0.png)
Not saved
![molgenis-8 20 5_true-false_radio_3](https://user-images.githubusercontent.com/4077085/137312775-162e3422-2d09-4b94-8429-a75b35b4408a.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser chromium
 - Version 94.0.4606.81

**Comment by connoratrug** [comment]
fixed in: https://github.com/molgenis/molgenis-emx2/pull/1606

**Comment by connoratrug** [comment]
fixed in 8.121.x
