### ISSUE TITLE
In forms in staging areas you can click on edit of a Table that you have only viewing rights for

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#650]
**What version of EMX2 are you using (see footer)**
8.20.5

**Describe the bug**
In staging areas you can refer to tables in another Schema for which you only have viewing rights. When entering data via forms you are allowed to click on the plus sign in those tables.
![image](https://user-images.githubusercontent.com/42644481/137483539-160b5a92-12e9-4907-86db-88b32fd04e15.png)
![image](https://user-images.githubusercontent.com/42644481/137483664-d92e8791-b19f-4c61-961a-023487e44f58.png)
you can enter information, but you cannot save (which is good).
![image](https://user-images.githubusercontent.com/42644481/137483805-d40b7c0f-962f-446a-b0c6-ff506ca93c50.png)

It would be better if you cannot click on the plus sign at all. The plus sign can be absent or you can receive a well-readable warning that you do not have editing rights.

**To Reproduce**
1. Go to 'https://catalogue-acc.molgeniscloud.org/'
2. Log in as admin and give yourself editing rights as a test user on schema test_staging
3. Log in as test user
4. Add a cohort via forms. See the issue described above.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chinook25** [comment]
Additionally, if the user does not have viewing rights on the second schema, the user can't even view the schema they have editing rights on.
