### ISSUE TITLE
Unable to add database when petstore is removed

### ISSUE THREAD

**Issue by dijansen** [molgenis/molgenis-emx2#673]
**What version of EMX2 are you using (see footer)**
8.20.11

**Describe the bug**
Just removed the petstore database using the UI. I am now  unable to click '+' to add a new database.

**To Reproduce**
1. Go to MOLGENIS
2. Login as Admin
3. Delete all databases that are present
4. Now try to add a new one.

**Expected behavior**
I would expect to be able to create a new database :). 

**Screenshots**
![image](https://user-images.githubusercontent.com/5172261/138896496-430d0887-d40a-47d7-ac0c-41ad2a4640dd.png)

**Comment by mswertz** [comment]
yeah, this is a nice user interface bug :-)
