### ISSUE TITLE
Master CI test are unstable 

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#678]
**What version of EMX2 are you using (see footer)**
8.20.1

**Describe the bug**
Some times tests fail ( other times all tests succeed )

**To Reproduce**
CI run master build
(example: https://jenkins.dev.molgenis.org/job/molgenis/job/molgenis-emx2/job/master/630/)

**Expected behavior**
Consistently fail or succeed

**Comment by mswertz** [comment]
In #834 

![image](https://user-images.githubusercontent.com/120060/150435428-52fcdc93-6926-4fdf-83ad-05154eb32eb7.png)

**Comment by mswertz** [comment]
the same one again, somewhere a tx is missing

**Comment by mswertz** [comment]
This one again
<img width="662" alt="image" src="https://user-images.githubusercontent.com/120060/197540619-fad7abae-9428-49a7-a5fc-992a36d5821a.png">
