### ISSUE TITLE
Docs for cohort data manager in 'data access guide' and 'catalogue guide' point to same file

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#698]
**What version of EMX2 are you using (see footer)**
8.20.6

**Describe the bug**
Docs for cohort data manager in 'data access guide' and 'catalogue guide' point to same file. Both point to https://data-catalogue.molgeniscloud.org/apps/docs/#/cat_cohort-data-manager. 

**To Reproduce**
1. Go to 'https://data-catalogue.molgeniscloud.org/apps/docs/#/'
2. Click on 'Cohort/DAP data manager' under Catalogue guide and under Data access guide
3. See the same information under both, about catalogue upload, not about data access or data upload to Armadillo.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by erikzwart** [comment]
'data access guide'  seems to be renamed to Armadillo guide, I can not reproduce this behavior. Bug seems to be resolved
