### ISSUE TITLE
Minerva: some fields visible in edit mode are not displayed in display mode

### ISSUE THREAD

**Issue by EleanorHyde-UMCG** [molgenis/molgenis-emx2#731]
**What version of EMX2 are you using (see footer)**
8.27.0

**Describe the bug**
Various fields in Minerva are visible in EDIT mode of a data bank and data source but are INVISIBLE 
in display mode of the same resource, even if the fields have been filled in. Some are truncated in display mode (indicated with 'truncated'). This applies to the following fields:

DATA BANK
- Data bank countries (Databanks-Countries)
- Causes event triggering of population exit (Databanks-populationExit)
- Population coverage (Databanks-populationCoverage)  TRUNCATED
- Population coverage details (same field as above??)
- Data bank language (table unknown?)
- Sociodemographics included (RWEresources-areasOfInformation)
- Lifestyle factors included (all fields below are in RWEresources-areasOfInformation)
- Hospital admission discharge
- ICU admission
- ATMP
- Contraception
- Indication for use
- Medical devices
- Procedures included
- Clinical measures included
- Healthcare provider
- Patient-generated data
DATA SOURCE
- Data source countries (Datasources-Countries)
- Data source type (Datasources-Type)
- Data source type, Other (Datasources-typeOther)
- Linkage variable unique (DatasourceDatabanks-LinkageVariableUnique)

**To Reproduce**
Steps to reproduce the behavior:  (eg for the 'Databank Countries' problem)
1. Go to (https://minerva.molgeniscloud.org/Minerva/catalogue/#/databanks)
2. Select CPRD_GOLD in edit mode
3. See that the country United Kingdom has been filled in
4. Go out of CPRD_GOLD and go back in display-only mode 
5. See that the space next to "Countries" is empty.

**Expected behavior**
You would expect to see the information visible in Edit mode also to be visible in Display mode.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser Chrome
[20211117 voorbeeld weergave vs edit mode CPRD GOLD data bank countries.docx](https://github.com/molgenis/molgenis-emx2/files/7555516/20211117.voorbeeld.weergave.vs.edit.mode.CPRD.GOLD.data.bank.countries.docx)

**Comment by connoratrug** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bug fix: resource view](https://trello.com/c/gqJYuJJX/321-bug-fix-resource-view)
