### ISSUE TITLE
Text field scroll bar is as long as text field

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#732]
**What version of EMX2 are you using (see footer)**
8.27.0

**Describe the bug**
When a text field in forms contains a lot of text, a scroll bar appaears, but the scroll bar is as long as the text box is.
![image](https://user-images.githubusercontent.com/42644481/142235414-c89a7893-22ef-42f9-a712-b2bfe9557f9c.png)

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
so either the scrollbar should be removed (because text field grows with text) or should be usable. Which of the two do we prefer?
