### ISSUE TITLE
Minerva: some fields are truncated

### ISSUE THREAD

**Issue by EleanorHyde-UMCG** [molgenis/molgenis-emx2#735]
**What version of EMX2 are you using (see footer)**
8.27.1

**Describe the bug**
The following fields are truncated. Anyone with only viewing rights misses most of what has been filled in in the field.

Databank:
DatabankFamilies Other
PopulationEntry Other
PopulationExit Other
PopulationCoverage

**To Reproduce**
1. Go to https://minerva-acc.molgeniscloud.org/Minerva-acc/catalogue/#/databanks/eleanortestdatabank in edit mode
2. See the text in the fields listed above
3. Go to the same databank in display mode
4. See that the fields have been truncated (see also screenshot)
3. (Similar fields may also be truncated in Datasources, too, perhaps worth checking)

**Expected behavior**
The fields wouldn't be truncated

**Screenshots**
[20211118 truncated fields in databank.docx](https://github.com/molgenis/molgenis-emx2/files/7563623/20211118.truncated.fields.in.databank.docx)

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser Chrome

**Comment by mswertz** [comment]
this should be fixed on 8.27.3. Please verify

**Comment by mswertz** [comment]
resolved
