### ISSUE TITLE
Athlete/Longitools/etc catalogue is missing the 'Show/hide empty fields' button in Cohorts

### ISSUE THREAD

**Issue by EleanorHyde-UMCG** [molgenis/molgenis-emx2#737]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In Institutions, Data sources and Data banks we have a button which gives the user the option to show/hide empty fields. This has not yet been implemented in Cohorts but would be very useful there.

**Describe alternatives you've considered**
Not having the button - but this isn't useful.

**Additional context**
NB the cohorts page is set up differently to Institutions etc, so the technical solution needs to be discussed.

**Comment by connoratrug** [comment]
Not part of the current cohort page design ( not included in the proposed designs).
empty fields are hidden by default, no use case for looking at empty fields.
