### ISSUE TITLE
'Show more' does not work in Catalogue tables

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#770]
**What version of EMX2 are you using (see footer)**
8.28.1

**Describe the bug**
When you click on 'show more' in tables that you enter via the Catalogue (e.g. Cohorts, Databanks) you are redirected to the Cohort detail view or Databank detail view. You should be seeing more text in the table itself.

**To Reproduce**
1. Go to 'https://catalogue-acc.molgeniscloud.org/UMCG/catalogue/#/'
2. Click on 'Cohorts'
3. Click on 'see more' in keywords column

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by connoratrug** [comment]
can not reproduce, please reopen if needed and update step to reproduce
