### ISSUE TITLE
User list in admin page is not scrollable 

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#774]
**What version of EMX2 are you using (see footer)**
8.30.0

**Describe the bug**
User list in admin page is not scrollable 

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org' ( server that runs 8.30.0)
2. Sign in as 'admin'
3. View the users list 

**Expected behavior**
can scroll down the list of users when list is longer then display port

**Comment by mswertz** [comment]
the page as a whole is scrollable right? i.e. what is the bug or feature request?

**Comment by connoratrug** [comment]
"the page as a whole is scrollable right?" No it's not, it's a bug and labeled as such. It stops the admin user from viewing the entire list of users
