### ISSUE TITLE
Forms does not scale well on half screen

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#821]
**What version of EMX2 are you using (see footer)**
8.32.4

**Describe the bug**
When catalogue is displayed on half screen, forms does not scale well. The form is very narrow. Form becomes less narrow when displaying at 90%.

**To Reproduce**
1. Go to an emx2 server and reduce the window to half of your screen
2. Open a form

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mswertz** [comment]
cannot really reproduce except that I notice I need to scroll horizontally. Is there example form you have in mind?

**Comment by mswertz** [comment]
Indeed. we should reduce spacers on smaller screens so modal is full screen and headers/footers are compressed? Or rethink towards a mobile rendering of the form that pushes the save buttons into header so we can save even more space?
