### ISSUE TITLE
Can ontology trees that are short be unfolded in the forms view

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#843]
**Is your feature request related to a problem? Please describe.**
Ontology trees are at the moment folded in, with only the first nodes visible. For short/small ontologies (such as age groups) the tree may be unfolded standardly, so you can see all options straight away.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mswertz** [comment]
what would be the criterium? total number of items <20 or something?
