### ISSUE TITLE
Spaces in front of ID causes errors and strange behaviour.

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#848]
**What version of EMX2 are you using (see footer)**
8.32.4

**Describe the bug**
I tried to add rich metadata for a cohort. This cohort provided DOIs for publications that had a space in front of the DOI. When I added these DOIs in the publications tabel, I could see them and also select them in the cohort view. However, when I then tried to save the cohort I got an error:
`Error: Update into table ‘Cohorts’ failed.: Transaction failed: insert or update on table “Resources” violates foreign key (ref_array) constraint.Key (“publications”)=(https://doi.org/10.1007/s10654-008-9309-4) is not present in table “Publications”, column(s)(“doi”): Cannot commit transaction`

Also, the publication existed in the publications tabel, but when I tried to edit the publication the form was empty.

**To Reproduce**
1. Go to 'https://data-catalogue.molgeniscloud.org/catalogue/tables/#/Publications
2. Add a new publication but with a space (' ') in front of the ID.
3. The publication is created (and you can download it) but when you open the edit form you will see an empty form
4. Go to the cohorts (https://data-catalogue.molgeniscloud.org/catalogue/tables/#/Cohorts)
5. Add the publication you just created to a cohort. You can select the publication but when you try to save the cohort you will get the previously described error.

**Comment by mswertz** [comment]
what is the desired behavior? That we strip the spaces?
