### ISSUE TITLE
When uploading OntologyTerm data with already used name (but not the same 'code'), data row with that name from a different ontologyterms table may be imported.

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#849]
**What version of EMX2 are you using (see footer)**
8.35.3

**Describe the bug**
When uploading OntologyTerm data with already used name (but not the same 'code'), data row with that name from a different ontologyterms table may be imported.
For instance upload this zip file: 
[zip.zip](https://github.com/molgenis/molgenis-emx2/files/7822592/zip.zip)

Upload gives no error, but ontologyterms with a same name will appear in the wrong table and the downloaded data also differs.

**To Reproduce**
1. Go to an emx2 server
2. upload zip file: [zip.zip](https://github.com/molgenis/molgenis-emx2/files/7822601/zip.zip)
3. Compare data in Table1 and Table2 in zip file to data in Table1 and Table2 in database (look at 'code' column for row differences). 
4. All data with the same 'name' in Table2 is 'replaced' by the data in Table1 
5. If you download the data all data with the same name in Table1 as in Table2 is not in the download for Table2.

**Expected behavior**

**Comment by connoratrug** [comment]
Please _fill-out all relevant sections_ of the issue template and _delete_ all empty/non relevant sections, this helps triage / fix the issue
