### ISSUE TITLE
Topics menu in the variable explorer does not show all topics and variables

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#851]
**What version of EMX2 are you using (see footer)**
8.32.4

**Describe the bug**
Only till the level 'sub-sub-sub-folder' variables are shown, but the lower folders are missing, making the variables invisible as well.

**To Reproduce**
For example, the old lifecycle (lifecycle.molgeniscloud.org) shows many more sub folders including their variables
<img width="1064" alt="Screenshot 2022-01-06 at 15 20 57" src="https://user-images.githubusercontent.com/8653334/148397288-a95deb0d-ac75-4f7c-b508-b54eb98d977d.png">

But these are missing in the new variable view, making the variables invisible too
![Screenshot 2022-01-06 at 15 20 38](https://user-images.githubusercontent.com/8653334/148397366-2321282b-4ec5-40b0-9569-c29c26e3b262.png)

However, when you search for a particular variable it actually does exist, but it disappears again when you select the subsequent folder.
![Screenshot 2022-01-06 at 15 23 31](https://user-images.githubusercontent.com/8653334/148397612-5317aa4a-f5aa-41b4-a29d-424bf19d95ee.png)

**Comment by mswertz** [comment]
thanks, well spotted. i will fix this as part of #816
