### ISSUE TITLE
Deleting item from a refback attribute while editing another row give SQL error

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#868]
**What version of EMX2 are you using (see footer)**
8.32.4

**Describe the bug**
When deleting an item from a refback attribute, while you are editing another data row from another tabel, gives a SQL error upon saving:
`Error: Update into table 'Pet' failed.: Transaction failed: SQL [update "pet store"."Pet" set "name" = 'test', "orders" = cast('{"test","test1"}' as varchar[]), "category" = 'cat', "mg_draft" = false, "mg_updatedBy" = 'admin', "mg_updatedOn" = timestamp '2022-01-11 14:26:27.85265409' where "name" = 'test']; Batch entry 0 update "pet store"."Pet" set "name" = 'test', "orders" = cast('{"test","test1"}' as varchar[]), "category" = 'cat', "mg_draft" = false, "mg_updatedBy" = 'admin', "mg_updatedOn" = timestamp '2022-01-11 14:26:27.85265409' where "name" = 'test' was aborted: ERROR: record "my_row" has no field "orderId" Where: SQL statement "SELECT 'Key ('||'orders'||')=('|| COALESCE(my_row."orderId",'NULL') ||') is not present in table '||'Order'||', column '||'orderId'" PL/pgSQL function "pet store"."1Pet-orders_UPDATE"() line 6 at RAISE Call getNextException to see other errors in the batch..: SQL [update "pet store"."Pet" set "name" = 'test', "orders" = cast('{"test","test1"}' as varchar[]), "category" = 'cat', "mg_draft" = false, "mg_updatedBy" = 'admin', "mg_updatedOn" = timestamp '2022-01-11 14:26:27.85265409' where "name" = 'test']; Batch entry 0 update "pet store"."Pet" set "name" = 'test', "orders" = cast('{"test","test1"}' as varchar[]), "category" = 'cat', "mg_draft" = false, "mg_updatedBy" = 'admin', "mg_updatedOn" = timestamp '2022-01-11 14:26:27.85265409' where "name" = 'test' was aborted: ERROR: record "my_row" has no field "orderId" Where: SQL statement "SELECT 'Key ('||'orders'||')=('|| COALESCE(my_row."orderId",'NULL') ||') is not present in table '||'Order'||', column '||'orderId'" PL/pgSQL function "pet store"."1Pet-orders_UPDATE"() line 6 at RAISE Call getNextException to see other errors in the batch.`

However, the item is actually deleted.

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/pet%20store/tables/?#/Pet'
2. Open the editing form for 'test'
3. Delete one of the orders (last attribute)
4. Click save; form will show error
6. When you close the editing form and open again, you will see the error is actually deleted.

**Comment by chinook25** [comment]
@marijevdgeest Cannot reproduce in v8.213.25. Is this still an issue for you?

**Comment by marijevdgeest** [comment]
> 1. https://emx2.dev.molgenis.org/pet%20store/tables/?#/Pet
No :)
