### ISSUE TITLE
Download zip in firefox results in file without .zip extension

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#886]
**What version of EMX2 are you using (see footer)**
8.40.2

**Describe the bug**

**To Reproduce**
With a Firefox browser
1. Go to 'https://data-catalogue.molgeniscloud.org/catalogue/tables/#/'
2. Click on 'Download all tables: zip'
3. File will download but without .zip extension
4. see screenshot

**Expected behavior**
Expect to download zip.zip instead I'll get zip

**Screenshots**
![molgenis_8 40 2_tables](https://user-images.githubusercontent.com/4077085/149909400-34944f42-47d1-4ec5-867f-3112a9c29e65.png)
![molgenis_8 40 2_download-zip-without-extention_Firefox-96](https://user-images.githubusercontent.com/4077085/149909556-094e0f23-2700-4d44-8dec-6e84fff81c4d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3
 - Browser Firefox
 - Version 96.0

**Additional context**
Also tested in Chrome, this works fine

**Comment by esthervanenckevort** [comment]
Can't reproduce.
