### ISSUE TITLE
Authentication via CURL

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis-emx2#902]
CURL imports fail due to not being logged in, would be nice to add login credentials to CURL calls

example:
```
curl -X POST --data-binary @molgenis.csv http://localhost:8080/fairgenomes/api/csv
{
  "errors" : [
    {
      "message" : "Cannot invoke \"org.molgenis.emx2.Schema.migrate(org.molgenis.emx2.SchemaMetadata)\" because the return value of \"org.molgenis.emx2.web.MolgenisWebservice.getSchema(spark.Request)\" is null"
    }
  ]
}%
```

**Comment by mswertz** [comment]
actually, there should be already a way to do it. It should be something like sign in via curl, retrieve a session cookie and use in the next call. In that case this is just documentation not code

**Comment by connoratrug** [comment]
example of signin using http: https://github.com/molgenis/molgenis-py-cohorts-etl/blob/deeddcd20081834a4c0ab29bcacb380a7e2a6f72/client.py#L23-L50

should also work for curl ( send post with signin mutation)

**Comment by joerivandervelde** [comment]
How to send the sign-in via Curl ? looking for something like

```
curl POST -user:admin -pw:admin http://localhost:8080/api/login
```

**Comment by mswertz** [comment]
You should use a session to keep the session id which binds your user.

We also are in process of implementing token based auth, see #986
