### ISSUE TITLE
ColumnType int throws subSelectionRequired error

### ISSUE THREAD

**Issue by davidruvolo51** [molgenis/molgenis-emx2#922]
**What version of EMX2 are you using (see footer)**
8.43.1

**Describe the bug**

Column that has the type `int` throws the following error.

```
Error: Validation error of type SubSelectionRequired: Sub selection required for type speciesAggregatorForcount of field count @ 'species_agg/count'
``` 

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'
2. Click on '+' to create a new database
3. Import attached schema into the new database
4. Navigate to the table `species`
5. See error

**Expected behavior**
All data should be visible

**Desktop (please complete the following information):**
 - OS: macOS v10.15.7
 - Browser: Firefox
 - Version: 96.0.2
 
**Additional context**
None
[birddata_emx2.xlsx](https://github.com/molgenis/molgenis-emx2/files/7950499/birddata_emx2.xlsx)

**Comment by davidruvolo51** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#8806: There is a running EMX2 version of cosas, variant database, ucu](https://trello.com/c/zC4wa7El/332-8806-there-is-a-running-emx2-version-of-cosas-variant-database-ucu)

**Comment by mswertz** [comment]
Ah, interesting bug. I suspect the colum name 'count' puts the query off track. 
The problem is that 'count' is a reserved word in the graphql (yes, that is obviously a mistake, we should have called it _count).
