### ISSUE TITLE
Loading of some tables is very slow

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#933]
**What version of EMX2 are you using (see footer)**
8.43.3

**Describe the bug**
Some tables load very slowly. e.g. SourceVariables, AllSourceVariables.

**To Reproduce**
1. Go to ['data-catalogue.molgeniscloud.org'](https://data-catalogue.molgeniscloud.org/catalogue/tables/#/)
2. Click on 'AllSourceVariables'
3. Try searching for a cohort in the search bar, this is also very slow.

**Comment by mswertz** [comment]
It might be a server issue. On my system the request takes <300ms, on remote server it takes 3000ms, about 10x slower.
