### ISSUE TITLE
Cannot download data

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#940]
**What version of EMX2 are you using (see footer)**
8.43.3

**Describe the bug**
Cannot download data in zip

**To Reproduce**
1. Go to data-catalogue.molgeniscloud.org
2. Click on up/download
3. click on export data as csv.zip

**Comment by connoratrug** [comment]
@BrendaHijmans any schema or a specific schema ?

**Comment by erikzwart** [comment]
Export all data as csv.zip does not work
![molgenis_8 43 3_download-zip](https://user-images.githubusercontent.com/4077085/152310740-c53de448-dd0e-435a-a294-bf7068a48dd5.png)

**Comment by connoratrug** [comment]
@erikzwart what schema are u trying to download ? please add all the steps needed to reproduce the issue

**Comment by connoratrug** [comment]
updated the server to 8.45.1, can not reproduce , please reopen if this happend again, and add all error information
